### ISSUE TITLE
Cannot set "native" kafka properties in KafkaBinderConfigurationProperties

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-stream#1081]
The "configuration" attribute of KafkaBinderConfigurationProperties is defined as a `Map<String,Object>` and if you want to set any of the native, dotted notation Kafka properties, they end up being mapped wrong into the map: 

```yml
spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            max.block.ms: 1000
```

Ends up being mapped to : `max={block={ms=1000}}`

I believe if the data type of that map is changed to `Map<String,String>` the value should be mapped correctly. This change would be consistent with how both `KafkaConsumerProperties` and `KafkaProducerProperties` map their `configuration` attribute.
