### ISSUE TITLE
custom headers are covered when using Spring Cloud Sleuth Stream

### ISSUE THREAD

**Issue by guomin2014** [spring-cloud/spring-cloud-stream#1099]
I use spring cloud sleuth stream with a zipkin stream collector with Kafka, I can send the messages and see the messages on console-consumer on Kafka, but custom headers are not coming with messages on console-consumer on Kafka, I remove spring cloud sleuth stream, it is ok. (PS: spring-cloud.version: Dalston.SR3)
**Application A**
pom.xml
```
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-stream-binder-kafka</artifactId>
</dependency>
```
application.yml
```
spring
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181,localhost:2182,localhost:2183
          brokers: localhost:9092,localhost:9093,localhost:9094
          autoCreateTopics: false
          autoAddPartitions: false
          headers: method,elapsedTime
      bindings:
        app-output:
          destination: event-call
          content-type: application/json
          producer:
            partitionCount: 10
```
MessageService.java
```
@EnableBinding(AppProcessor.class)
public class MessageService
{
    @Autowired
    private MessageChannel channel;
    public void sendMsg(String msg)
    {
        Message<?> message = MessageBuilder.withPayload(msg)
				.setHeader("method", "api.joyes.cn.sale.query")
				.setHeader("elapsedTime", "15")
				.build();
        channel.send(message);
    }
}
```
**Application B**
```
@EnableBinding(AppProcessor.class)
public class MessageHandler
{
  @StreamListener(AppProcessor.INPUT)
	public void receiveMessage(Message<?> message) {
		System.out.println("receive message-->" + message);
	}
}
```
I send a message with **MessageService.sendMsg**, Application B receive and print message:
```
receive message-->GenericMessage [payload=hello word, headers={spanId=0199c4f0ad48a978, spanTraceId=0199c4f0ad48a978, spanParentSpanId=0199c4f0ad48a978, kafka_offset=7257, messageSent=true, id=ab20f289-47c6-e11a-11f4-225d695d6293, spanSampled=1, kafka_receivedPartitionId=5, contentType=application/json, kafka_receivedTopic=event-call, spanName=message:app-output}]
```
custom headers is missing! but, remove spring-cloud-sleuth-zipkin-stream from pom.xml, Application B receive message incloud custom headers
**Application A -- pom.xml**
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-stream-binder-kafka</artifactId>
</dependency>
```
Application B receive and print message:
```
receive message-->GenericMessage [payload=hello word, headers={spanTraceId=0d23f0ecc2ac72f6, spanId=0d23f0ecc2ac72f6, method=api.joyes.cn.sale.query, kafka_offset=7254, messageSent=true, id=5c46b684-ac2c-40ce-abc7-053bcf9c4ea9, elapsedTime=15, kafka_receivedPartitionId=6, spanSampled=1, contentType=application/json, kafka_receivedTopic=event-call, spanName=message:app-input}]
```
I check the spring-cloud-sleuth-stream source code, found the question in **org.springframework.cloud.sleuth.stream.StreamEnvironmentPostProcessor**
```
private int findStartIndex(ConfigurableEnvironment environment, String binder) {
	String prefix = "spring.cloud.stream." + binder + ".binder.headers";
	int i = 0;
	while (environment.getProperty(prefix + "[" + i + "]")!=null) {
		i++;
	}
	return i;
}
```
This method determines where the trace header is added, but i define it as a single property at application.yml(like this '**headers: method,elapsedTime**'), it can't get the value here, so the index of the trace head starts at 0, I print out the header information in the order of initialization, I can see the custom headers are covered
```
{
spring.cloud.stream.kafka.binder.zkNodes='spring.cloud.stream.kafka.binder.zkNodes' from 'applicationConfig: [classpath:/application.yml]',
spring.cloud.stream.kafka.binder.brokers='spring.cloud.stream.kafka.binder.brokers' from 'applicationConfig: [classpath:/application.yml]',
spring.cloud.stream.kafka.binder.autoCreateTopics='spring.cloud.stream.kafka.binder.autoCreateTopics' from 'applicationConfig: [classpath:/application.yml]',
spring.cloud.stream.kafka.binder.autoAddPartitions='spring.cloud.stream.kafka.binder.autoAddPartitions' from 'applicationConfig: [classpath:/application.yml]',
spring.cloud.stream.kafka.binder.headers='spring.cloud.stream.kafka.binder.headers' from 'applicationConfig: [classpath:/application.yml]',
spring.cloud.stream.kafka.binder.headers[4]='spring.cloud.stream.kafka.binder.headers[4]' from 'defaultProperties',
spring.cloud.stream.kafka.binder.headers[3]='spring.cloud.stream.kafka.binder.headers[3]' from 'defaultProperties',
spring.cloud.stream.kafka.binder.headers[5]='spring.cloud.stream.kafka.binder.headers[5]' from 'defaultProperties',
spring.cloud.stream.kafka.binder.headers[0]='spring.cloud.stream.kafka.binder.headers[0]' from 'defaultProperties',
spring.cloud.stream.kafka.binder.headers[2]='spring.cloud.stream.kafka.binder.headers[2]' from 'defaultProperties',
spring.cloud.stream.kafka.binder.headers[1]='spring.cloud.stream.kafka.binder.headers[1]' from 'defaultProperties'
}
```
so, I use the following 2 ways to modify the configuration from application.yml, the custom header are coming with messages on console-consumer on Kafka, After using spring-cloud-sleuth-zipkin-stream, you can`t define it as a single property (like this: headers: method,elapsedTime)
```
spring
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181,localhost:2182,localhost:2183
          brokers: localhost:9092,localhost:9093,localhost:9094
          autoCreateTopics: false
          autoAddPartitions: false
          headers: 
            - method
            - elapsedTime
```
```
spring
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181,localhost:2182,localhost:2183
          brokers: localhost:9092,localhost:9093,localhost:9094
          autoCreateTopics: false
          autoAddPartitions: false
          headers[0]: method
          headers[1]: elapsedTime
```

PS: My revised version
**org.springframework.cloud.sleuth.stream.StreamEnvironmentPostProcessor**
```
private int findStartIndex(ConfigurableEnvironment environment, String binder) {
	String prefix = "spring.cloud.stream." + binder + ".binder.headers";
	int i = 0;
        String oldHeaders = environment.getProperty(prefix);
        if (oldHeaders != null) {
            i = oldHeaders.split(",").length;
        }
	while (environment.getProperty(prefix + "[" + i + "]")!=null) {
		i++;
	}
	return i;
}
```
