### ISSUE TITLE
On Kafka， Two Consumer at the same group still get the same message.

### ISSUE THREAD

**Issue by wxiaoqi** [spring-cloud/spring-cloud-stream#1117]
I just use spring cloud stream to produce a message and two consumer in the same group.
When I produce a message，two consumer receive the same message in the same time.
What should I do to config that two consumer in the same group which only on can consume the message.
such like this
```
# Consumer's1
GenericMessage [payload=123, headers={kafka_offset=3, kafka_messageKey=null, kafka_topic=text1, kafka_partitionId=1, kafka_nextOffset=4, contentType=text/plain}]
# Consumer's2
GenericMessage [payload=123, headers={kafka_offset=3, kafka_messageKey=null, kafka_topic=text1, kafka_partitionId=1, kafka_nextOffset=4, contentType=text/plain}]
```
# Producer's properties
```
spring:
  application:
    name: producer
  cloud:
     instance-count: 1
     instance-index: 0
     kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 2
     stream:
        bindings:
          output:
            destination: text1
            content-type: text/plain
            auto-add-partitions: true
            producer:
              partitionCount: 4
              partitioned: true

```

# Consumer's 1 properties
```
spring:
  application:
    name: treadmill-analytics
  cloud:
     instance-count: 1
     instance-index: 0
     kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
          offsetUpdateCount: true
     stream:
        bindings:
          input:
            destination: text1
            group: s2
            consumer:
#              autoCommitOffset: false
              concurrency: 1
              partitioned: true
server:
  port: 8082
```

# Consumer's 2 properties
```
spring:
  application:
    name: treadmill-analytics
  cloud:
     instance-count: 1
     instance-index: 0
     kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
          offsetUpdateCount: true
     stream:
        bindings:
          input:
            destination: text1
            group: s2
            consumer:
#              autoCommitOffset: false
              concurrency: 1
              partitioned: true
server:
  port: 8081
```

**Comment by garyrussell** [comment]
What you are describing shouldn't be possible.

Can you provide INFO level logs? The listener container reports which partitions are allocated to it.

**Comment by garyrussell** [comment]
I just ran a test with your configuration and saw this...

Consumer1:


>2017-10-31 15:54:30.283  INFO 31612 --- [           -C-1] o.s.c.s.b.k.KafkaMessageChannelBinder$3  : partitions assigned:[text1-3, text1-2, text1-1, text1-0]
foo from partition 3 at offset 8
foo from partition 3 at offset 9
...
foo from partition 2 at offset 16
foo from partition 1 at offset 16
foo from partition 3 at offset 16
2017-10-31 15:54:57.328  INFO 31612 --- [           -C-1] o.a.k.c.c.internals.ConsumerCoordinator  : Revoking previously assigned partitions [text1-3, text1-2, text1-1, text1-0] for group s2
2017-10-31 15:54:58.210  INFO 31612 --- [           -C-1] o.s.c.s.b.k.KafkaMessageChannelBinder$3  : partitions revoked:[text1-3, text1-2, text1-1, text1-0]
2017-10-31 15:54:58.210  INFO 31612 --- [           -C-1] o.a.k.c.c.internals.AbstractCoordinator  : (Re-)joining group s2
2017-10-31 15:54:58.213  INFO 31612 --- [           -C-1] o.a.k.c.c.internals.AbstractCoordinator  : Successfully joined group s2 with generation 8
2017-10-31 15:54:58.213  INFO 31612 --- [           -C-1] o.a.k.c.c.internals.ConsumerCoordinator  : Setting newly assigned partitions [text1-1, text1-0] for group s2
2017-10-31 15:54:58.216  INFO 31612 --- [           -C-1] o.s.c.s.b.k.KafkaMessageChannelBinder$3  : partitions assigned:[text1-1, text1-0]
foo from partition 0 at offset 16
foo from partition 1 at offset 17


Consumer 2:

>2017-10-31 15:54:58.221  INFO 31639 --- [           -C-1] o.s.c.s.b.k.KafkaMessageChannelBinder$3  : partitions assigned:[text1-3, text1-2]
foo from partition 2 at offset 17
...

i.e. all as expected.

**Comment by wxiaoqi** [comment]
Could u send me your test code？

**Comment by garyrussell** [comment]
Producer:

```java
@SpringBootApplication
@EnableBinding(Source.class)
public class Kbgh1117Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh1117Application.class, args);
	}

	@InboundChannelAdapter(channel = Source.OUTPUT, poller = @Poller(fixedDelay = "5000"))
	public String out() {
		return "foo";
	}

}
```

```yaml
spring:
  application:
    name: producer
  cloud:
     instance-count: 1
     instance-index: 0
     kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 2
     stream:
        bindings:
          output:
            destination: text1
            content-type: text/plain
            producer:
              partitionCount: 4
              partitioned: true
```

Consumer:

```java
@SpringBootApplication
@EnableBinding(Sink.class)
public class Kbgh11171Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh11171Application.class, args);
	}

	@StreamListener(Sink.INPUT)
	public void in(String in, @Header(KafkaHeaders.RECEIVED_PARTITION_ID) int partition,
			@Header(KafkaHeaders.OFFSET) long offset) {
		System.out.println(in +  " from partition " + partition + " at offset " + offset);
	}

}
```

```yaml
spring:
  application:
    name: treadmill-analytics
  cloud:
     instance-count: 1
     instance-index: 0
     kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
          offsetUpdateCount: true
     stream:
        bindings:
          input:
            destination: text1
            group: s2
            consumer:
#              autoCommitOffset: false
              concurrency: 1
              partitioned: true
server:
  port: 8082
```

I ran two instances of the consumer (after changing the server port).
