### ISSUE TITLE
bindingRoutingKey not work

### ISSUE THREAD

**Issue by TonyLiu0112** [spring-cloud/spring-cloud-stream#1150]
I use the spring cloud + spring stream integrated rabbitmq, I hope to use routting key to distribute the message to a different queue, but it does not work.

### application.yml
``` yml
spring: 
  cloud:
    stream:
      bindings:
        comment-channel:
          producer:
            bindingRoutingKey: rk.comment
          destination: comment_publish_queue
          group: test
  rabbitmq:
    host: www.tony666.com
    username: admin
    password: admin
```

### Java 
``` java
public interface Comment {

    String OUTPUT = "comment-channel";

    @Output(Comment.OUTPUT)
    MessageChannel output();

}
```

Publish message
```java
@Component
public class CommentProvider {

    private final Comment comment;

    public CommentProvider(Comment comment) {
        this.comment = comment;
    }

    public void pushComment(ApComment apComment) {
        String json = JSON.toJSONString(apComment);
        Message<String> message = new GenericMessage<>(json, new HashMap<String, Object>() {{
            put("name", "Tony");
        }});
        MessageChannel channel = comment.output();
        channel.send(message);
    }

}
```

In the rabbitmq web console, you can see the message sent to the exchange, but not according to the routing key sent to the specified queue.

When I use the wildcard #, it works fine, or I can send the message specifying the routing key directly to the rabbitmq web console and it works.

So I guess the problem lies in the spring cloud stream side?

> Spring Cloud : Dalston.SR4
> Spring stream: 1.2.2.RELEASE
> Rabbitmq: 3.6.14, Erlang 19.2.1
