### ISSUE TITLE
How to define a single threaded handler for multiple sink bindings or input destinations?

### ISSUE THREAD

**Issue by fghawi** [spring-cloud/spring-cloud-stream#1167]
I have a requirement to check if spring cloud streams supports single threaded handler for multiple input bindings.
If I configure my app to have a single binding with 2 destination:
```
spring:
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        input:
          destination: c1,c2
          group: mygroup
          consumer:
            partitioned: true
```

and a listener:
```
    @StreamListener("input")
    public void receive(Message<?> message) {
        System.out.println("["+Thread.currentThread().getId()+"] Received1 message "+message);
    }

```
I see that the message are consumed with 2 different threads:
```
[38] Received1 message ...
[30] Received1 message ...
```
**Is there anyway to configure my app so I can control the number of handling threads, regardless of the number of the binding\destinations configured?**

Noticed that if I do similar thing using **spring-kafka**, I do see that the messages are handled by a single thread:
```
kafka:
  consumer:
    bootstrap: localhost:9092
    group: mygroup
    topic:
      - c1
      - c2
```
and:
```
   @KafkaListener(topics = {"c1","c2"})
    public void onReceiving(String msg, @Header(KafkaHeaders.OFFSET) Integer offset,
                            @Header(KafkaHeaders.RECEIVED_PARTITION_ID) int partition,
                            @Header(KafkaHeaders.RECEIVED_TOPIC) String topic) {
        System.out.println("["+Thread.currentThread().getId()+"] Processing msg = "+msg+", topic = "+topic+", partition = "+partition);
    }

```
