### ISSUE TITLE
Revisit the hierarchy of configuration properties and make them consistent

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1278]
Recently we had a few issues:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/326
https://github.com/spring-cloud/spring-cloud-stream/pull/1276
etc. . .
They are all in one way or the other tied to configuration properties hierarchies that begin with boot and transcend to SCSt and then binders.
There seem to be a bit of inconsistency, so a review is in order

**Comment by 2speed** [comment]
Greetings, I ran into an issue similar to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/326 using Spring Boot with the Kafka streams binder when attempting to bridge a stream from an external Kafka cluster. Here is a snippet from my `application.yml` file:

```
spring.cloud.stream:
  bindings:
    input:
      destination: ...
      binder: kBind1
  binders:
    kBind1:
      type: kstream
      environment:
        spring.cloud.stream.kafka.streams.binder:
          brokers: ...
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
...
```

Running the application results in the following error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field kafkaProperties in org.springframework.cloud.stream.binder.kafka.streams.KStreamBinderConfiguration required a bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' that could not be found.
```
