### ISSUE TITLE
Unable to set partitionKeyExpression for default properties (application fails to start)

### ISSUE THREAD

**Issue by dharrigan** [spring-cloud/spring-cloud-stream#1297]
Hi,

A configuration that worked with Spring Cloud Egware SR2 and Spring Cloud Stream Ditmars SR3 no longer works with Spring Boot 2, Spring Cloud Finchley M7 and Spring Cloud Stream Elmhurst RC2.

I have this in my application.yml

```
spring:
  cloud:
    stream:
      default:
        group: foo.bar
        contentType: application/json;charset=UTF-8
        producer:  &defaultProducerBindings
          headerMode: raw
          partitionCount: 12
          partitionKeyExpression: headers[ T(foo.bar.PayloadGateway).PARTITION_KEY ].getBytes()
      bindings:
        output:
          producer: *defaultProducerBindings
          destination: foo-bar
```
On launching my Spring Boot 2 application, it fails with this message:

```
Description:

Failed to bind properties under 'spring.cloud.stream.default.producer.partition-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.default.producer.partitionkeyexpression
    Value: headers[ T(foo.bar.PayloadGateway).PARTITION_KEY ].getBytes()
    Origin: class path resource [config/application.yml]:16:35
    Reason: No converter found capable of converting from type [java.lang.String] to type [@com.fasterxml.jackson.databind.annotation.JsonSerialize org.springframework.expression.Expression]

Action:

Update your application's configuration
```

If, however, I move the expression *into* the specific binding, my application starts (although at a cost of line duplication for many, many bindings (of the partitionKeyExpression line))

```
spring:
  cloud:
    stream:
      default:
        contentType: application/json;charset=UTF-8
        producer:  &defaultProducerBindings
          headerMode: raw
          partitionCount: 12
      bindings:
        output:
          producer:
            <<: *defaultProducerBindings
            partitionKeyExpression: headers[ T(foo.bar.PayloadGateway).PARTITION_KEY ].getBytes()
          destination: foo-bar
```

On stepping through the code, in the first example, the partitionKeyExpression *is* set on ProducerProperties. Of course, it is also set in the second binding-specific example.

Has this behaviour changed, if so and is intentional, then no problemo :-) Otherwise, I would expect the same configuration as before to still work.

Thank you.

-=david=-
