### ISSUE TITLE
partitionKeyExtractorName isn't honored unless partitionKeyExtractorClass is also set

### ISSUE THREAD

**Issue by infa-jerry** [spring-cloud/spring-cloud-stream#1330]
In the application.yml file:
```
spring:
  cloud:
    stream:
      bindings:
        test-source:
          destination: testtock
          producer:
            partitionKeyExtractorName: keyextractor
            partitionSelectorName: partitionselector
#            partitionKeyExtractorClass: demo.KeyExtractor
#            partitionSelectorClass: demo.PartitionSelector

```
This does not work unless I uncomment the partitionKeyExtractorClass as well. Even in that case, it results in two instances of the class being created (one from the @Bean annotation and one from the class name provided here). It seems to be a problem with the below line of code:
https://github.com/spring-cloud/spring-cloud-stream/blob/0656c23f1e9de2e497c211d4b5a9c7df6b407361/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/PartitionHandler.java#L98
When it reaches this line, this.partitionKeyExtractorStrategy is properly initialized, but the code incorrectly checks for this.producerProperties.getPartitionKeyExtractorClass() != null.
