### ISSUE TITLE
Specific bindings params is overridden by default ones

### ISSUE THREAD

**Issue by Viacheslav-Petriaiev** [spring-cloud/spring-cloud-stream#1359]
I have a configuration
```
spring:
  cloud:
    stream:
      default:
        contentType: someDefaultContentType
      bindings:
        someChannel:
          contentType: someSpecificContentType
```
and someChannel.contentType is someDefaultContentType instead of someSpecificContentType

I've investigated the class
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/EnvironmentEntryInitializingTreeMap.java

Default configuration overrides the specific configuration, instead of merge mechanism

Is it a bug or it works as designed?
If it works as designed, the param name "default" is ambiguous, because default usually can be overridden with non-default value
It would be very convenient behavior when default values can be overridden with specific ones
