### ISSUE TITLE
"Group" property configuration for RabbitMQ is triggering job operator multiple times with same parameters, after consumer restart.

### ISSUE THREAD

**Issue by ravi28** [spring-cloud/spring-cloud-stream#1367]
We have an application that is using spring-cloud-stream with RabbitMQ as binder. We are seeing issues during a specific scenario as described below

* Scale down consumer instances to zero.
* A request from producer application is initiated and is in the queue waiting to be picked up.
* Scale up consumer instance to one and it processes the job in the queue after it starts.

To support scaling up of consumer instances we have added the "group" property to our configuration so that it now looks as shown below 
```
spring.cloud:
  stream:
    bindings:
      # inputs
      sandboxOperationRequestInput:
        destination: "sandboxTaskRequests"
        content-type: "application/json"
        group: operator
        consumer:
          maxAttempts: 1
      # outputs
      sandboxStatusEventOutput:
        destination: "sandboxStatusEvents"
        content-type: "application/json"
```
Since we added the "group" property the above scenario has been failing. Once the consumer is scaled up to one instance we are noticing that Request Listener is triggering job operator multiple times with the same job parameters which is undesired. As a result the job is failing due to JobInstanceAlreadyExistsException. I've tried changing multiple configurations but in vain. Can someone please suggest if I'm missing something? Any leads to what is causing this will be very helpful.

You can access the full logs for both [working](https://gist.github.com/ravi28/3c8d83bba9e698369cf60259d1ac819b) and [failing](https://gist.github.com/ravi28/00498caa4f761a33124b456fb8e3d0bc) scenarios.
