### ISSUE TITLE
Multiple binders configuration results in unnecessary default auto-config

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1392]
While working on [this issue](https://github.com/spring-cloud/spring-cloud-stream/issues/1384) realized that multi-binder configuration results in 3 instances of the `ConnectionFactory` and other components that are never used. This is due to the default auto-configs coming from boot where those defaults are never used.
Easiest way to reproduce it is
```
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: input
          binder: rabbit1
        output:
          destination: output
          binder: rabbit2
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
```
