### ISSUE TITLE
@Transformer and @Splitter Annotations not activating Avro message converter

### ISSUE THREAD

**Issue by dmarmugi** [spring-cloud/spring-cloud-stream#1461]
Opening per comments in (https://stackoverflow.com/questions/51994226) 
With an application.yml that contains
```yml
spring:
  cloud:
    stream:
      bindings:
        output:
          content-type: application/*+avro
          destination: output2
      schema-registry-client:
        endpoint: http://localhost:9999
      schema:
        avro:
          schema-locations:
          - classpath:avro/generated/SkinnyMessage.avsc
```
And a SkinnyMessage like 
```json
{
  "type" : "record",
  "name" : "SkinnyMessage",
  "namespace" : "com.example.avro",
  "fields" : [ {
    "name" : "id",
    "type" : [ "null", "string" ]
  }, {
    "name" : "guid",
    "type" : [ "null", "string" ]
  } ]
}
```

This groovy App will fail as it tries to serialize the avro message with the Json converter: 
```java
@SpringBootApplication
@EnableBinding(Processor.class)
@EnableSchemaRegistryClient
class SoExample {
    @Value(value = "classpath:output.json")
    private Resource mockQueryResponse
    
    //This one doesn't work
    @Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
    SkinnyMessage queryTransformer(def trigger){
        log.info "Received message"
        def response = new JsonSlurper().parse(mockQueryResponse.getInputStream())

        def first = response._embedded.data[0]
        return SkinnyMessage.Builder.newInstance()
                .setGuid(first.guid)
                .setId(first._links.self['href'])
                .build()
    }
    
    static void main(String[] args) {
        SpringApplication.run SoExample.class, args
    }
}
```

The `mockQueryResponse` looks like
```json
{
  "_embedded" : {
    "data" : [ {
      "guid" : "c75320e9-810f-4b71-aec8-5f3821790d20",
      "_links" : {
        "self" : {
          "href" : "https://example.com/resource/2624414"
        },
        "resourceEntity" : {
          "href" : "https://example.com/resource/2624414"
        }
      }
    }, {
...
```

Switching to a `@StreamListener/@SendTo` annotation worked as expected. 

# What I expected
The `spring.cloud.stream.bindings.output.content-type: application/*+avro` should make the Transformer use the Avro MessageConverter to wrap the message

# What happened
The Avro MessageConverter didn't take the message, so SCS fell-back to the Json converter, which couldn't handle the payload: 
> Caused by: org.springframework.messaging.converter.MessageConversionException: Could not write JSON: Not a map...
