### ISSUE TITLE
Setting default `useNativeEncoding` for all channels/bindings does not work when `destination` is set for a particular binding

### ISSUE THREAD

**Issue by lendle** [spring-cloud/spring-cloud-stream#1473]
I'm using spring boot 2 and spring-cloud-stream Elmhurst.SR1. 

Per the [docs](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.SR1/reference/htmlsingle/#_producer_properties), I'm setting `spring.cloud.stream.default.producer.useNativeEncoding: true` in `application.yml`. (Actually, `bootstrap.yml` because I'm using spring-cloud-config, but I don't think that matters.)

This setting does not seem to be applied, because content-type conversions are still being applied to messages. If I set `spring.cloud.stream.bindings.<channel-name>.producer.useNativeEncoding: true`, it is applied for that binding.

Unless I'm misunderstanding the docs, I believe this is a bug.

**Comment by sobychacko** [comment]
@lendle This could possibly be a bug. The content type conversion interceptors are still applied even if `nativeEncoding` is set on the default producer. Thanks for reporting. Bug fix contributions are welcomed!

**Comment by olegz** [comment]
Actually I am not really sure what this issue is about . 
I just tried to set `spring.cloud.stream.default.producer.useNativeEncoding=true` and all worked fine, the `SendingHandler`  was set with it being `true` essentially returning an "untouched" message
```
Message<?> messageToSend = (this.useNativeEncoding) ? message
					: serializeAndEmbedHeadersIfApplicable(message);
```
May be it is related to `bootstrap.yml`. . . not sure. . .
Perhaps a test case or some details on how to reproduce. . .

**Comment by lendle** [comment]
I'll try to create a minimal example.

On Mon, Sep 10, 2018 at 11:04 AM, Oleg Zhurakousky <notifications@github.com

**Comment by lendle** [comment]
I cannot reproduce in a minimal example. I have no idea under what conditions it's happening. I'll reopen the issue if I figure it out.

**Comment by lendle** [comment]
I've found the issue. See https://github.com/lendle/spring-kafka-config-demo/tree/use-native-encoding, note branch `use-native-encoding`.

The issue occurs when I also [set the destination of a particular channel](https://github.com/lendle/spring-kafka-config-demo/blob/use-native-encoding/src/main/resources/application.yml#L9). When I do that, `spring.cloud.stream.default.producer.useNativeEncoding: true` is not applied, and the app fails when trying to convert the object `MyClass` to JSON by the content converter. (This is because `MyClass.java` as generated by the gradle avro plugin I'm using isn't compatible with jackson.)

If I set `spring.cloud.stream.bindings.output.producer.useNativeEncoding: true`, things work as expected.

**Comment by sabbyanandan** [comment]
Relates to #1470.

**Comment by lendle** [comment]
Yes that looks to be related. I'm guessing the underlying issue is that if any properties (or maybe specifically `destination`) are specified for a particular binding, then default properties are forgotten.

**Comment by olegz** [comment]
So, yes, indeed the issue with `default` is that it only works if there are no binding specific configurations. As soon as you add one, default values no longer exist.

**Comment by dharrigan** [comment]
Hi,

Java: 1.8u181
Spring Boot: 2.0.5
Spring Cloud Stream: Elmhurst.RELEASE (and Elmhurst.SR1)
Spring Cloud: Finchley.SR1

Ouch! This is a pretty big regression for us. When upgrading from Elmhurst.RELEASE to Elmhurst.SR1, we wondered why our default properties were not being honoured anymore. Here is a snippet of our (slightly modified to protect the innocent) application.yml

```
spring:
  application:
    name: foo
  cloud:
    stream:
      default:
        group: ${spring.application.name}
        contentType: application/json;charset=UTF-8
        producer: &defaultProducerBindings
          partitionCount: 1
          headerMode: none
          sync: true
      bindings:
        amazingTopic:
          destination: amazing
          producer: *defaultProducerBindings
        slightlyInterestingTopic:
          destination: slight-interesting
          producer: *defaultProducerBindings
        boringTopic:
          destination: boring
          producer: *defaultProducerBindings
```

Then the specific application-production.yml that we "apply" in production using a "spring.config-locations" override:

application-production.yml
```
spring:
  cloud:
    stream:
      default:
        producer:
          partitionCount: 12
```

When running with Elmhurst.RELEASE, then 12 partitions are created. When running with Elmhurst.SR1, only 1 partition is created (i.e., the "override" is ignored...)

I believe this is related to this bug.
