### ISSUE TITLE
A custom `ConnectionNameStrategy` is ignored if there is a custom binder configuration

### ISSUE THREAD

**Issue by kinjelom** [spring-cloud/spring-cloud-stream#1541]
A custom `ConnectionNameStrategy` is ignored if there is a custom binder configuration.
Configuration without a custom binder works ok.

### Configuration and code to reproduce this case

Spring Boot: 2.0.6.RELEASE
Spring Cloud: Finchley.RELEASE

```yaml
spring.cloud.stream:
  binders:
    demoinout:
      type: rabbit
      defaultCandidate: false
      inheritEnvironment: false
      environment.spring.rabbitmq:
        host: localhost
        port: 5672
        virtual-host: demo
        username: demo
        password: demo
  bindings:
    input:
      binder: demoinout
      destination: in-demo-a-dest
      group: in-demo-a-group
    output:
      binder: demoinout
      destination: out-demo-b-dest
      group: out-demo-b-group
```

```java
@Configuration
public class MessagingConfiguration {

	@Bean
	public ConnectionNameStrategy defineConnectionNameStrategy() {
		return connectionFactory -> "demo#"+UUID.randomUUID().toString().substring(0, 8);
	}

}
```

```java
@Service
@EnableBinding(Processor.class)
public class MessagingProcessorService {

	@Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
	public Message<byte[]> demoProcessor(@Payload final byte[] body, @Headers Map<String, Object> headers) {
		return MessageBuilder.withPayload(body).copyHeaders(headers).build();
	}
}

```

-----
In this case Spring creates two `CachingConnectionFactory` (publisher: false, true) and set them connection strategy to one defined as a bean `ConnectionNameStrategy`. 
After that `DefaultBinderFactory` creates another two `CachingConnectionFactory` but **doesn't set defined `ConnectionNameStrategy`**:
```
at   org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
--
at   org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:206)
at   org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:139)
at   org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:308)
at   org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:208)
at   org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:252)
at   org.springframework.cloud.stream.binding.OutputBindingLifecycle.doStartWithBindable(OutputBindingLifecycle.java:46)
at   java.util.Iterator.forEachRemaining(Iterator.java:116)
at   java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at   java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
at   org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47)
at   org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:29)
at   org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
at   org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
at   org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
at   org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
at   org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
at   org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at   org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
at   org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
```

**Comment by olegz** [comment]
This appears to be due to parent/child application context relationship.
I am not ready to classify this as a bug since in a multi-binder scenario there should be some kind of additional qualifier to then specify which binder this strategy should be applied to especially considering there may be several (one per binder).

**Comment by wildloop** [comment]
In my case I want to apply the same custom ConnectionNameStrategy to all binders.

**Comment by olegz** [comment]
I understand, but as a framework we need to think of all cases

**Comment by wildloop** [comment]
I understand, just consider applying to `all binders` too :)

**Comment by wildloop** [comment]
This issue is related to: https://github.com/spring-projects/spring-boot/issues/12367

In case like below the custom ConnectionNameStrategy:
- was applied to the binder `demoin` (inherited from the default) 
- wasn't applied to the binder `demoout`

```yaml
custom.rabbitmq.connection-name-prefix: rmq-demo-single-named

spring.rabbitmq:
  host: localhost
  port: 5672
  virtual-host: demo
  username: demo
  password: demo

spring.cloud.stream:
  binders:
    demoin:
      type: rabbit
      ## inherited from the default: 
      # environment.spring.rabbitmq:
      #   virtual-host: demo
    demoout:
      type: rabbit
      environment.spring.rabbitmq:
        virtual-host: demo
  bindings:
    input:
      binder: demoin
      destination: in-demo-a-dest
      group: in-demo-a-group
    output:
      binder: demoout
      destination: out-demo-b-dest
      group: out-demo-b-group
```
