### ISSUE TITLE
actuator endpoint error if specified routingKeyExpression

### ISSUE THREAD

**Issue by nxzh** [spring-cloud/spring-cloud-stream#1614]
When I try to `GET` the `localhost:8080/actuator/bindings`, I got a error:

```
{
    "timestamp": "2019-02-13T07:15:22.085+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Could not write JSON: Direct self-reference leading to cycle (through reference chain: org.springframework.cloud.stream.binder.ExtendedProducerProperties[\"extension\"]->org.springframework.cloud.stream.binder.rabbit.properties.RabbitProducerProperties[\"routingKeyExpression\"]->org.springframework.expression.spel.standard.SpelExpression[\"ast\"]->org.springframework.expression.spel.ast.StringLiteral[\"literalValue\"]->org.springframework.expression.TypedValue[\"typeDescriptor\"]->org.springframework.core.convert.TypeDescriptor[\"resolvableType\"]->org.springframework.core.ResolvableType[\"componentType\"]->org.springframework.core.ResolvableType[\"componentType\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: org.springframework.cloud.stream.binder.ExtendedProducerProperties[\"extension\"]->org.springframework.cloud.stream.binder.rabbit.properties.RabbitProducerProperties[\"routingKeyExpression\"]->org.springframework.expression.spel.standard.SpelExpression[\"ast\"]->org.springframework.expression.spel.ast.StringLiteral[\"literalValue\"]->org.springframework.expression.TypedValue[\"typeDescriptor\"]->org.springframework.core.convert.TypeDescriptor[\"resolvableType\"]->org.springframework.core.ResolvableType[\"componentType\"]->org.springframework.core.ResolvableType[\"componentType\"]) (through reference chain: java.util.ArrayList[1]->org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$1[\"extendedInfo\"])",
    "path": "/actuator/bindings"
}
```
I am using:
spring boot: `2.1.1.RELEASE`
spring cloud: `Greenwich.RELEASE`
spring cloud starter stream rabbit: `2.1.0.RELEASE`

My configuration file looks like following:

```
spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VHOST}
  cloud:
    stream:
      bindings:
        int_input:
          destination: guilin_int
          contentType: application/json
          group: basket
          consumer:
            maxAttempts: 1
        int_output:
          destination: guilin_int
          contentType: application/json

      rabbit:
        bindings:
          int_input:
            consumer:
              acknowledgeMode: MANUAL
              autoBindDlq: true
              bindingRoutingKey: '#.basket.#'
          int_output:
            producer:
              transacted: true
              routingKeyExpression: '''order'''
```
And I have a `Processor` in code:

```
public interface IntegrationEventProcessor {
  String INPUT = "int_input";
  String OUTPUT = "int_output";

  @Input(INPUT)
  SubscribableChannel input();

  @Output(OUTPUT)
  MessageChannel output();
}
```
If I removed the `routingKeyExpression`, everything works file. Is there any wrong with my configuration?

**Comment by olegz** [comment]
My guess it is boot related, but need to take a look

**Comment by nxzh** [comment]
Don't know it is helpful about this comment. If i remove the `routingKeyExpression` and use `delayExpression` like this:

```
          int_output:
            producer:
              transacted: true
#              routingKeyExpression: '''order'''
              delayExpression: '''1'''
```
A similar error will be get:
```

{
    "timestamp": "2019-02-13T07:27:31.265+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "Could not write JSON: Direct self-reference leading to cycle (through reference chain: org.springframework.cloud.stream.binder.ExtendedProducerProperties[\"extension\"]->org.springframework.cloud.stream.binder.rabbit.properties.RabbitProducerProperties[\"delayExpression\"]->org.springframework.expression.spel.standard.SpelExpression[\"ast\"]->org.springframework.expression.spel.ast.StringLiteral[\"literalValue\"]->org.springframework.expression.TypedValue[\"typeDescriptor\"]->org.springframework.core.convert.TypeDescriptor[\"resolvableType\"]->org.springframework.core.ResolvableType[\"componentType\"]->org.springframework.core.ResolvableType[\"componentType\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: org.springframework.cloud.stream.binder.ExtendedProducerProperties[\"extension\"]->org.springframework.cloud.stream.binder.rabbit.properties.RabbitProducerProperties[\"delayExpression\"]->org.springframework.expression.spel.standard.SpelExpression[\"ast\"]->org.springframework.expression.spel.ast.StringLiteral[\"literalValue\"]->org.springframework.expression.TypedValue[\"typeDescriptor\"]->org.springframework.core.convert.TypeDescriptor[\"resolvableType\"]->org.springframework.core.ResolvableType[\"componentType\"]->org.springframework.core.ResolvableType[\"componentType\"]) (through reference chain: java.util.ArrayList[1]->org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$1[\"extendedInfo\"])",
    "path": "/actuator/bindings"
}
```
Both of these two configurable items are of Jave type: `org.springframework.expression.Expression`.
