### ISSUE TITLE
@ServiceActivator isn't publishing to proper channel

### ISSUE THREAD

**Issue by jbforth4** [spring-cloud/spring-cloud-stream#1691]
My understanding is if I don't specify a topic name in my Interface, @Input or @Output method it will use the method name as the topic name: 
```  
 @Output
 MessageChannel outputTopic();
 @Input()
 SubscribableChannel inputTopic();
```
My understanding is that I can override that topic name in my yml:
```
...
      bindings:
        outoutTopic:
          destination: ${topic.output}
        inputTopic:
          destination: ${topic.input}

topic:
  output: coolStuff
  input: alsoCoolStuff
```
My consumer works as expected with inputChannel referencing the topicName method: 
```
@ServiceActivator(inputChannel = "inputTopic")

```
I can consume topics dynamically by controlling the topic name per environment in my configurations. In this case my consumer subscribes and consumes from the topic named "alsoCoolStuff" but my producer does not work as expected: 
```
@ServiceActivator(outputChannel = "outputTopic")
```
My producer is publishing to a topic named "outputTopic" instead of "coolStuff".
Am I missing something here or is this a bug?
