### ISSUE TITLE
The number of consumers is proportional to the length of the startup

### ISSUE THREAD

**Issue by EightMonth** [spring-cloud/spring-cloud-stream#1722]
```
spring:
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${spring.rabbitmq.addresses}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
      bindings:
        event_oneLocation_consumer:
          content-type: application/json;charset=UTF-8
          destination: event_oneLocation
          group: ${spring.application.name}
          consumer: 
            header-mode: raw
            concurrency: 120
```
my application startup time used 900 seconds when setting number of consumers is 120.
by the way ,if dont set this number of consumers, rabbitmq message will accumulation.
could you please help me make startup time shorten
