### ISSUE TITLE
Ability to stop Listerners based on Binding Target

### ISSUE THREAD

**Issue by kishorekkota** [spring-cloud/spring-cloud-stream#1762]
Hello,

We have a use case where we have multiple binding on the same destination using different target name. Would it be possible to enhance changeState to take target name and stop the listeners ?

**Comment by olegz** [comment]
This has already been addressed in 2.2.0. Next time please specify which version you are referring to.

**Comment by kishorekkota** [comment]
I am currently on ..

springBootVersion = '2.1.6.RELEASE'

springCloudVersion = 'Greenwich.SR1'.

What do i need to do, to get the new version so i can start using requested feature ?

**Comment by olegz** [comment]
Simply override spring-cloud-stream version to 2.2.0.RELEASE

**Comment by kishorekkota** [comment]
Thank you for the details. I am not seeing what I am expecting. May be my questions was not clear to begin with.

Below is my rabbit mq binding definition, which listens to same exchange twice - each listener has specific header. When I try to stop the listener - I can only do it by name - which is always the destination / exchange. I am requesting a change to BindingEndpoint to allow stop/start by Binding Target in addition to Binding Name. 

Can you help me with  making sure this is the feature added to 2.2 and how to achieve this behavior ? 

```

  cloud:
    stream:
      bindings:
        consumer-input-primary:
          destination: exchange.test
          content-type: application/json

        consumer-input-secondary:
          destination: exchange.test
          content-type: application/json

```
