### ISSUE TITLE
@PollableBean not behaving as intended

### ISSUE THREAD

**Issue by mlundela** [spring-cloud/spring-cloud-stream#1846]
This producer:

    @Bean
    public Supplier<Flux<String>> sport() {
        return () -> Flux.just("Football", "Tennis");
    }

will produce two messages as expected, but only once.

With @PollableBean I expect each invocation to produce the same messages:

    @PollableBean
    Supplier<Flux<String>> sport() {
        return () -> Flux.just("Football", "Tennis");
    }

But the output is:

    {"scanAvailable":true,"prefetch":-1}
    ...

My spring cloud config is as follows:

```
spring.cloud:
  function:
    definition: sport
  stream:
    bindings:
      sport-out-0:
        group: test
        destination: sport
```
