### ISSUE TITLE
How Bind in an AMQPMocked Application?

### ISSUE THREAD

**Issue by FabianoLothor** [spring-cloud/spring-cloud-stream#1847]
I am using a SpringCloudStream and testing the classes with a Mocked RabbitMQ similar to this project: https://github.com/fridujo/rabbitmq-mock

Unfortunately the RabbitMQ instanced by the `com.github.fridujo.rabbitmq.mock.compatibility.MockConnectionFactoryFactory` class doesn't bind the SpringCloudStream binds.

Some help about this issue?

**Comment by FabianoLothor** [comment]
My `app.yml`

```yml
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        firstOutput:
          destination: foo.update
        secondOutput:
          destination: foo.request
  rabbitmq:
    host: localhost
    port: 5672
```

My `AmqpAppTestConfig.java`

```java
@Configuration
public class AmqpApplicationTestConfiguration {

    @Bean
    public ConnectionFactory connectionFactory() {
        CachingConnectionFactory connectionFactory = new CachingConnectionFactory(MockConnectionFactoryFactory.build().enableConsistentHashPlugin());
        connectionFactory.setPort(5672);

        return  connectionFactory;
    }

}
```

In My `FooTest.java` I have something similar to

@RunWith(SpringRunner.class)
@SpringBootTest
public class FooTest {

    @Autowired
    private AmqpAdmin amqpAdmin;

    @Test
    public void testSolicitarCalculo() throws Exception {
        ...
        amqpAdmin.getQueueProperties("foo.request.queue"); // Returns null, expecting a bind
        ...
    }

}

**Comment by garyrussell** [comment]
You have (possibly) 2 problems.

1. When a binding has no `group`, an anonymous auto-delete queue with a randomized name is created.
2. You need to remove the test support dependency to use the real rabbit binder in tests

```xml
<!-- 		<dependency> -->
<!-- 			<groupId>org.springframework.cloud</groupId> -->
<!-- 			<artifactId>spring-cloud-stream-test-support</artifactId> -->
<!-- 			<scope>test</scope> -->
<!-- 		</dependency> -->
```

This works fine:

```yaml
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: foo.request
          group: queue
  rabbitmq:
    host: localhost
    port: 5672
```

```java
@SpringBootTest
class Rbgh1847ApplicationTests {

	@Test
	void contextLoads(@Autowired RabbitAdmin admin) throws InterruptedException {
		System.out.println(admin.getQueueProperties("foo.request.queue"));
	}

}
```
When there is a group, the queue is named `destination.group`.

Result:

    {QUEUE_CONSUMER_COUNT=1, QUEUE_MESSAGE_COUNT=0, QUEUE_NAME=foo.request.queue}

**Comment by FabianoLothor** [comment]
When I remove my tests don't run anymore.

* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes:

**Comment by garyrussell** [comment]
Removing the test binder will have no impact on what tests exist. So something else is going on; try `--debug`.

If you are using the test binder in some tests (`MessageCollector`) than you will need to exclude the test binder just from those tests that you want to use the mock broker with.

**Comment by FabianoLothor** [comment]
I change my app.yml

```yml
    cloud:
        stream:
            default:
                contentType: application/json
            bindings:
                input:
                    destination: foo.request
                    group: queue
                recomendacaoOutput:
                    destination: recomendacao.atualizar
                calculoOutput:
                    destination: foo.request
```

And add a `System.out.println` in my test code.

```java
        System.out.println(amqpAdmin.getQueueProperties("foo.request.queue"));
        systemService.doRequest(uuid.toString(), fooParameter); // The OUTPUT is sent here
        System.out.println(amqpAdmin.getQueueProperties("foo.request.queue"));
```

The code above returns:

```log
null
[INFO ] 2019-11-20 09:46:24.979 AbstractConnectionFactory                          - Attempting to connect to: localhost:5672
[INFO ] 2019-11-20 09:46:24.980 AbstractConnectionFactory                          - Created new connection: connectionFactory.publisher#219b6250:0/SimpleConnection@52855de5 [delegate=com.github.fridujo.rabbitmq.mock.MockConnection@7c82be11, localPort= 0]
[INFO ] 2019-11-20 09:46:25.000 FooService                                      - Request sent to myService MyRequestObject
null
```

If I add a Listener class like:

```java
@Slf4j
@Service
@EnableBinding(Processor.class)
public class FooService {

    @StreamListener(INPUT)
    public Message foo(MyRequestObject request) {
        return MessageBuilder.withPayload("foo".getBytes()).build();
    }
}
```

My return is

```log
{QUEUE_NAME=foo.request.queue, QUEUE_MESSAGE_COUNT=0, QUEUE_CONSUMER_COUNT=1}
[INFO ] 2019-11-20 09:46:24.979 AbstractConnectionFactory                          - Attempting to connect to: localhost:5672
[INFO ] 2019-11-20 09:46:24.980 AbstractConnectionFactory                          - Created new connection: connectionFactory.publisher#219b6250:0/SimpleConnection@52855de5 [delegate=com.github.fridujo.rabbitmq.mock.MockConnection@7c82be11, localPort= 0]
[INFO ] 2019-11-20 09:46:25.000 FooService                                      - Request sent to myService MyRequestObject
{QUEUE_NAME=foo.request.queue, QUEUE_MESSAGE_COUNT=0, QUEUE_CONSUMER_COUNT=1}
```

So, the first println is ok: `{QUEUE_NAME=foo.request.queue, QUEUE_MESSAGE_COUNT=0, QUEUE_CONSUMER_COUNT=1}`

But the second should be `{QUEUE_NAME=foo.request.queue, QUEUE_MESSAGE_COUNT=1, QUEUE_CONSUMER_COUNT=1}`
