### ISSUE TITLE
Flux Supplier with EmitterProcessor not functioning during explicit binder assignment 

### ISSUE THREAD

**Issue by ncheema** [spring-cloud/spring-cloud-stream#1880]
Explicit `binder` assignment  to  a  `supplier` and  `consumer` binding,  is resulting in `supplier` failing to publish to the assigned binder.  It seems  `emitterProcessor`  is unable to drain the queue due to not having a  registered subscriber. 

Sample Project for debugging: https://github.com/ncheema/spring-cloud-stream-demo

#### Nonfunctioning configuration (has binder assignment): 
```yaml
spring.cloud.stream:
  function.definition: supplier;consumer;
  bindings:
    supplier-out-0:
      destination: topic-out
      binder: kafka1
    consumer-in-0:
      destination: topic-in
      binder: kafka1
  binders:
    kafka1:
      type: kafka
      environment:
        spring:
          cloud:
            stream:
              kafka:
                binder:
                  brokers: localhost:9092
```

#### Functioning Configuration:
```yaml
spring.cloud.stream:
  function.definition: supplier;consumer;
  bindings:
    supplier-out-0:
      destination: topic-out
    consumer-in-0:
      destination: topic-in
```

Code Snippet from above sample project:
``` Java
@SpringBootApplication
public class Application {
    private EmitterProcessor<Message<String>> processor =  EmitterProcessor.create();

    @Bean
    public Supplier<Flux<Message<String>>> supplier() {
        return () -> processor;
    }

    @Bean
    public Consumer<String> consumer() {
        return msg -> processor.onNext(MessageBuilder.withPayload(msg).build());
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```
