### ISSUE TITLE
implemented new binder for mqtt

### ISSUE THREAD

**Issue by sheunglaili** [spring-cloud/spring-cloud-stream#1908]
Not sure where to put.
Just to let you guys know that I have implemented a MQTT binder. free feel to use it. links are as below: 

https://github.com/sheunglaili/spring-cloud-stream-binder-mqtt

**Comment by olegz** [comment]
Noted! Thank you

**Comment by sheunglaili** [comment]
not sure why when it's included in the classpath. the other binder won't configure 🤔

**Comment by olegz** [comment]
You have to be more specific. May be share your configuration?

**Comment by sheunglaili** [comment]
```
    spring:
      profiles: development
      application:
        name: mqtt-kafka
      cloud:
        stream:
          defaultBinder: kafka
          bindings:
            mqtt-input:
              destination: mqtt-input
              binder: custom-mqtt
              content-type: application/json
            mqtt-output:
              destination: mqtt-output
              binder: custom-mqtt
              content-type: application/json
            kafka-input:
              destination: kafka-input
              binder: custom-kafka
              content-type: application/json
            kafka-output:
              destination: kafka-output
              binder: custom-kafka
              content-type: application/json
          binders:
            custom-mqtt:
              type: mqtt
              defaultCandidate: false
            custom-kafka:
              type: kafka
          kafka:
            binder:
              brokers: kafka-bootstrap-address
          mqtt:
            binder:
              url: tcp://hivemq-mqtt.default:1883
```

this is the application.yml I am using.

When I include only the kafka binder implementaion. it will start configure the kafka-binder

but when I also included my mqtt implementation. it will only configure the mqtt implementation , even though I specified the binder as kafka.

below is the response from the actuator bindings endpoint 

```
[
    {
        "bindingName": "kafka-input",
        "name": "kafka-input",
        "group": null,
        "pausable": false,
        "state": "running",
        "input": true,
        "extendedInfo": {
            "bindingDestination": "com.above.mqttkafka.config.binder.MqttProvisioningProvider$MqttTopicDestination@6aa1da60",
            "ExtendedConsumerProperties": {
                "autoStartup": true,
                "concurrency": 1,
                "instanceCount": 1,
                "maxAttempts": 3,
                "backOffInitialInterval": 1000,
                "backOffMaxInterval": 10000,
                "backOffMultiplier": 2.0,
                "defaultRetryable": true,
                "extension": {
                    "clientId": "stream.client.id.source",
                    "topics": [
                        "stream.mqtt"
                    ],
                    "qos": [
                        0
                    ],
                    "binary": false,
                    "charset": "UTF-8"
                }
            }
        }
    },
    {
        "bindingName": "kafka-output",
        "name": "kafka-output",
        "group": null,
        "pausable": false,
        "state": "running",
        "input": false,
        "extendedInfo": {
            "bindingDestination": "kafka-output",
            "ExtendedProducerProperties": {
                "autoStartup": true,
                "partitionCount": 1,
                "extension": {
                    "clientId": "stream.client.id",
                    "topic": "stream.mqtt",
                    "qos": 1,
                    "retained": false,
                    "charset": "UTF-8",
                    "async": false
                },
                "validPartitionKeyProperty": true,
                "validPartitionSelectorProperty": true
            }
        }
    }
]
```

**Comment by olegz** [comment]
`defaultBinder: kafka` is the issue. It sees two binders and defaults to kafka. Remove it.
Also you can remove `content-type: application/json` as it is default

**Comment by sheunglaili** [comment]
tried your suggestion but still the same. 

It seems that the case is when I provided my own binder implementation. The KafkaBinderConfiguration will be skipped as it possesses the annotation @ConditionalOnMissingBean(Binder.class)

if that's the case , how should I fix it ?

**Comment by olegz** [comment]
No, this is not the case since multiple binders is one fo the core features of the framework - https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.2.RELEASE/reference/html/spring-cloud-stream.html#multiple-binders.

**Comment by olegz** [comment]
You also have `defaultCandidate: false` And your 
```
kafka:
            binder:
              brokers: kafka-bootstrap-address
          mqtt:
            binder:
              url: tcp://hivemq-mqtt.default:1883
```
as they should be part of the `environment:`

**Comment by sheunglaili** [comment]
should my mqtt implementation worried about how to read that enviroment ? cause It's seems still not working 

here is the yaml:

```
    spring:
      profiles: development
      application:
        name: mqtt-kafka
      cloud:
        stream:
          bindings:
            mqtt-input:
              destination: mqtt-input
              binder: custom-mqtt
            mqtt-output:
              destination: mqtt-output
              binder: custom-mqtt
            kafka-input:
              destination: kafka-input
              binder: custom-kafka
            kafka-output:
              destination: kafka-output
              binder: custom-kafka
          binders:
            custom-mqtt:
              type: mqtt
              environment:
                spring:
                  cloud:
                    stream:
                     mqtt:
                      binder:
                        url: tcp://hivemq-mqtt.default:1883

            custom-kafka:
              type: kafka
              environment:
               spring:
                 cloud:
                   stream:
                    kafka:
                      binder:
                        brokers: kafka-bootstrap-address

```

**Comment by sheunglaili** [comment]
moreover, I am currently using those implementations as plain spring configuration. Will it matter ? should I put those configurations and properties into its own jar and import it as a dependency

**Comment by olegz** [comment]
Yes, the environment is part of the general configuration of your broker, and is out of scope of s-c-stream. You can look at Rabbit or Kafka binder and see that environment is taken by the underlying components from spring-kafka, spring-amqp.

**Comment by sheunglaili** [comment]
> moreover, I am currently using those implementations as plain spring configuration. Will it matter ? should I put those configurations and properties into its own jar and import it as a dependency

how about this one? sorry for too many questions.

**Comment by sheunglaili** [comment]
tried using @import to force import the kafka binder , resulting in 
```
 Caused by: java.lang.IllegalStateException: Multiple binders are available, however neither default nor per-destination binder name is provided. Available binders are [kafkaMessag
eChannelBinder, mqttBinder]
```

**Comment by olegz** [comment]
I am not sure what you're doing but I would suggest going through the section i mentioned earlier.
Here is the example of simplest multi-binder configuration:
```
spring:
  cloud:
    function:
      definition: uppercase
    stream:
      bindings:
        uppercase-in-0:
           binder: rabbit_binder
        uppercase-out-0:
           binder: kafka_binder
      binders:
        rabbit_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
        kafka_binder:
          type: kafka
```

The above implies that you have Kafka and Rabbit binder on classpath. Input is bound to Rabbit and output to Kafka

**Comment by sheunglaili** [comment]
turns out that I have to comment out the @Configuration on the MqttBinderConfiguration

and add in the spring.binders

```
mqtt:\
com.sheunglaili.mqttkafka.config.binder.config.MqttBinderConfiguration

kafka:\
org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfiguration
```

and my application.yml are as follow:

```
    spring:
      profiles: development
      application:
        name: mqtt-kafka
      cloud:
        stream:
          bindings:
            mqtt-input:
              destination: mqtt-input
              binder: mqtt
            mqtt-output:
              destination: mqtt-output
              binder: mqtt
            kafka-input:
              destination: kafka-input
              binder: kafka
            kafka-output:
              destination: kafka-output
              binder: kafka
          mqtt:
            binder:
              url: tcp://hivemq-mqtt.default:1883
          kafka:
            binder:
              brokers: kafka-bootstrap-address
```
