### ISSUE TITLE
Default rabbit bind properties dont work

### ISSUE THREAD

**Issue by sanmibuh** [spring-cloud/spring-cloud-stream#1933]
**Describe the issue**
I'm trying to put some default binder properties, but don't create the queues on the rabbit according to the configuration

**To Reproduce**
spring.cloud.stream.rabbit.default.consumer.autoBindDlq=true
spring.cloud.stream.rabbit.default.consumer.republishToDlq=true

**Version of the framework** 
Hoxton.SR3

**Additional context**
If I put those configurations on every consumer config work as expected:
spring.cloud.stream.rabbit.bindings.referenceInput.consumer.autoBindDlq=true
spring.cloud.stream.rabbit.bindings.referenceInput.consumer.republishToDlq=true

NOTE: If I put an incorrect values like:
spring.cloud.stream.rabbit.default.consumer.autoBindDlq=notValidBoolean

It fails on startup, so the configuration is parsed correctly, but is ignored

**Comment by olegz** [comment]
I just tried it and all works as expected. Here is the minimum example that shows that all is working
```
@SpringBootApplication
public class SampleFunctoinAppApplication {

	public static void main(String[] args) throws Exception {
		SpringApplication
				.run(SampleFunctoinAppApplication.class, "--spring.cloud.function.definition=uppercase",
						"--spring.cloud.stream.rabbit.default.consumer.autoBindDlq=true",
						"--spring.cloud.stream.rabbit.default.consumer.republishToDlq=true");
	}

	@Bean
	public Function<String, String> uppercase() {
		return v -> v;
	}
}
```

Perhaps you can share an example that shows the oposite

**Comment by sanmibuh** [comment]
Here is my working yml repeating attributes
```
spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                prt: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        referenceInput:
          binder: rabbit
          destination: styling.catalog.product_variants
          group: ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue
          contentType: application/json
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 10000
            backOffMaxInterval: 1000000
            backOffMultiplier: 2
        referenceLocationLogInput:
          binder: rabbit
          destination: ops.warehouse.stock.exchange
          group: reference.log.queue
          contentType: application/json
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 10000
            backOffMaxInterval: 1000000
            backOffMultiplier: 2
        referenceZoneLogInput:
          binder: rabbit
          destination: ops.warehouse.stock.exchange
          group: zone.log.queue
          contentType: application/json
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 10000
            backOffMaxInterval: 1000000
            backOffMultiplier: 2
        orderLogInput:
          binder: rabbit
          destination: ops.warehouse.order.exchange
          group: order.log.queue
          contentType: application/json
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 10000
            backOffMaxInterval: 1000000
            backOffMultiplier: 2
        orderReferenceLogInput:
          binder: rabbit
          destination: ops.warehouse.order.exchange
          group: order.reference.log.queue
          contentType: application/json
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 10000
            backOffMaxInterval: 1000000
            backOffMultiplier: 2
        referenceLocationOutput:
          binder: rabbit
          destination: ops.warehouse.stock.exchange
          contentType: application/json
        referenceZoneOutput:
          binder: rabbit
          destination: ops.warehouse.stock.exchange
          contentType: application/json
        orderReferenceOutput:
          binder: rabbit
          destination: ops.warehouse.order.exchange
          contentType: application/json
        orderOutput:
          binder: rabbit
          destination: ops.warehouse.order.exchange
          contentType: application/json
      rabbit:
        bindings:
          referenceInput:
            consumer:
              queueNameGroupOnly: true
              autoBindDlq: true
              republishToDlq: true
              bindingRoutingKey: styling.catalog.pim.product_variant.product_variant_created
              declareExchange: true
              prefetch: 5
              maxConcurrency: 2
          referenceLocationLogInput:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              bindingRoutingKey: ops.warehouse.stock
              declareExchange: false
              prefetch: 5
              maxConcurrency: 2
          referenceZoneLogInput:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              bindingRoutingKey: ops.warehouse.zone
              declareExchange: false
              prefetch: 5
              maxConcurrency: 2
          orderReferenceLogInput:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              bindingRoutingKey: ops.warehouse.orderreference.#
              declareExchange: false
              prefetch: 5
              maxConcurrency: 2
          orderLogInput:
            consumer:
              autoBindDlq: true
              republishToDlq: true
              bindingRoutingKey: ops.warehouse.order.#
              declareExchange: false
              prefetch: 5
              maxConcurrency: 2
          referenceLocationOutput:
            producer:
              routingKeyExpression: '''ops.warehouse.stock'''
              transacted: true
          referenceZoneOutput:
            producer:
              routingKeyExpression: '''ops.warehouse.zone'''
              transacted: true
          orderReferenceOutput:
            producer:
              routingKeyExpression: "'ops.warehouse.orderreference.'.concat(payload['action'].name().toLowerCase())"
              transacted: true
          orderOutput:
            producer:
              routingKeyExpression: "'ops.warehouse.order.'.concat(payload['action'].toLowerCase())"
              transacted: true
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  mvc:
    log-resolved-exception: false
```

In the rabbit it makes those queues:
<img width="1360" alt="queues good" src="https://user-images.githubusercontent.com/15193703/77418813-ba50d300-6dc7-11ea-9c6b-61bc85614686.png">

A queue config
<img width="1404" alt="queue good" src="https://user-images.githubusercontent.com/15193703/77418841-c50b6800-6dc7-11ea-9830-4dc05b40e73f.png">


And this is not working yml
```
spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                prt: 5672
                username: guest
                password: guest
                virtual-host: /
      default:
        binder: rabbit
        contentType: application/json
        consumer:
          concurrency: 5
          maxAttempts: 3
          backOffInitialInterval: 10000
          backOffMaxInterval: 1000000
          backOffMultiplier: 2
      bindings:
        referenceInput:
          destination: styling.catalog.product_variants
          group: ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue
        referenceLocationLogInput:
          destination: ops.warehouse.stock.exchange
          group: reference.log.queue
        referenceZoneLogInput:
          destination: ops.warehouse.stock.exchange
          group: zone.log.queue
        orderLogInput:
          destination: ops.warehouse.order.exchange
          group: order.log.queue
        orderReferenceLogInput:
          destination: ops.warehouse.order.exchange
          group: order.reference.log.queue
        referenceLocationOutput:
          destination: ops.warehouse.stock.exchange
        referenceZoneOutput:
          destination: ops.warehouse.stock.exchange
        orderReferenceOutput:
          destination: ops.warehouse.order.exchange
        orderOutput:
          destination: ops.warehouse.order.exchange
      rabbit:
        default:
          consumer:
            autoBindDlq: true
            republishToDlq: true
            declareExchange: false
            prefetch: 5
            maxConcurrency: 2
          producer:
            transacted: true
        bindings:
          referenceInput:
            consumer:
              queueNameGroupOnly: true
              bindingRoutingKey: styling.catalog.pim.product_variant.product_variant_created
              #Only on local
              declareExchange: true
          referenceLocationLogInput:
            consumer:
              bindingRoutingKey: ops.warehouse.stock
          referenceZoneLogInput:
            consumer:
              bindingRoutingKey: ops.warehouse.zone
          orderReferenceLogInput:
            consumer:
              bindingRoutingKey: ops.warehouse.orderreference.#
          orderLogInput:
            consumer:
              bindingRoutingKey: ops.warehouse.order.#
          referenceLocationOutput:
            producer:
              routingKeyExpression: '''ops.warehouse.stock'''
          referenceZoneOutput:
            producer:
              routingKeyExpression: '''ops.warehouse.zone'''
          orderReferenceOutput:
            producer:
              routingKeyExpression: "'ops.warehouse.orderreference.'.concat(payload['action'].name().toLowerCase())"
          orderOutput:
            producer:
              routingKeyExpression: "'ops.warehouse.order.'.concat(payload['action'].toLowerCase())"
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  mvc:
    log-resolved-exception: false
```

In the rabbit makes those queues:
<img width="1227" alt="queues-bad" src="https://user-images.githubusercontent.com/15193703/77418863-cccb0c80-6dc7-11ea-93b1-94fba2f72d53.png">

A queue config
<img width="1316" alt="queue bad" src="https://user-images.githubusercontent.com/15193703/77418875-d18fc080-6dc7-11ea-9861-027c5d4abd02.png">

**Comment by olegz** [comment]
I am sorry, but there is no way any one can review that much configuration. Can you please slim it down to a bare minimum that reproduces the issue?

**Comment by sanmibuh** [comment]
For example, with this configuration:
```
spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                prt: 5672
                username: guest
                password: guest
                virtual-host: /
      default:
        binder: rabbit
        contentType: application/json
        consumer:
          concurrency: 5
          maxAttempts: 3
          backOffInitialInterval: 10000
          backOffMaxInterval: 1000000
          backOffMultiplier: 2
      bindings:
        referenceInput:
          destination: styling.catalog.product_variants
          group: ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue
      rabbit:
        default:
          consumer:
            queueNameGroupOnly: true
            autoBindDlq: true
            republishToDlq: true
            declareExchange: false
            prefetch: 5
            maxConcurrency: 2
```
it creates a 1 queue with a name:
styling.catalog.product_variants.ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue 

So it is ignoring queueNameGroupOnly and autoBindDlq

With this config:
``` 
spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                prt: 5672
                username: guest
                password: guest
                virtual-host: / 
      bindings:
        referenceInput:
          binder: rabbit
          contentType: application/json
          destination: styling.catalog.product_variants
          group: ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue
          consumer:
            concurrency: 5
            maxAttempts: 3
            backOffInitialInterval: 10000
            backOffMaxInterval: 1000000
            backOffMultiplier: 2
      rabbit:
        bindings:
          referenceInput:
            consumer:
              bindingRoutingKey: styling.catalog.pim.product_variant.product_variant_created
              #Only on local
              declareExchange: true 
              queueNameGroupOnly: true
              autoBindDlq: true
              republishToDlq: true
              prefetch: 5
              maxConcurrency: 2
```

It creates both queue and dlq with the correct name
ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue
ops.styling.catalog.product_variants.exchange.warehouse.stock.reference.queue.dlq

**Comment by olegz** [comment]
This still seems like a lot of irrelevant configuration. Consider revising it even more so it's easy to reproduce, diagnose and fix.

**Comment by sanmibuh** [comment]
There is the minimum config to see the issue:
* The connection to the rabbit
* 1 binding

If I put less config, the queues are not created.

**Comment by olegz** [comment]
When you say less, what do you mean by it? What exactly should be removed from the above configuration for problem to go away? For example, I can't see how `concurrency`, `maxAttempts` etc.,  have anything to do with the problem. 

Anyway, I will look eventually, but was hoping that you can help by making diagnostics simpler

**Comment by sanmibuh** [comment]
All of the properties are part of the problem. None of the properties that I put on the 
spring.cloud.stream.rabbit.default.* 
are used (but they are loaded because If it put a not valid value, it fails on startup)

Thanks!

**Comment by sanmibuh** [comment]
Hello!

Finally did you found the problem?

Thanks

**Comment by briceamk** [comment]
I have the same problem in my project. this is my config

```yaml
spring:
    cloud:
      stream:
        binders:
          gmoneyRabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
        bindings:
          uaaChannel:
            contentType: application/json
            destination: gmoney.uaa
            binder: gmoneyRabbit
          partnerChannel:
            destination: gmoney.partner
            group: gmoney.partnerQueue
            binder: gmoneyRabbit
          accountChannel:
            destination: gmoney.account
            group: gmoney.accountQueue
            binder: gmoneyRabbit
          rabbit:
            bindings:
              uaaChannel:
                producer:
                  routingKeyExpression: headers['uaaRouteTo']
              partnerChannel:
                consumer:
                  bindingRoutingKey: createPartnerResponse
              accountChannel:
                consumer:
                  bindingRoutingKey: createAccountResponse
```
error;
Failed to bind properties under 'spring.cloud.stream.rabbit.bindings.uaachannel.producer.routing-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.rabbit.bindings.uaachannel.producer.routingkeyexpression
    Value: headers[uaaRouteTo]
    Origin: "spring.cloud.stream.rabbit.bindings.uaaChannel.producer.routingKeyExpression" from property source "bootstrapProperties-file:///home/ubuntu/Projets/Spring/gmoney-ms-configuration/uaa/application-dev.yml"
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

Action:

Update your application's configuration

I had try to change  routingKeyExpression: headers['uaaRouteTo'] to routingKeyExpression: '''headers['uaaRouteTo']''' or routingKeyExpression: "'headers[uaaRouteTo]'" or routingKeyExpression: headers.uaaRouteTo

still get same error
