### ISSUE TITLE
Spring Cloud Stream filtered with IntegrationFlow waits indefinitely for a response when selector is false

### ISSUE THREAD

**Issue by jdmcmahan** [spring-cloud/spring-cloud-stream#1948]
I'm having trouble using IntegrationFlow along with Spring Cloud Stream to perform some complex filtering on messages.

Suppose my service is only interested in messages with an `eventType` header of `foo`:

```java
@Configuration
public class FooListener {

    @Bean
    public IntegrationFlow fooFlow() {
        return IntegrationFlows.from(FooMessageFunction.class, gateway -> gateway.beanName("foo"))
                .filter(Message.class, message -> {
                    Object value = message.getHeaders().get("eventType");
                    if (value == null) {
                        return false;
                    } else {
                        value = value instanceof byte[] ? new String((byte[]) value) : value.toString();
                        return value.equals("foo");
                    }
                })
                .transform(Foo.class, this::handleFoo)
                .get();
    }

    protected Message<FooEvent> handleFoo(Foo foo) {
        // TODO: handle foo

        FooEvent event = new FooEvent(...);

        return MessageBuilder.withPayload(event)
                .setHeader("eventType", "fooEvent")
                .build();
    }

    interface FooMessageFunction extends Function<Message<?>, Message<FooEvent>> {}
}
```

```yaml
spring:
  cloud:
    function:
      definition: foo
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}
      bindings:
        foo-in-0:
          binder: kafka
          destination: test
          content-type: application/json
        foo-out-0:
          binder: kafka
          destination: test
          content-type: application/json
```
This will work as expected so long as the filter returns `true`. When the filter is `false`, it seems the stream still expects some kind of response which never comes. This causes the application to hang on `GenericMessagingTemplate` line 240.

**To Reproduce**
1. Clone https://github.com/jdmcmahan/scst-filter-test.git
2. Spin up a Kafka instance
3. Run scst-filter-test project
4. Verify "foo" message is working
> kafkacat -P -b <broker> -t test -p 0 -H eventType=foo
5. Try "bar" message
> kafkacat -P -b <broker> -t test -p 0 -H eventType=bar
6. Try "foo" message again (this will not be received)
> kafkacat -P -b <broker> -t test -p 0 -H eventType=foo

**Version of the framework**
3.0.4.RELEASE (as defined by Hoxton.SR4)

**Expected behavior**
Application should gracefully handle uninteresting messages and continue to function
