### ISSUE TITLE
Add possibility to configure rabbitmq specific to stream binder

### ISSUE THREAD

**Issue by armsargis** [spring-cloud/spring-cloud-stream#1963]
I have project with already configured amqp but for cloud bus want to use separate virtual host with its own username/password

I think its nice to have possibility to configure brokers using separate config path to be able isolate modules.

If you think idea is nice I can prepare PR.

**Comment by olegz** [comment]
Yes there is a solution and 

There is `spring.rabbitmq.*` properties, so for the above example you could do something like  
```
spring.rabbitmq.host=
spring.rabbitmq.username=
spring.rabbitmq.password=
```

**Comment by armsargis** [comment]
but I want to have 2 configuration one for cloud-bus/stream another one for application messaging subsystem and configuration like this:

```yaml
spring:
  cloud:
    bus:
      rabbitmq:
        host: localhost
        username: cloud
        password: bus
        virtual-host: /bus
```

does not exists it was a suggestion to add.
