### ISSUE TITLE
No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

### ISSUE THREAD

**Issue by sufiannazim** [spring-cloud/spring-cloud-stream#1979]
Application fails to startup if it has multiple binder configurations and routingKeyExpression property for producer.

**Error message:
**Property: spring.cloud.stream.rabbit.bindings.test.producer.routing-key-expression
    Value: headers['event-type']
    Origin: class path resource [application-local.yml]:55:39
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]**** 

Issue can be recreated only in 3.0.4 and 3.0.5 version of spring cloud stream.

**Comment by olegz** [comment]
can you please provide steps to reproduce?  Perhaps sampel project?

**Comment by sufiannazim** [comment]
Sample project can be cloned from the following repo:

https://github.com/sufiannazim/spring-cloud-stream-sample-for-issue-1979.git

Sample project has three app yaml files to demo different configuration scenarios.

1) Single binder with routing key expression property for producer  - works fine
2) Multi binder **without** routing key expression property for producer - works fine
2) Multi binder **with** routing key expression property for producer - broken

**Comment by sufiannazim** [comment]
@olegz Any update regarding this defect?

**Comment by briceamk** [comment]
I have the same problem in my project. this is my config
spring:
    cloud:
      stream:
        binders:
          gmoneyRabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
        bindings:
          uaaChannel:
            contentType: application/json
            destination: gmoney.uaa
            binder: gmoneyRabbit
          partnerChannel:
            destination: gmoney.partner
            group: gmoney.partnerQueue
            binder: gmoneyRabbit
          accountChannel:
            destination: gmoney.account
            group: gmoney.accountQueue
            binder: gmoneyRabbit
          rabbit:
            bindings:
              uaaChannel:
                producer:
                  routingKeyExpression: headers['uaaRouteTo']
              partnerChannel:
                consumer:
                  bindingRoutingKey: createPartnerResponse
              accountChannel:
                consumer:
                  bindingRoutingKey: createAccountResponse
error;
Failed to bind properties under 'spring.cloud.stream.rabbit.bindings.uaachannel.producer.routing-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.rabbit.bindings.uaachannel.producer.routingkeyexpression
    Value: headers[uaaRouteTo]
    Origin: "spring.cloud.stream.rabbit.bindings.uaaChannel.producer.routingKeyExpression" from property source "bootstrapProperties-file:///home/ubuntu/Projets/Spring/gmoney-ms-configuration/uaa/application-dev.yml"
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

Action:

Update your application's configuration

I had try to change  routingKeyExpression: headers['uaaRouteTo'] to routingKeyExpression: '''headers['uaaRouteTo']''' or routingKeyExpression: "'headers[uaaRouteTo]'" or routingKeyExpression: headers.uaaRouteTo

still get same error

**Comment by jeiroa** [comment]
I have the same error too. This is my configuration that works on Spring Boot v2.2.7 and Spring Cloud version Hoxton.SR3 (Spring Cloud Stream v3.0.3) but not on 3.0.4 or 3.0.5:
```
#
# RabbitMQ Transport layer
#
spring.cloud.stream.binders.rabbit-transport-layer.environment.spring.rabbitmq.addresses=somehost:5672
spring.cloud.stream.binders.rabbit-transport-layer.environment.spring.rabbitmq.virtual-host=test
spring.cloud.stream.binders.rabbit-transport-layer.environment.spring.rabbitmq.username=user
spring.cloud.stream.binders.rabbit-transport-layer.environment.spring.rabbitmq.password=pass

spring.cloud.stream.binders.rabbit-transport-layer.type=rabbit
spring.cloud.stream.binders.rabbit-transport-layer.environment.spring.cloud.stream.rabbit.bindings.stream-output.producer.exchange-type=topic
spring.cloud.stream.binders.rabbit-transport-layer.environment.spring.cloud.stream.rabbit.bindings.stream-output.producer.routing-key-expression=headers['routingKey']

spring.cloud.stream.bindings.stream-output.destination=price-merger-out-price-mixer-in
spring.cloud.stream.bindings.stream-output.group=local
spring.cloud.stream.bindings.stream-output.binder=rabbit-transport-layer

spring.cloud.stream.bindings.source-price-input.destination=price-sync-out-price-merger-in
spring.cloud.stream.bindings.source-price-input.group=local
spring.cloud.stream.bindings.source-price-input.binder=rabbit-transport-layer
```

The error can be replicated in [spring-cloud-stream-samples/partitioning-samples/rabbit-partitioning](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/partitioning-samples/rabbit-partitioning) project adding the following lines to partitioning-producer-sample-rabbit/src/main/resources/application.yml file:
```
spring:
  cloud:
    stream:
      binders:
        rabbit1:
          environment:
            spring:
              rabbitmq:
                addresses: somehost:5672
                virtual-host: test
                username: user
                password: pass
              cloud:
                stream:
                  rabbit:
                    bindings:
                      generate-out-0:
                        producer:
                          routing-key-expression: headers['routingKey']
```

**Comment by tangdelong** [comment]
I have the same error to . 
 Horsham SR3 upgrade to Horsham SR5

configuration:
```
spring:
  application:
    name: spring-cloud-rabbit-service-1
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        myOutput:
          destination: my-messages
          binder: local_rabbit
      rabbit:
          bindings:
            myOutput:
              producer:
                exchangeType: direct 
                routingKeyExpression:  headers.key
                queueNameGroupOnly: tru
```e 

project start exception as follows:
```
Failed to bind properties under 'spring.cloud.stream.rabbit.bindings.myoutput.producer.routing-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.rabbit.bindings.myoutput.producer.routingkeyexpression
    Value: headers.key
    Origin: class path resource [application.yml]:64:37
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]
```
