### ISSUE TITLE
Kafka Binder multiple cluster configuration

### ISSUE THREAD

**Issue by saipraveenjda** [spring-cloud/spring-cloud-stream#1994]
I am using Spring Cloud Stream Kafka binder to consume messages from Kafka. I am able to make my sample work with a single Kafka Binder as below

```
spring:
      cloud:
        stream:
          kafka:
            binder:
              consumer-properties: {enable.auto.commit: true}
              auto-create-topics: false
              brokers: <broker url>
          bindings:
            consumer:
              destination: some-topic
              group: testconsumergroup
              consumer:
                concurrency: 1
                valueSerde: JsonSerde
            producer:
              destination: some-other-topic
              producer:
                valueSerde: JsonSerde
```

Note that both the bindings are to the same Kafka Broker here. However, I have a situation where I need to publish to a topic in some Kafka Cluster and also consume from another topic in a different Kafka Cluster. How should I change my configuration to be able to bind to different Kafka Clusters?

I tried something like this for multiple cluster binding

```
    spring:
      cloud:
        stream:
          binders:
            kafka2:
              type: kafka
              environment:
                spring.cloud.stream.kafka.binder.brokers: <cluster2-brokers>
            kafka1:
              type: kafka
              environment:
                spring.cloud.stream.kafka.binder.brokers: <cluster1-brokers>
          bindings:
            consumer:
              destination: <some-topic>
              binder: kafka1
              group: testconsumergroup
              content-type: application/json
              nativeEncoding: true
              consumer:
                concurrency: 1
                valueSerde: JsonSerde
            producer:
              destination: some-topic
              binder: kafka2
              contentType: application/json
              nativeEncoding: true
              producer:
                valueSerde: JsonSerde

```
**I am using the dependency 'org.springframework.cloud:spring-cloud-starter-stream-kafka:3.0.1.RELEASE' and Spring Boot 2.2.6**

The Message Streams and EventHubBinding is as follows

 ```
public interface MessageStreams {
      String PRODUCER = "producer";
      String CONSUMER = "consumer;
    
      @Output(PRODUCER)
      MessageChannel producerChannel();
    
      @Input(CONSUMER)
      SubscribableChannel consumerChannel()
    }
    
    @EnableBinding(MessageStreams.class)
    public class EventHubStreamsConfiguration {
    }

```
My Producer class looks like below

```
@Component
    @Slf4j
    public class EventPublisher {
      private final MessageStreams messageStreams;
    
      public EventPublisher(MessageStreams messageStreams) {
        this.messageStreams = messageStreams;
      }
    
      public boolean publish(CustomMessage event) {
        MessageChannel messageChannel = getChannel();
        MessageBuilder messageBuilder = MessageBuilder.withPayload(event);
        boolean messageSent = messageChannel.send(messageBuilder.build());
        return messageSent;
      }
    
      protected MessageChannel getChannel() {
        return messageStreams.producerChannel();
      }
    }

```
And Consumer class looks like below

```
@Component
    @Slf4j
    public class EventHandler {
      private final MessageStreams messageStreams;
    
      public EventHandler(MessageStreams messageStreams) {
        this.messageStreams = messageStreams;
      }
    
      @StreamListener(MessageStreams.CONSUMER)
      public void handleEvent(Message<CustomMessage> message) throws Exception 
      {
        // process the event
      }
    
      @Override
      @ServiceActivator(inputChannel = "some-topic.testconsumergroup.errors")
      protected void handleError(ErrorMessage errorMessage) throws Exception {
        // handle error;
      }
    }

```
I am getting the below error while trying to publish and consume the messages from my test.

`    Dispatcher has no subscribers for channel 'application.producer'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[104], headers={contentType=application/json, timestamp=1593517340422}]
`

Am i missing anything? For a single cluster, i am able to publish and consume messages. The issue is only happening with multiple cluster bindings
