### ISSUE TITLE
Producer (fn) stops after theres an error [Kafka binder]

### ISSUE THREAD

**Issue by juliuskrah** [spring-cloud/spring-cloud-stream#2000]
I have setup a stream producer using `spring-cloud-function`, which works fine until there's an exception then it stops producing.

**Steps to reproduce the behavior:**

```java
class Producer {
    public static EmitterProcessor<String> produce = EmitterProcessor.create();
}

@Configuration
class BeanConfig {
    @Bean
    Supplier<Flux<String>> producer() {
        return () -> Producer.produce;
    }
}

@Component
class Listener {
    @EventListener
    void onSomeEvent(SomeEvent<String> event) {
        var dto = event.getEvent();
	Producer.produce.onNext(dto);
    }
}
```

```yaml
spring:
  cloud:
    function:
      definition: producer
    stream:
      kafka:
        binder:
          brokers: localhost
      bindings:
        producer-out-0:
          destination: some-topic
```

**Version of the framework**

- Spring-Boot: 2.3.0.RELEASE
- Spring-Cloud: Hoxton.SR5 (`spring-cloud-stream-binder-kafka`)

**Expected behavior**

The application should keep producing after an exception is encountered. I added an error handler but it doesn't seem to fix it.

```java
 @Bean
 Supplier<Flux<String>> producer() {
     return () -> Producer.produce.onErrorResume(e -> Mono.empty());
 }
```
