### ISSUE TITLE
kafka maxAttempts not working and cannot manually send ack in kafka consumer when there is an exception

### ISSUE THREAD

**Issue by leighyu1983** [spring-cloud/spring-cloud-stream#2002]
Hello

**Describe the issue**
Two issues:
1. Kafka maxAttempts=1 not working.
2. When throwing exception in @StreamListener in Kafka, cannot manually send ack even if the setting is manual ack in config file.

The goal is when code throws business exception in StreamListener, GlobalChannelInterceptor provided by SpringCloud stream could log the business exception and send ack to kafka broker by code manually(please refer to the code below). Thus the record won't be consumed again. I don't want to use DLQ in this scenario. 

However, the situation when testing kafka is that it retried many times even if the maxAttempts is set to 1. Besides that, sending ack from GlobalChannelInterceptor doesn't work. But, when testing rabbitmq in this way, it works well.

**To Reproduce**

kafka version:  Latest
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.3.0.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
            <version>3.0.6.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
            <version>3.0.6.RELEASE</version>
        </dependency>
```
settings:
```yaml
spring:
  application:
    name: have-fun
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          consumer-properties:
            max:
              poll:
                interval:
                  ms: 600000
            session:
              timeout:
                ms: 6000
            heartbeat:
              interval:
                ms: 2000
        bindings:
          consumer-K1:
            consumer:
              autoCommitOffset: false
      bindings:
        consumer-K1:
          destination: my.k1
          binder: my-kafka-1
          group: g2
          consumer:
            autoCommitOnError: true
            max-attempts: 1
        producer-K1:
          destination: my.k1
          binder: my-kafka-1

      binders:
        my-kafka-1:
          type: kafka
          environment:
            spring:
              kafka:
                host: localhost
                port: 9092
```
```Java
@Component
@GlobalChannelInterceptor
public class MyInterceptor implements ChannelInterceptor {

    @Override
    public void afterSendCompletion(Message<?> message, MessageChannel mc, boolean bln, Exception exception) {
        if(getRequestType(message) == RequestType.CONSUME) {
            sendResponseAck(message);
	}
    }


    private void sendResponseAck(Message<?> message) throws Exception {
        Acknowledgment acknowledgment = null;
	if(message instanceof ErrorMessage) {
          acknowledgment = (Acknowledgment) ((ErrorMessage) message).getOriginalMessage().getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT);
	} else {
          acknowledgment = message.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class);
	}

	acknowledgment.acknowledge(); // not working
    }
	}

    private RequestType getRequestType(Message<?> message) {
        if(message.getHeaders().containsKey(KafkaHeaders.OFFSET) || message.getHeaders().containsKey(KafkaHeaders.RAW_DATA)) {
            return RequestType.CONSUME;
        } else {
            return RequestType.PRODUCE;
        }
    }

    private enum RequestType {
        PRODUCE, CONSUME
    }
}
```

Listener
```java
@EnableBinding({MyKafkaConsumerK1Binding.class})
public class MqListener {
    @StreamListener(MyKafkaConsumerK1Binding.CONSUMER_K1)
    public void recieveK1(Message<School> message) throws Exception{
        throw new Exception("testing business exception");
   }
}


public interface MyKafkaConsumerK1Binding {
	String CONSUMER_K1 = "consumer-K1";

	@Input(CONSUMER_K1)
	SubscribableChannel inputK1();
}
```
**Version of the framework**
Please refer to pom above.

**Additional context**

**Comment by garyrussell** [comment]
"Not working" is not quite correct.

What is happening is that, by default, the listener container now has a `SeekToCurrentErrorHandler` which effectively repositions the offset (after the acknowledgment has been processed) and re-sends the failed record (up to 10 times).

You can use a `ListenerContainerCustomizer` `@Bean` to reconfigure the container by replacing the error handler with a `LoggingErrorHandler` (which was the previous default), or a custom `ErrorHandler` if you don't want to log the exception as an error.

**Comment by leighyu1983** [comment]
> "Not working" is not quite correct.
> 
> What is happening is that, by default, the listener container now has a `SeekToCurrentErrorHandler` which effectively repositions the offset (after the acknowledgment has been processed) and re-sends the failed record (up to 10 times).
> 
> You can use a `ListenerContainerCustomizer` `@Bean` to reconfigure the container by replacing the error handler with a `LoggingErrorHandler` (which was the previous default), or a custom `ErrorHandler` if you don't want to log the exception as an error.

Thank you for your reply, Is there any samples that I can refer?

**Comment by garyrussell** [comment]
See [this answer on Stack Overflow](https://stackoverflow.com/questions/60958078/how-to-set-concurrency-or-other-configurations-for-concurrentkafkalistenercont/60958873#60958873). You just need to add the customizer as a bean and the framework will call it for each consumer binding. 

In the customizer, use `container.setErrorHandler(new LoggingErrorHandler())`.

**Comment by leighyu1983** [comment]
Thanks @garyrussell , I just figured it out by myself as below, but still the question. How to make it only attempts once(it would be great that even not trying failed message) rather than multiple times?  I called  acknowledgment.acknowledge() when capturing exception, but it does't work. It still tried to consume the record and kafka Consumer Offset is later than Last Offset, for instance Consumer Offset=7, Last Offset=8. That is to say, client didn't send ack(commit offset) to the broker. 

```java
@Component
public class MyErrorHandler {
	@Bean
	public ListenerContainerCustomizer haha() {
		return new ListenerContainerCustomizer() {
			@Override
			public void configure(Object container, String destinationName, String group) {
				ConcurrentMessageListenerContainer m = (ConcurrentMessageListenerContainer) container;
				m.setErrorHandler(new ErrorHandler() {
					@Override
					public void handle(Exception thrownException, ConsumerRecord<?, ?> data) {
						System.out.println(destinationName);
					}
				});
			}
		};
	}
}
```

**Comment by garyrussell** [comment]
This works fine for me:

```java
@SpringBootApplication
@EnableBinding(Sink.class)
public class Kbgh2002Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh2002Application.class, args);
	}

	@StreamListener(Sink.INPUT)
	public void listen(Message<?> in) {
		in.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class).acknowledge();
		throw new RuntimeException();
	}

	@Bean
	public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> customizer() {
		return (container, dest, group) -> container.setErrorHandler((ex, data) -> System.out.println(data));
	}

}
```

```properties
spring.cloud.stream.bindings.input.destination=kbgh2002
spring.cloud.stream.bindings.input.group=kbgh2002
spring.cloud.stream.bindings.input.consumer.max-attempts=1
spring.cloud.stream.kafka.bindings.input.consumer.auto-commit-offset=false

logging.level.org.springframework.kafka=debug
```

**Result**

```
2020-07-13 12:31:52.351 DEBUG 6277 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Received: 1 records
2020-07-13 12:31:52.373 ERROR 6277 --- [container-0-C-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: Exception thrown while invoking Kbgh2002Application#listen[1 args]; nested exception is java.lang.RuntimeException
...
Caused by: java.lang.RuntimeException
...
ConsumerRecord(topic = kbgh2002, partition = 0, leaderEpoch = 0, offset = 3, CreateTime = 1594657911273, serialized key size = -1, serialized value size = 3, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [B@6af910ef)
2020-07-13 12:31:52.374 DEBUG 6277 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Commit list: {kbgh2002-0=OffsetAndMetadata{offset=4, leaderEpoch=null, metadata=''}}
2020-07-13 12:31:52.374 DEBUG 6277 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Committing: {kbgh2002-0=OffsetAndMetadata{offset=4, leaderEpoch=null, metadata=''}}
2020-07-13 12:31:57.380 DEBUG 6277 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Received: 0 records
```

**Comment by leighyu1983** [comment]
@garyrussell  Thanks for the example.  What I've been doing is to encapsulate ``` in.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class).acknowledge(); ``` into  ```ChannelInterceptor inteface afterSendCompletion method ```, this is to avoid other's mistake by forgetting calling acknowledge method in @StreamListener. Would you please provide an example by doing so since I failed on the testing? Thanks very much.

**Comment by garyrussell** [comment]
It won't make any difference to the container where the ack is called; all it does is queue the offset for commit later when the consumer thread returns to the container.

**Comment by garyrussell** [comment]
Interesting; it shouldn't matter to the container where the ack is called from, but I see the same result; investigating...

**Comment by garyrussell** [comment]
It still works fine for me (I wasn't checking for ErrorMessage in my previous test)...

```java
@SpringBootApplication
@EnableBinding(Sink.class)
public class Kbgh2002Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh2002Application.class, args);
	}

	@StreamListener(Sink.INPUT)
	public void listen(Message<?> in) {
		throw new RuntimeException();
	}

	@Bean
	public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> customizer() {
		return (container, dest, group) -> container.setErrorHandler((ex, data) -> System.out.println(data));
	}

}

@Component
class AddIntercept {

	public AddIntercept(AbstractMessageChannel input) {
		input.addInterceptor(new ChannelInterceptor() {

			@Override
			public void afterSendCompletion(Message<?> message, MessageChannel channel, boolean sent,
					@Nullable Exception ex) {

				((ErrorMessage) message).getOriginalMessage()
						.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class).acknowledge();

			}


		});
	}

}
```

```
ConsumerRecord(topic = kbgh2002, partition = 0, leaderEpoch = 0, offset = 6, CreateTime = 1594659776038, serialized key size = -1, serialized value size = 3, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [B@7ac96d48)
2020-07-13 13:02:57.081 DEBUG 13920 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Commit list: {kbgh2002-0=OffsetAndMetadata{offset=7, leaderEpoch=null, metadata=''}}
2020-07-13 13:02:57.082 DEBUG 13920 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Committing: {kbgh2002-0=OffsetAndMetadata{offset=7, leaderEpoch=null, metadata=''}}
```

**Comment by leighyu1983** [comment]
@garyrussell Hello, I tried to set autoCommitOffset=false, however, offset is commited automatically without calling ```acknowledge()```.
```text
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
```

```yaml
spring:
  cloud:
    stream:
      kafka:
        bindings:
          input-K1:
            consumer:
              auto-commit-offset: false

      bindings:
        input-K3:
          destination: my.k3 #topic
          binder: my-kafka-3
          group: g3
          consumer:
            max-attempts: 1
        output-K3:
          destination: my.k3 #topic
          binder: my-kafka-3

      binders:
        my-kafka-3:
          type: kafka
          environment:
            spring:
              kafka:
                host: localhost
                port: 9092
```
```java
public interface MyInputBinding {
	String INPUT_K3 = "input-K3";

	@Input(INPUT_K3)
	SubscribableChannel inputK3();
}

public interface MyOutputBinding {
	String OUTPUT_K3 = "output-K3";

	@Output(OUTPUT_K3)
	MessageChannel outPutK3();
}

@EnableBinding(MyInputBinding.class)
public class MyKafkaListener {

	@StreamListener(MyInputBinding.INPUT_K3)
	public void recieveK1(Message<PersonObj> message) {
		throw new RuntimeException("..........this is runtime exception..............");
	}
}
```
