### ISSUE TITLE
Massive Logging when using StreamBridge

### ISSUE THREAD

**Issue by dbruegger** [spring-cloud/spring-cloud-stream#2034]
**Description**

We use StreamBridge to send messages triggered by a foreign source. The messages are sent successfully but it fills our log with logging messages such like this:

```
2020-10-15 08:46:00.905  INFO [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'streamBridge' with acceptedOutputTypes: [application/json]
```

The log message is logged each time the StreamBridge.send() method is called.

Our binding configuration looks like this:

```
spring:
  cloud:
    stream:
      default:
        group: ${application.name}
        consumer.autoStartup: false
        producer.autoStartup: false
      source: locationUpdatedEvent;pathUpdatedEvent
      bindings:
        locationUpdatedEvent-out-0:
          destination: x/y/z/movement-tracking/v1/LocationUpdatedEvent
        pathUpdatedEvent-out-0:
          destination: x/y/z/movement-tracking/v1/PathUpdatedEvent
```

Our application code looks like this:

```
@Service
public class MovementTrackingPublisher {

    private final StreamBridge streamBridge;

    @Autowired
    public MovementTrackingPublisher(StreamBridge streamBridge) {
        this.streamBridge = requireNonNull(streamBridge);
    }

    public void publishLocationUpdatedEvent(LocationUpdatedEvent event) {
        streamBridge.send("locationUpdatedEvent-out-0", MessageBuilder.withPayload(event).build());
    }

    public void publishPathUpdatedEvent(PathUpdatedEvent event) {
        streamBridge.send("pathUpdatedEvent-out-0", MessageBuilder.withPayload(event).build());
    }

}
```

**Version of the framework**

- Spring Boot 2.2.6.RELEASE
- Spring Cloud Hoxton.SR8
- Spring Cloud Stream 3.0.6.RELEASE (an update to 3.0.8.RELEASE did not solve the problem)
- Spring Cloud Stream Binder for Solace PubSub+ 2.1.1

**Expected behavior**

The function lookup is either logged with DEBUG level or logged only once with INFO level.
