### ISSUE TITLE
TestBinder is ignoring routing key

### ISSUE THREAD

**Issue by mzalewski82** [spring-cloud/spring-cloud-stream#2041]
TestBinder used by org.springframework.cloud.stream.binder.test.TestChannelBinderConfiguration (3.0.8.RELEASE) is ignoring RabbitMQ (AMQP) routing key. Messages are delivered in round robin fashion to all listeners bound to the exchange.
Every test where message is delivered to incorrect listener will fail.
Because of that it's imposible to have repeatable tests.

As a workaround I'm using testcontainers but I hope I'll see routing key support from you soon!

Example test facing this issue:
https://github.com/mzalewski82/contract-test-challenges/blob/main/listener-with-routing-key/src/test/java/com/example/multipleoutput/CustomSome_clientTest.java

**Comment by garyrussell** [comment]
The test binder knows nothing about RabbitMQ - it's just that - a test binder; it is not intended for testing features that are only supported by protocol-specific binders.

**Comment by mzalewski82** [comment]
Test tool shouldn't force solutions used in production code.
With current test binder I must make a difficult choice. Options I see to solve routing key problem in tests:
1. Use test containers -> slow tests.
2. Use dedicated config for tests, 1-1 queue-exchange, no routing keys -> app I'm testing is not the same I'm running on prod.
3. Don't use routing keys.

I'd love to have 4th option. Use routing keys, same config on prod and tests, have fast tests.

I understand that TestBinder knows nothing about RabbitMQ as it works on a higher abstraction level. I would like to have simple and efficient way to test my code. If there's any I haven't mentioned above please let me know.

**Comment by olegz** [comment]
You are discussing integration tests and for those you indeed should use a real binder with a real messaging broker. Test binder was meant for unit testing of features that are not specific to various binders that are out there. In other words test binder is not to test specific features of rabbit binder that rely on RabbitMq.

**Comment by mzalewski82** [comment]
@olegz This is the problem, using routing key makes unit tests impossible. I don't want to test any broker specific stuff I just want a message to reach the listener I'm test. Unfortunately routing key is RabbitMQ specific and TestBinder is unable to  meet this basic need.

How do you recommend to unit test a listener that uses a routing key?

**Comment by mzalewski82** [comment]
Example:
Config:
```
spring:
  cloud:
    function:
      definition: inputMessageProcessor;additionalInputMessageProcessor
    stream:
      bindings:
        inputMessageProcessor-in-0:
          destination: myInputExchange
          group: messageProcessorGroup
        additionalInputMessageProcessor-in-0:
          destination: myInputExchange
          group: additionalMessageProcessorGroup
        inputMessageProcessor-out-0:
          destination: myOutputExchange
        additionalInputMessageProcessor-out-0:
          destination: myOutputExchange
      rabbit:
        bindings:
          inputMessageProcessor-in-0:
            consumer:
              bindingRoutingKey: messages
          additionalInputMessageProcessor-in-0:
            consumer:
              bindingRoutingKey: additionalMessages
```

test:
```
import org.junit.jupiter.api.RepeatedTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.stream.binder.test.InputDestination;
import org.springframework.cloud.stream.binder.test.OutputDestination;
import org.springframework.cloud.stream.binder.test.TestChannelBinderConfiguration;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(classes = {RoutingKeyTestApplication.class, TestChannelBinderConfiguration.class})
class ConfigTest {

    @Autowired
    private InputDestination inputDestination;

    @Autowired
    private OutputDestination outputDestination;

    @RepeatedTest(10)
    public void testInputMessageProcessor() {

        inputDestination.send(MessageBuilder.withPayload(new InputMessage("abc")).build());

        Message<byte[]> received = outputDestination.receive();
        assertThat(received).isNotNull();
    }
}
```

This test will fail 5 times and pass 5 times because of round robin mentioned earlier.
