### ISSUE TITLE
Make InputDestination#send method bindingName argument work as documentation says.

### ISSUE THREAD

**Issue by mzalewski82** [spring-cloud/spring-cloud-stream#2042]
Currently bindingName works only when binding destination is passed. I would like it to work as described in documentation:

`
Allows the {@link Message} to be sent to a Binder to be delegated to a named binding
	 * destination (e.g., "function-in-0" for cases where you want to send input to function with the name 'function').
`

I've prepared an example project to show the problem:
https://github.com/mzalewski82/contract-test-challenges/tree/main/listener-with-routing-key
I have a config:
```
spring:
  cloud:
    function:
      definition: inputMessageProcessor;additionalInputMessageProcessor
    stream:
      bindings:
        inputMessageProcessor-in-0:
          destination: myInputExchange
          group: messageProcessorGroup
        additionalInputMessageProcessor-in-0:
          destination: myInputExchange
          group: additionalMessageProcessorGroup
        inputMessageProcessor-out-0:
          destination: myOutputExchange
        additionalInputMessageProcessor-out-0:
          destination: myOutputExchange
```

And test:
```
    @RepeatedTest(10)
    public void testInputMessageProcessor() {

        inputDestination.send(MessageBuilder.withPayload(new InputMessage("abc")).build(), "myInputExchange");

        Message<byte[]> received = outputDestination.receive(0L, "myOutputExchange");
        assertThat(received).isNotNull();
    }
```
I the test I have to pass binding destination as `bindingName`: `myOutputExchange`.
When I use binding name `inputMessageProcessor-in-0` as bindingName, test is crashing:
`
java.lang.NullPointerException
	at org.springframework.cloud.stream.binder.test.InputDestination.send(InputDestination.java:57)
`
