### ISSUE TITLE
Kafka not working after upgrading to Hoxton.SR9

### ISSUE THREAD

**Issue by aariza1** [spring-cloud/spring-cloud-stream#2050]
Hello,
I have been getting the following exception in all our services that include Kafka after upgrading to Hoxton.SR9.
With Hoxton.SR8 is working just fine.

org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException:

Somehow the service is not able to subscribe to the kafka topic.

We are also using Spring Boot 2.3.6.RELEASE
Any idea what could be triggering this error?
I posted an issue on the spring-kafka project and i was told to post it here.

This is the stacktrace

`org.springframework.kafka.KafkaException: Seek to current after exception; nested exception is org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}], failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}]
at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:157)
at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:113)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeErrorHandler(KafkaMessageListenerContainer.java:2037)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1936)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1863)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1757)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1478)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1141)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1044)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.kafka.listener.ListenerExecutionFailedException: Listener failed; nested exception is org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}], failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}]
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.decorateException(KafkaMessageListenerContainer.java:2052)
... 10 common frames omitted
Caused by: org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'classification-group-provider-1.mapClassificationGroup-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[4535], headers={kafka_offset=1294235, scst_nativeHeadersPresent=true, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@6bfa116c, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=44, kafka_receivedMessageKey=S0A0H0YE, contentType=application/json, kafka_receivedTopic=product-updates, kafka_receivedTimestamp=1605257699523, kafka_groupId=classification-group-provider, accept=application/json}]
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.sendMessageIfAny(KafkaMessageDrivenChannelAdapter.java:390)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.access$300(KafkaMessageDrivenChannelAdapter.java:77)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:449)
at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter$IntegrationRecordMessageListener.onMessage(KafkaMessageDrivenChannelAdapter.java:423)
at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.lambda$onMessage$0(RetryingMessageListenerAdapter.java:120)
at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)
at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:114)
at org.springframework.kafka.listener.adapter.RetryingMessageListenerAdapter.onMessage(RetryingMessageListenerAdapter.java:40)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2004)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1986)
at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1923)
... 8 common frames omitted
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139)
at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
... 27 common frames omitted`

Thank you in advance!

**Comment by garyrussell** [comment]
As I said in the issue you raised against spring-kafka; you need to show your application.yml and any other pertinent code/configuration.

Even better would be a small, complete, project that exhibits this behavior (works with SR8 but not with SR9).

**Comment by aariza1** [comment]
application.yaml


[application_test.yml.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5561255/application_test.yml.zip)

**Comment by garyrussell** [comment]
```yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    function:
      definition: mapClassificationGroup
    stream:
      bindings:
        mapClassificationGroup-in-0:
          destination: product-updates
          group: ${spring.application.name}
        mapClassificationGroup-out-0:
          destination: products-of-source
          producer:
            partition-key-expression: headers['productId']
            partition-count: 32
      kafka:
        binder:
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
```

**Comment by garyrussell** [comment]
Pretty basic configuration. Something else must have changed; I just tested with your config on SR9 with no problems.

Please put together a complete, simple, example that exhibits the behavior you see.

**Comment by garyrussell** [comment]
I see this is test YAML.

Are you using the embedded kafka broker?

Is this perhaps a downstream error?

If so, see this https://github.com/spring-projects/spring-kafka/issues/1604#issuecomment-719569056

There is an issue with Boot 2.3.6 pulling in a Jackson version that pulls in an incompatible Scala jar.

**Comment by aariza1** [comment]
I just named the .yaml test do duplicate it. 

No, we are not using the embedded kafka broker.

I am trying to recreate the error in a demo project. 

thank you

**Comment by aariza1** [comment]
Well, 
after recreating the situation in a demo project, it seems to work perfectly with Hoxton SR.9. 
The error must be from our side, will try to fix it.

Thank you very much for your time and sorry about the time lost.

**Comment by iashaposhnikov** [comment]
Hello,
try to set a property
spring.cloud.stream.kafka.binder.auto-create-topics: false

**Comment by aariza1** [comment]
@iashaposhnikov I tried it and did not work.

**Comment by aariza1** [comment]
Hello,

we have not being able to fix this issue, I guess i should be more specific:

application.yml
```
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    function:
      definition: mapClassificationGroup
    stream:
      bindings:
        mapClassificationGroup-in-0:
          destination: product-updates
          group: ${spring.application.name}
        mapClassificationGroup-out-0:
          destination: products-of-source
          producer:
            partition-key-expression: headers['productId']
            partition-count: 32
      kafka:
        binder:
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
```

Application.kt

```@SpringBootApplication
@ConfigurationPropertiesScan
@EnableReactiveMethodSecurity
class Application(
        private val mongoTemplate: ReactiveMongoTemplate,
        private val mongoMappingContext: MongoMappingContext
) {

    @EventListener(ApplicationReadyEvent::class)
    fun initIndicesAfterStartup() {
        // business logic
    }
}

fun main(args: Array<String>) {
    runApplication<Application>(*args)
}
```

ProductMapper.kt

```
@Configuration
class ProductMapper(
        private val mappingService: MappingService,
        private val meterRegistry: MeterRegistry
) {

    private val failureCounterName = "products.failure"

    @Bean
    fun mapClassificationGroup(): Function<Flux<Product>, Flux<Message<ProductOfSource>>> = Function { products ->
        products
                .concatMap { handleProduct(it) }
                .onErrorStop()
    }

    private fun handleProduct(product: Product): Mono<Message<ProductOfSource>> = product.toMono()
// Business logic ...
```

The error remains the same. As I said before, this only happens after upgrading to Hoxton.SR9, no other changes.

Thank you very much for any help.
