### ISSUE TITLE
binder's consumerProperties and producerProperties are not used, only configuration is applied

### ISSUE THREAD

**Issue by psporysz** [spring-cloud/spring-cloud-stream#2060]
**Describe the issue**
As opposed to documentation the
`spring.cloud.stream.kafka.binder.producerProperties` and `spring.cloud.stream.kafka.binder.consumerProperties` properties got ignored and only `spring.cloud.stream.kafka.binder.configuration` is applied.

**To Reproduce**
My `spring.cloud.stream.kafka.binder` prefix:
```
            configuration:
              interceptor.classes: my.ActuallyUsedInterceptor
            producerProperties:
              interceptor.classes: my.DesiredProducerInterceptor
            consumerProperties:
              interceptor.classes: my.DesiredConsumerInterceptor
```

**Version of the framework**
2.3.3.RELEASE

**Expected behavior**
`spring.cloud.stream.kafka.binder.producerProperties` and `spring.cloud.stream.kafka.binder.consumerProperties`  will override the `spring.cloud.stream.kafka.binder.configuration`

**Additional context**
I looked at `KafkaStreamsBinderSupportAutoConfiguration` and found that `streamConfigGlobalProperties` bean factory method only uses:

```
        if (!ObjectUtils.isEmpty(configProperties.getConfiguration())) {
            properties.putAll(configProperties.getConfiguration());
        }
```

I also found that `configProperties.getConsumerProperties()` and `configProperties.getProducerProperties()` were filled correctly but had never been used during startup.
