### ISSUE TITLE
The binding properties defined for springCloudBusOutput binding take no effect

### ISSUE THREAD

**Issue by JordiMartinezVicent** [spring-cloud/spring-cloud-stream#2077]
**Describe the bug**
I am using the spring-cloud-bus version 3.0.0-RC1. 

When a message is sent through the bus, the binding properties defined with the namespace 'spring.cloud.stream.bindings.springCloudBusOutput' take no effect. 

It is due to the implementation of **StreamBusBridge**, as it is sending the message directly to the bus destination

```java
this.streamBridge.send(properties.getDestination(), MessageBuilder.withPayload(event).build());
```
instead to the bindingName, as is stated in the spring-cloud-stream StreamBridge documentation.

**Comment by olegz** [comment]
This may just be a documentation update, but let me investigate first

**Comment by JordiMartinezVicent** [comment]
[bus-example.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5801694/bus-example.zip)

I have attached a simple example in order to reproduce it with spring-cloud-bus + kafka binder. You will need a kafka to run it. (Sorry, I should have update it before). 

The example is driven by the test class SendEventBusTest. 

The test sendEventByBus is sending an event through the bus via ApplicationContext: 

```
@Test
void sendEventByBus() {
	MyRemoteEvent event = new MyRemoteEvent(this, busProperties.getId(), () -> "**");

	context.publishEvent(event);
}
```
with the next configuration: 
```
spring:
  application:
    name: bus-example
  cloud:
    bus:
      destination: bus.topic
    stream:
      bindings:
        springCloudBusOutput:
          destination: ${spring.cloud.bus.destination} # Should be added by BusEnvironmentPostProcessor
          producer:
            header-mode: embeddedheaders
```

If you see the message sent to kafka, the headers are NOT embedded into the message, so the property `producer.header-mode=embeddedHeaders` takes no effect. 

On the other hand, with the following test using the StreamBridge directly, the property is working fine: 

```
@Test
void sentEventByStreamBridge() {
	MyRemoteEvent event = new MyRemoteEvent(this, busProperties.getId(), () -> "**");

	streamBridge.send(BusConstants.OUTPUT, event); // BusConstants.OUTPUT defines the bindingName (springCloudBusOutput). Currently StreamBusBridge passess the destination directly. 
}
```

Note that in the application.yml I added the following property: 

```
spring:  
    stream:
      bindings:
        springCloudBusOutput:
          destination: ${spring.cloud.bus.destination} # Should be added by BusEnvironmentPostProcessor
```

But it is something that I think it should be added by the BusEnvironmentPostProcessor. 


Many thanks to take a look at this :)
