### ISSUE TITLE
InputDestination for same destination with different groups

### ISSUE THREAD

**Issue by jmecsei** [spring-cloud/spring-cloud-stream#2094]
Hi,
I have a binding configuration where I use same destination with different groups.
                                                                                 
                                                                                                                                                                    
                                                                                    
                                                       +---------------------------+
                                                    /--|     INVOICE QUEUE         |
                                                /---   |                           |
         +-----------------------------+    /---       +---------------------------+
         |      FINANCIAL EXCHANGE  -  | ---                                        
         |                             |----           +---------------------------+
         +-----------------------------+    \------    |    SIMPLEPAY QUEUE        |
                                                   \---|                           |
                                                       +---------------------------+
                                                                                    

```yaml
     bindings:
        ipnMessageConsumer-in-0:
          group: simplepay.financial
          destination: financial
          content-type: application/json
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 30000
            backOffMaxInterval: 120000
            backOffMultiplier: 2.0
            defaultRetryable: false
            retryableExceptions:
              x.y.z.ServiceUnavailableException: true
        createInvoiceMessageConsumer-in-0:
          group: invoice.create.financial
          destination: financial
          content-type: application/json
          consumer:
            maxAttempts: 1
            defaultRetryable: false
    function:
      definition: ipnMessageConsumer;createInvoiceMessageConsumer
```

It is working well. But when I want to write a test I got an exception, because the InputDestination bind the the channels by destination name!

```java

class ProcessIpnMessageHappyPathIT {
    @Autowired
    private InputDestination inputDestination;

    @ResourceContent("classpath:files/json/queue/ipn_transaction_message.json")
    private String requestBody;

    @Test
    void test_updateTransaction_should_setProperValues() {
        // GIVEN

        // WHEN
        inputDestination.send(MessageBuilder.withPayload(requestBody).build());

        // THEN
    }
}
```

I tried to write this
```java
  inputDestination.send(MessageBuilder.withPayload(requestBody).build(), "ipnMessageConsumer-in-0");
```
but it does not work becaue, the AbstractDestination find the channels by name.

```java
	SubscribableChannel getChannelByName(String name) {
		name = name.endsWith(".destination") ? name : name + ".destination";
		for (AbstractSubscribableChannel subscribableChannel : channels) {
			if (subscribableChannel.getBeanName().equals(name)) {
				return subscribableChannel;
			}
		}
		return null;
	}
```

I need some help to how can I solve this problem. Or I think it would be better to I can define the binding name to the InputDestination instead of the destination name( lets see above ):
