### ISSUE TITLE
Cannot create a binding dynamically using ExtendedProducerProperties

### ISSUE THREAD

**Issue by tigermarques** [spring-cloud/spring-cloud-stream#2146]
**Describe the issue**
I am trying to create a binding dynamically with properties set in my ExtendedProducerProperties. However, these properties are ignored when merging my properties with the binder default properties.

I have a use case where I support bindings being created dynamically. For each of them, I create my consumer and producer dynamically, and I need to enforce that the schema registry is used and the schema validation is enforced. A way of doing that would be to force users to configure my library with the following in their `application.yml`:

```yml
spring:
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          brokers:
            - localhost:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
            schema.registry.url: mock://url-test
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: mock://url-test
            specific.avro.reader: true
```

However, I am trying to enforce this using code, so that it does not require a configuration that must always be the same.

**To Reproduce**
I am building my producer using something like:

```java
Map<String, String> configuration = new HashMap<>();
configuration.put("value.serializer", "io.confluent.kafka.serializers.KafkaAvroSerializer");
configuration.put("value.subject.name.strategy", "io.confluent.kafka.serializers.subject.RecordNameStrategy");
KafkaProducerProperties extensionProperties = new KafkaProducerProperties();
extensionProperties.setConfiguration(configuration);
final ProducerProperties producerProperties = new ExtendedProducerProperties<>(extensionProperties);
producerProperties.setUseNativeEncoding(true);

final BindingProperties bindingProperties = new BindingProperties();
bindingProperties.setDestination("topic");
bindingProperties.setProducer(producerProperties);
bindingProperties.setContentType("application/*+avro");

this.bindingServiceProperties.getBindings().put(bindingName, bindingProperties);
final MessageChannel channel = (MessageChannel) this.bindingTargetFactory.createOutput(bindingName);
this.bindingService.bindProducer(channel, bindingName);
```

The binding is created successfully, and I am able to produce messages. However, the 2 properties I set in `configuration` are lost during the binding creation.

I have pinned the problem to this [line in BindingService](https://github.com/spring-cloud/spring-cloud-stream/blob/47125a155747f400817cccf3ddd666ebd1a52cd4/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L277)

Here, the two properties are merged. However, the `extension` field is skipped because it does not have a valid setter. Therefore, everything I have in my `configuration` object is ignored.

**Possible Solution**

The way I see it, there are two approaches to fix this/add this functionality:
1. Add a setter to [ExtendedProducerProperties](https://github.com/spring-cloud/spring-cloud-stream/blob/47125a155747f400817cccf3ddd666ebd1a52cd4/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/ExtendedProducerProperties.java#L23)
2. Before creating the `extendedProducerProperties`, merge the extensions and create the object with the merged extension
```java
Object extension = ((ExtendedPropertiesBinder) binder).getExtendedProducerProperties(outputName);
if (producerProperties instanceof ExtendedProducerProperties) {
  BeanUtils.copyProperties(((ExtendedProducerProperties<?>) producerProperties).getExtension(), extension);
}
ExtendedProducerProperties<?> extendedProducerProperties = new ExtendedProducerProperties<>(extension);
BeanUtils.copyProperties(producerProperties, extendedProducerProperties);

producerProperties = extendedProducerProperties;
```

The same problem creating consumers dynamically using the ExtendedConsumerProperties. The same solutions might apply.

Thanks a lot!
