### ISSUE TITLE
Functional style binding for multiple input topics only creates one consumer group

### ISSUE THREAD

**Issue by AttitudeL** [spring-cloud/spring-cloud-stream#2148]
Dear developers,

I have a working application that uses spring-cloud-stream functional style for input and output topics binding.

After deployed the application to dev environment I discovered some weird behaviour which I found to be best clarified in this thread.

Currently I have 2 bindings settings: one for spring.cloud.stream.kafka and the other one for spring.clould.stream.kafka.streams

For the spring.cloud.stream.kafka bindings the config looks like the following:
```
spring.cloud.stream:
  function:
    destination: processor
  kafka.binder:
    brokers: localhost:9092
    autoCreateTopics: false
  bindings:
    processor-in-0:
      group: group.topic.0
      destination: input_topic_0
      consumer:
        concurrency: 12
    processor-in-1:
      group: group.topic.1
      destination: input_topic_1
      consumer:
        concurrency: 12
    processor-in-2:
      group: group.topic.2
      destination: input_topic_2
      consumer:
        concurrency: 12
    processor-out-0:
        destination: output_topic_0
```

For the spring.clould.stream.kafka.streams the config looks like the following:
```
spring.cloud.stream.kafka.streams:
  binder:
    brokers: localhost:9092
    autoCreateTopics: false
    configuration:
      schema.registry.url: mock://
      num.stream.threads: 12
  bindings:
    processor-in-0:
      consumer:
        applicationId: processor-app-0
    processor-in-1:
      consumer:
        applicationId: processor-app-1
    processor-in-2:
      consumer:
        applicationId: processor-app-2
```

Then the function as the spring bean that binds to these input topics:
```
@Bean
public Function<KStream<String, String>,
	Function<KStream<String, String>,
		Function<KStream<String, String>,
			KStream<String, String>>>> processor() {
    return stream0 -> stream1 -> stream2 {
        return ....
    };
}
```
As you can see that I've created a binding function "processor" that binds to 3 input topics and produce to 1 output topic.

After the application is started, I saw that 12 stream threads were created, this is the correct behaviour since I set the number of stream threads to be 12.

However in terms of the group creation, I only see "processor-app-0" being created and all 12 consumers have been assigned under this one group. Also this single group appears to have subscribed to all 3 input topics where I was intentionally wanting one consumer group per input topic.

So there are 2 issues:

The first issue is that the spring.cloud.stream.kafka.streams applicationId appears to have overridden the group name I set from the spring.cloud.stream.kafka bindings.

The second issue is that I do not see consumer group for "processor-app-1" and "processor-app-2" even though I've specifically defined them inside the spring.cloud.stream.kafka.streams bindings. After the application is deployed, there is only one consumer group created "processor-app-0" which appeared to be the applicationId from the kafka.streams binding for the first parameter. All the group.id I defined earlier inside the kafka bindings seem to be gone or overridden.

I'm wondering if this is the correct behaviour, if it is then did I do something wrong?
