### ISSUE TITLE
MessageConverterConfigurer throws NPE since #2145 fix

### ISSUE THREAD

**Issue by lz101010** [spring-cloud/spring-cloud-stream#2160]
**Describe the issue**
The fix for #2145 introduces a NPE for my setup: I cannot start the application context with `3.0.12.RELEASE`, but with `3.0.11.RELEASE` I can.

**To Reproduce**
I'm using the old non-functional programming model with `@Input`, `@Output`, `@StreamListener` with the following minimal setup:
```java
@SpringBootApplication(scanBasePackages = "com.example")
@EnableBinding(MessageChannels.class)
public class ExampleApplication {
    public static void main(String[] args) {
        SpringApplication.run(ExampleApplication.class, args);
    }
}

public interface MessageChannels {
    // ...
    @Output("admin-out") MessageChannel adminNotificationsOut();
    // ...
}
```
```yml
// application.yml
spring:
  cloud.stream.bindings:
    admin-out:
      binder: rabbit
      contentType: application/json
      destination: notifications
      group: notifications.admin
  cloud.stream.rabbit.bindings:
    admin-out:
      producer:
        routingKeyExpression: "'admin'"
```
I've set up a sample project here for figuring out issues with my contract tests where messages aren't intercepted properly: https://github.com/lz101010/scc-messaging-triggeredby-method/tree/scst-3.0.x

This setup lets me run tests for `3.0.11.RELEASE`, but fails to load the ApplicationContext for `3.0.12.RELEASE`, because
```java
// MessageConverterConfigurer.java

if (environment != null && environment.containsProperty("spring.cloud.stream.rabbit.bindings." + channelName + ".producer.routing-key-expression")) {
    FunctionCatalog catalog = this.beanFactory.getBean(FunctionCatalog.class);
    FunctionInvocationWrapper function = catalog.lookup(this.streamFunctionProperties.getDefinition()); // definition = null
    function.setSkipOutputConversion(true); // <-- function = null
    functional = false;
}
```

**Version of the framework**
`3.0.11.RELEASE` / everything after #2145 fix

**Expected behavior**
Application context starts.

**Additional context**
https://github.com/spring-cloud/spring-cloud-contract/issues/1626
