### ISSUE TITLE
Kafka Message Key Header is dropped for Supplier functions

### ISSUE THREAD

**Issue by selcuksert** [spring-cloud/spring-cloud-stream#2173]
**Describe the issue**
Even Kafka Message Key header is set, the message is serialized without it (the message key is set as null) which avoids to utilize Kafka partitioning mechanism for this message.

The message key is also observed as null in consumer end:
```java
	@Bean
	public BiConsumer<KStream<String, Task>, KStream<String, User>> process() {
		return (taskStream, userStream) -> {
			taskStream.peek((key, task) -> log.info("key: {} | task: {}", key, task))
					.toTable(Materialized.as(taskTable)).toStream();
			userStream.peek((key, user) -> log.info("key: {} | user: {}", key, user))
					.toTable(Materialized.as(userTable)).toStream();
		};
	}
```

```
2021-05-11 17:50:43.477  INFO 6385 --- [-StreamThread-1] c.c.c.t.s.processor.TaskProcessor        : key: null | user: {"id": "***", "firstname": "***", "lastname": "***"}

```

As a workaorund `messageKeyExpression` is set as `payload['id']`but it also prevents to delete this with a tombstone message on Kafka as it is impossible to set a payload with an id.

There should be a way to set Kafka message key header for supplier functions used by outbound message channels.

**Version of the framework**
```XML
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-dependencies</artifactId>
<version>Hoxton.SR11</version>
```

**Expected behavior**
The message key should be set using `MessageBuilder`'s `setHeader` method and sent to Kafka topic.

**Additional context**
Here is the source class that emits message to Kafka topic:
```java
package com.corp.concepts.taskmanager.services.source;

import java.util.function.Supplier;

import org.springframework.context.annotation.Bean;
import org.springframework.kafka.support.KafkaHeaders;
import org.springframework.kafka.support.KafkaNull;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.stereotype.Service;

import com.corp.concepts.taskmanager.models.User;

import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Sinks;
import reactor.core.publisher.Sinks.EmitFailureHandler;
import reactor.core.publisher.Sinks.Many;

@Service
@Slf4j(topic = "User Message Generator")
public class UserMessageGenerator {

	private final Many<Message<?>> processor = Sinks.many().multicast().onBackpressureBuffer();

	public void emitMessage(User user) {
		Message<User> message = MessageBuilder.withPayload(user).setHeader(KafkaHeaders.MESSAGE_KEY, user.getId()).build();

		processor.emitNext(message, EmitFailureHandler.FAIL_FAST);

		log.info("Message sent");
	}

	public void deleteMessage(String id) {
		// Use tombstone message to remove item data from Kafka
		Message<KafkaNull> message = MessageBuilder.withPayload(KafkaNull.INSTANCE)
				.setHeader(KafkaHeaders.MESSAGE_KEY, id).build();

		processor.emitNext(message, EmitFailureHandler.FAIL_FAST);

		log.info("Message sent");
	}

	@Bean
	public Supplier<Flux<?>> output() {
		return () -> processor.asFlux();
	}

}
```

The application.yml for this producer is:
```yml
spring:
  cloud:
    stream:
      function:
        definition: output
      kafka:
        bindings:
          output-out-0:
            producer:
              messageKeyExpression: headers['kafka_messageKey']
        binder:
          auto-create-topics: false
          autoAddPartitions: false
          brokers:
          - ***
          - *** 
          producer-properties:
            '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
            '[value.serializer]': io.confluent.kafka.serializers.KafkaAvroSerializer
            '[schema.registry.url]': ***
      bindings:
        output-out-0:
          destination: users
          content-type: application/*+avro
          producer:
            useNativeEncoding: true
```

After some debugging it seems when `skipOutputConversion` is set to false the payload of message is extracted and sent without custom headers:

**org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry** :
```java

		private Object convertOutputIfNecessary(Object output, Type type, String[] contentType) {
			if (this.skipOutputConversion) {
				return output;
			}
			if (output instanceof Message && isExtractPayload((Message<?>) output, type)) {
				output = ((Message) output).getPayload();
			}
```
The only way to set this flag to true is also set configuration parameter for producer `useNativeEncoding` to true:

https://github.com/spring-cloud/spring-cloud-stream/blob/08d0ae3093e2ef52895294d7b6fd17b4643e06b6/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L485

Even it is set in application.yml the method call that executes the setter is simply ignored for Supplier functions which is also used in this case:

https://github.com/spring-cloud/spring-cloud-stream/blob/08d0ae3093e2ef52895294d7b6fd17b4643e06b6/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L400-L402
