### ISSUE TITLE
Invalid content type with reactive aproach

### ISSUE THREAD

**Issue by mkluzacek** [spring-cloud/spring-cloud-stream#2187]
**Describe the issue**
After upgrading from spring boot 2.3.0 and spring cloud stream binder rabbit 3.0.8 to versions 2.4.5 and 3.1.2 all messages sent with reactive approach now have content_type: application/octet-stream

Code used:
``` java
  @Bean
  public EmitterProcessor<AggregationEvent> aggregationEventEmitter() {
    return EmitterProcessor.create();
  }

  @Bean
  public Supplier<Flux<AggregationEvent>> aggregationEventsOut(
      EmitterProcessor<AggregationEvent> aggregationEventEmitter
  ) {
    return () -> aggregationEventEmitter;
  }
```
and then calling: `emitterProcessor.onNext(eventMessage);`

Application.yml:
```
spring:
  cloud:
    stream:
      bindings:
        aggregationEventsOut-out-0:
          destination: backend-events
          content-type: application/json

      rabbit:
        bindings:
          aggregationEventsOut-out-0:
            producer:
              routingKeyExpression: 'headers.type'
```

I tried explicitly setting the content type via `application.yml` and rewriting the code to use `Sink` instead of the deprecated `EmitterProcessor` but nothing changed.

**Version of the framework**
spring boot 2.4.5 and spring cloud stream binder rabbit 3.1.2
**Expected behavior**
Messages have the default application/json content type like in version 3.0.8
