### ISSUE TITLE
No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

### ISSUE THREAD

**Issue by mmaeller** [spring-cloud/spring-cloud-stream#2189]
As far as I can track the issue down, due the commit for #2165 a regression has been created for issue #1979.
I cannot start the application using a producer based expression property like 'routingKeyExpression' or 'delayExpression'.
If I comment them out, the application starts properly.

**To Reproduce**
```yaml
spring:
  cloud:
    stream:
      bindings:
        inputMail:
          destination: ${rabbitmq.mail.exchange}
          group: ${rabbitmq.mail.queue}
          binder: rabbitMail
          consumer:
            maxAttempts: 1
        retryMail:
          destination: ${rabbitmq.mail.exchange}
          binder: rabbitMail
        dlqMail:
          destination: ${rabbitmq.mail.dlx}
          binder: rabbitMail
      binders:
        rabbitMail:
          type: rabbitMail
          environment:
            spring:
              cloud:
                stream:
                  rabbit:
                    bindings:
                      inputMail:
                        consumer:
                          autoBindDlq: true
                          queueNameGroupOnly: true
                          exchangeAutoDelete: false
                          deadLetterExchange: ${rabbitmq.mail.dlx}
                          delayedExchange: true
                      retryMail:
                        producer:
                          declareExchange: false
                          exchangeAutoDelete: false
                          delayExpression: 300000 # 5min
                      dlqMail:
                        producer:
                          declareExchange: false
                          exchangeAutoDelete: false
                          routingKeyExpression: '''${rabbitmq.mail.queue}'''
```

**Version of the framework**
3.1.3 (Spring cloud dependencies 2020.0.3)
Spring Boot 2.4.5 and also with 2.4.7
**Expected behavior**
Configuration works as in 3.1.2 (Spring cloud dependencies 2020.0.2)

The property will be resolved properly, but the application cannot start.
**Error message**
```

Failed to bind properties under 'spring.cloud.stream.rabbit.bindings.dlqMail.producer.routing-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.rabbit.bindings.dlqMail.producer.routing-key-expression
    Value: 'mail-local'
    Origin: "spring.cloud.stream.rabbit.bindings.dlqMail.producer.routingKeyExpression" from property source "rabbitMail"
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

```

**Comment by Been24** [comment]
i am using spring-boot 2.5.1 & spring-cloud 2020.0.3(stream3.1.3), the error happened,if i change spring-cloud-stream.jar to 3.1.2,it works

**Comment by olegz** [comment]
So, it is fixed. The issue is with the fact that we've refactored how child (binder) context is created and not all the moving parts fell into place the right way

**Comment by Samehadar** [comment]
@olegz thanks for this fix. Has it released yet? What version should I use now?

**Comment by olegz** [comment]
@Samehadar in 3.0.x versions you would not have this issue (latest is 3.0.12.RELEASE). It was only introduced effectively as a regression in 3.1.3. IN other words you would not have this issue with 3.1.2 either. 
So, this specific fix  will be released in 3.1.4. No date is set for it yet, but I may do it sooner outside of spring-cloud release cycle.

**Comment by Samehadar** [comment]
@olegz damn, I am so unlucky, I had updated our cloud stream exactly to 3.1.3 version. 
No need for you to hurry, I am going to use 3.1.2 instead then. Thanks for helping.

**Comment by at-kkray** [comment]
@olegz is there any work around for this? Our application has multiple binders (kafka & rabbit) and uses `@Configuration` and classes for beans so cannot use version 3.1.2 due to other bug: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1030.

**Comment by erizzo** [comment]
What about a release date for 3.1.4? Or even a beta build that we can try?

**Comment by zggg** [comment]
add these configuration it's work ! @olegz @mmaeller @erizzo 
spring:
  cloud:
    stream:
      binders:
        rabbit:
          environment:
            spring:
              main:
                 sources: org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration

**Comment by zggg** [comment]
add these configuration it's work ! @olegz @mmaeller @erizzo

`
spring:
  cloud:
    stream:
      binders:
        rabbit:
          environment:
            spring:
              main:
                 sources: org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration
`

**Comment by zggg** [comment]
add these configurations. it's works on 3.1.3 @olegz @erizzo @Samehadar @mmaeller @Been24 

```
spring:
  cloud:
    stream:
      binders:
        rabbit:
          environment:
            spring:
              main:
                 sources: org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration
```
