### ISSUE TITLE
Routing function and extended binding properties

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#2200]
It does not look like the following is possible.

```
spring:
  cloud:
    stream:
      function:
        routing:
          enabled: true
      kafka:
        bindings:
          functionRouter-in-0:
            consumer:
              enableDlq: true
              ackEachRecord: true
              autoCommitOffset: true
              autoCommitOnError: false
```

The Kafka bindings are ignored and the application gets into an unstable state. It is convenient for the app developer to set extended binding properties on the routing function bindings. For example, what if something goes wrong with the function routing and it throws an exception in which case the application prefers to send the record in error to a `DLQ`.
