### ISSUE TITLE
Too many retries of message consumption

### ISSUE THREAD

**Issue by 472827074** [spring-cloud/spring-cloud-stream#2205]
When I used Kafka, I found a bug where the number of message consumption failed retries is random, the default is 3 times, but my configuration of this number is invalid, and my direct configuration of RetryTemplate is also invalid. Each time the number of retries is more than 9 , Sometimes even more than 20 times. Here is the version information I used:
  springboot  2.3.3.RELEASE
  spring-cloud Hoxton.SR7

The following configurations are invalid
```yaml
spring:
  cloud:
      stream:
        bindings:
          orderInput:
            destination: order-topic
            group: order-service
            consumer:
              maxAttempts: 2
```
```java
@Bean
    public RetryTemplate retryTemplate() {

        RetryTemplate retryTemplate = new RetryTemplate();
        retryTemplate.setBackOffPolicy(new ExponentialBackOffPolicy());

        SimpleRetryPolicy retryPolicy = new SimpleRetryPolicy();
        retryPolicy.setMaxAttempts(2);
        retryTemplate.setRetryPolicy(retryPolicy);

        return retryTemplate;
    }
```
Looking forward to your reply, thank you very much
