### ISSUE TITLE
Stopping a Binding bound to a Supplier<?> bean does not stop

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2212]
The `Lifecycle` in the `Binding` is the message producer; in most cases stopping this component does nothing.

The `SourcePollingChannelAdapter` that invokes the supplier needs to be stopped as well.

https://stackoverflow.com/questions/68895758/spring-cloud-stream-with-kafka-binder-bindings-actuator-api-does-not-stop-prod/68896149#68896149

**Comment by garyrussell** [comment]
Also related; `auto-startup=false` does not work for output bindings.

```yaml
spring:
  cloud:
    stream:
      bindings:
        foo:
          producer:
            auto-startup: false
      function:
        bindings:
          output-out-0: foo
```
```java
	@Bean
	Supplier<String> output() {
		return () -> {
			log.info("Sending");
			return "foo";
		};
	}
```
```
[scheduling-1] Sending
[scheduling-1] Sending
[scheduling-1] Sending
[scheduling-1] Sending
[scheduling-1] Sending
[scheduling-1] Sending
```
