### ISSUE TITLE
No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

### ISSUE THREAD

**Issue by luamas** [spring-cloud/spring-cloud-stream#2283]
spring.cloud.stream.kafka.default.producer.message-key-expression: headers['messageKey']

When you configure the default

Failed to bind properties under 'spring.cloud.stream.kafka.default.producer.message-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.kafka.default.producer.message-key-expression
    Value: headers['messageKey']
    Origin: class path resource [application.yml] - 11:37
    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

**Comment by luamas** [comment]
version 3.2.1

**Comment by olegz** [comment]
It appears to be some type of miss-configuration. The converter is registered with core. Are you saying it worked with previous versions?

**Comment by olegz** [comment]
That is not what i asked you

**Comment by luamas** [comment]
This is a new application, configured in the default way.  Otherwise, 'message-key-expression' needs to be configured separately for each one.

**Comment by luamas** [comment]
I'm starting to see what you mean.  Spring Boot core bind has an error.  

The following code

private <T> Object bindObject(ConfigurationPropertyName name, Bindable<T> target, BindHandler handler,
			Context context, boolean allowRecursiveBinding) {
		ConfigurationProperty property = findProperty(name, target, context);
		if (property == null && context.depth != 0 && containsNoDescendantOf(context.getSources(), name)) {
			return null;
		}
		AggregateBinder<?> aggregateBinder = getAggregateBinder(target, context);
		if (aggregateBinder != null) {
			return bindAggregate(name, target, handler, context, aggregateBinder);
		}
		if (property != null) {
			try {
				return bindProperty(target, context, property);
			}
			catch (ConverterNotFoundException ex) {
				// We might still be able to bind it using the recursive binders
				Object instance = bindDataObject(name, target, handler, context, allowRecursiveBinding);
				if (instance != null) {
					return instance;
				}
				throw ex;
			}
		}
		return bindDataObject(name, target, handler, context, allowRecursiveBinding);
	}

**Comment by luamas** [comment]
link https://github.com/spring-projects/spring-integration/issues/3726

**Comment by luamas** [comment]
@olegz 

spring cloud 2020.0.0 
spring boot 2.6.3

This time it is a default configuration  

org.springframework.cloud.stream.config.BindingServiceProperties


`
private void bindToDefault(String binding) {
		BindingProperties bindingPropertiesTarget = new BindingProperties();
		Binder binder = new Binder(
				ConfigurationPropertySources
						.get(this.applicationContext.getEnvironment()),
				new PropertySourcesPlaceholdersResolver(
						this.applicationContext.getEnvironment()),
				IntegrationUtils.getConversionService(
						this.applicationContext.getBeanFactory()),
				null);
		binder.bind("spring.cloud.stream.default",
				Bindable.ofInstance(bindingPropertiesTarget));
		this.bindings.put(binding, bindingPropertiesTarget);
	}
`

The `IntegrationUtils.getConversionService(this.applicationContext.getBeanFactory())` method does not get SpelConverter .

`
@Bean
	@ConfigurationPropertiesBinding
	@IntegrationConverter
	public Converter<String, Expression> spelConverter() {
		return new SpelConverter();
	}
`

**Comment by olegz** [comment]
You don't need to register Spel converter, it is already registered by the framework

**Comment by olegz** [comment]
Any updates on this? Perhaps a reproducible sample?

**Comment by luamas** [comment]
However, the converter does not exist after debugging, so you can try it out

**Comment by luamas** [comment]
`spring.cloud.stream.kafka.default.producer.message-key-expression` is in need of this converter

**Comment by iguissouma** [comment]
I'm having similar issue in a project with multi binder while I'm trying to upgrade to upgrade to latest versions
spring-boot: 2.6.5
spring-cloud: 2021.0.1

```
        my-kafka:
          type: kafka
          inheritEnvironment: true
          environment:
            spring.cloud.stream:
              kafka:
                default:
                  producer:
                    messageKeyExpression: headers['messageKey']
                    headerPatterns: ta*
                binder:
                  producer-properties:
                    key.serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
                    value.serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
```

and it seems a default conf like this is not working has no effect:

```
spring.cloud.stream:
      kafka:
        default:
          consumer:
            autoCommitOffset: false
          producer-properties:
            messageKeyExpression: headers['messageKey']
            headerPatterns: ta*

**Comment by luamas** [comment]
@iguissouma Don't use the default variable for now, The default variable is faulty

**Comment by iguissouma** [comment]
I can't figured why the 'message-key-expression'  configured separately for each one stop working too, I have null key.
I noticed when we don specify environment property the default property is properly taken and it works as expected but it's not a solution.

```
spring:
  application:
    name: "spring-cloud-stream-multibinder"
  cloud:
    stream:
      bindings:
        input:
          destination: test1
          binder: kafka1
        output:
          destination: test2
          binder: kafka1

      binders:
        kafka1:
          type: kafka
        kafka2:
          type: kafka
      kafka:
        default:
          producer:
            messageKeyExpression: headers['myKey']
```
