### ISSUE TITLE
One of Mutliple Functions does not Listen

### ISSUE THREAD

**Issue by sidsamant** [spring-cloud/spring-cloud-stream#2368]
**Describe the issue**

I have 5 functions with the last one being a Consumer. All other 4 functions output to a common topic but their input topics are different.

```
spring:
  cloud:
    function:
        definition: function1;function2;function3;function4;function5
    stream:      
      bindings:
        function1-in-0:
          destination: function1-topic
          content-type: application/*+avro
          group: somegroup
          consumer:
            concurrency: 3
        function1-out-0:
          destination: common-topic-out
          content-type: application/*+avro
          producer:
            use-native-encoding: true
        function2-in-0:
          destination: function2-topic
          content-type: application/*+avro
          group: somegroup
          consumer:
            concurrency: 3
        function2-out-0:
          destination: common-topic-out
          content-type: application/*+avro
          producer:
            use-native-encoding: true
        function3-in-0:
          destination: function3-topic
          content-type: application/*+avro
          group: somegroup
          consumer:
            concurrency: 3
        function3-out-0:
          destination: common-topic-out
          content-type: application/*+avro
          producer:
            use-native-encoding: true
        function4-in-0:
          destination: function4-topic
          content-type: application/*+avro
          group: somegroup
          consumer:
            concurrency: 3
        function4-out-0:
          destination: common-topic-out
          content-type: application/*+avro
          producer:
            use-native-encoding: true
        function5-in-0:
          destination: function5
          content-type: application/*+avro
          group: somegroup
          consumer:
            concurrency: 3
```
 At times the first function does not process/listen. If I remove the other functions in the config, then it listens. When I restore it works fine. Then again after a few days, it stops listening. 

**To Reproduce**
Sorry could not reproduce.  The moment I tinker with it, it start working and then after a few days its back. Need guidance.

**Version of the framework** 
spring-cloud-stream@3.2.2, spring-cloud-stream-binder-kafka@3.2.2

**Expected behavior**
It should listen to all the configured functions all the time.
**Screenshots**

**Additional context**
