### ISSUE TITLE
Use custom deserializer for consumer instead of ByteArrayDeserializer

### ISSUE THREAD

**Issue by kgeneral** [spring-cloud/spring-cloud-stream#2388]
Hi.

I'm looking for the option for use custom deserializer for consumer instead of ByteArrayDeserializer

```
2022-05-11 21:26:29.231  INFO 43843 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	allow.auto.create.topics = false
	auto.commit.interval.ms = 5000
...
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
```

I found out this option from manual :

> use-native-decoding: true

```
spring:
  cloud:
    stream:
      bindings:
        bindingname:
          destination: topicname
          consumer:
            use-native-decoding: true
      kafka:
        bindings:
          bindingname:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer

```

But it didn't made change for key.deserializer option.

So I checked some code for kafka consumer init.
But I can't found any code about checking condition for use-native-decoding 
and bind custom deserializer. (for this time)

```
// ConsumerConfig.java
    protected static Map<String, Object> appendDeserializerToConfig(Map<String, Object> configs,
                                                                    Deserializer<?> keyDeserializer,
                                                                    Deserializer<?> valueDeserializer) {
        Map<String, Object> newConfigs = new HashMap<>(configs);
        if (keyDeserializer != null)
            newConfigs.put(KEY_DESERIALIZER_CLASS_CONFIG, keyDeserializer.getClass());
        if (valueDeserializer != null)
            newConfigs.put(VALUE_DESERIALIZER_CLASS_CONFIG, valueDeserializer.getClass());
        return newConfigs;
    }

// SteamThread.java : ByteArrayDeserializer looks hard-coded into it.

private static final class InternalConsumerConfig extends ConsumerConfig {
        private InternalConsumerConfig(final Map<String, Object> props) {
            super(ConsumerConfig.appendDeserializerToConfig(props, new ByteArrayDeserializer(),
                    new ByteArrayDeserializer()), false);
        }
    }
```

Please let me know how.
