### ISSUE TITLE
Two BinderConfigurationPropertiesBeans are created

### ISSUE THREAD

**Issue by zhaozhiguang** [spring-cloud/spring-cloud-stream#2389]
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/879

There seems to be a similar problem in my previous 3.2

error:
Parameter 0 of method jaasInitializer in org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsJaasConfiguration required a single bean, but 2 were found:
	- binderConfigurationProperties: defined by method 'binderConfigurationProperties' in class path resource [org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderSupportAutoConfiguration.class]
	- myKafkaStream-KafkaStreamsBinderConfigurationProperties: a programmatically registered singleton

**my config**
```yml
spring:
  kafka:
    bootstrap-servers:
      - xx:9092
      - xx:9093
      - xx:9092
  cloud:
    stream:
      kafka:
        streams:
          bindings:
            process-in-0:
              consumer:
                application-id: myKafkaStreamApp
                native-decoding: true 
          binder:
            deserialization-exception-handler: logAndContinue 
            state-store-retry: 
              max-attempts: 1 
              backoff-period: 1000 
            configuration:
              num.stream.threads: 8 
      function:
        definition: process 
      binders:
        myKafkaStream:
          type: kstream
      bindings:
        process-in-0: 
          destination: newTopic10 
          content-type: text/plain
          group: myStream
          binder: myKafkaStream
```
```xml
<properties>
        <java.version>11</java.version>
        <spring-cloud.version>2021.0.1</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
            <scope>test</scope>
            <classifier>test-binder</classifier>
            <type>test-jar</type>
        </dependency>
    </dependencies>
```

**my code**
```java
@Bean
public Consumer<KStream<Object, String>> process() {
    return input ->
            input.foreach((key, value) -> {
                System.out.println("Key: " + key + " Value: " + value);
            });
}
```
