### ISSUE TITLE
spring function don't work fine with spring integration

### ISSUE THREAD

**Issue by Xtreme-Light** [spring-cloud/spring-cloud-stream#2439]
**spring function don't work fine with spring integration**
In my case.I am use spring cloud stream , then I am try to use spring integration with java dsl.First time，I use a consumer bean to do all things that I need to do.
when I  got Spring Integration, I do a refactor by use the old consumer bean to send message by MessageGateway.
Then I realized，why I needed this consumer bean? so I had a try to just use IntegrationFlow to accept message from a messageChannel that also defined with spring cloud stream.
yes,It worked succes in my demo.but I found it don't work fine wit spring-cloud-bus. with the more test。I founded that，It just work fine without spring function beans。 I had try to find some thing about this in Stack Overflow,But not found.so,i think，it is a issue.

**my core config**
```yaml
spring:
  cloud:
    stream:
      input-bindings: amqpMessage
      bindings:
#        amqpMessage-in-0:
        AMQP_MESSAGE_INPUT:
          destination: AMQP_DESTINATION
          group: AMQP_INPUT
        AMQP_MESSAGE_OUTPUT:
          destination: AMQP_DESTINATION
      function:
        bindings:
          amqpMessage-in-0: AMQP_MESSAGE_INPUT
          amqpMessage-out-0: AMQP_MESSAGE_OUTPUT
      output-bindings: amqpMessage
      rabbit:
        bindings:
          AMQP_MESSAGE_OUTPUT:
            producer:
              routing-key-expression: ''''''

```
my integrationflow:

```java
  @Bean
  public IntegrationFlow directFlow(
      SimpleEchoServiceActivator simpleEchoServiceActivator
  ) {
    return IntegrationFlows
        .from("AMQP_MESSAGE_INPUT")
        .handle(simpleEchoServiceActivator)
        .log().get();
  }
@MessageEndpoint
@Slf4j
public class SimpleEchoServiceActivator {

  @ServiceActivator
  public void handle(Cargo messages) {
    log.info("accept {}", messages);
  }
}

```
when I declare a consumer like this,even don't do any config in yaml.my integration flow defined before,just don't work. so,same way,do not work fine with spring cloud bus,because of springCloudBusInput consumer.
```java
  @Bean
  public Consumer<String> temp() {
    return v -> log.info("============{}", v);
  }
```
also ,I checked queue in rabbit mq. when i add this bean,the queue's message won't be consumed. 

**Version of the framework**
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.7.0</version>
    <relativePath/> 
  </parent>
    <spring-cloud.version>2021.0.3</spring-cloud.version>
