### ISSUE TITLE
Header contentType propagated in response message when using useNativeEncoding=true

### ISSUE THREAD

**Issue by metalpalo** [spring-cloud/spring-cloud-stream#2451]
HI,

My configuration is following:

- Spring Boot version: 2.6.3

- Spring Cloud Dependencies version: 2021.0.1

- Confluent Kafka Library(kafka-avro-serializer): 7.1.1

My application reads JSON data from input topic 'UpdateRequests' and push avro message **UpdateResponse** to output topic 'UpdateResponses'.
It is implemented via spring cloud function like this example:
```
@Bean
    public Function<UpdateRequest, UpdateResponse> processUpdate() {
        return request -> UpdateResponse.newBuilder()
                .setOperation(Operation.UPDATE)
                .build();
    }
```

Both consumer and producer have enabled **useNativeEncoding** to true and it seems that everything works. 

1. I send json to input topic with only one native header necessary for JsonDeserializer:  "__TypeId__=com.example.UpdateRequest"
2. UpdateResponse avro message sent to output topic successfully, schema also registered

But in produced message I see native contentType header **application/json** from legacy setting **spring.cloud.stream.bindings.input.content-type**
When I removed this setting, default content type setting is used instead: **spring.cloud.stream.default.content-type**.  
But output content type  **spring.cloud.stream.bindings.output.content-type** is not taken into account.

What can be wrong with configuration or why contentType is propagated there?

Here is my setting:
```
spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      properties:
        max.poll.records: 1
  cloud:
    function:
      definition: processUpdate
    stream:
      schema:
        avro:
          dynamic-schema-generation-enabled: false
      default:
        content-type: application/*+avro
        group: ${spring.cloud.stream.bindings.input.group:LH_Updater}
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
          max-attempts: 1
      bindings:
        input:
          destination: UpdateRequests
          content-type: application/json
        output:
          destination: UpdateResponses
          content-type: application/*+avro
      function:
        bindings:
          processUpdate-in-0: input
          processUpdate-out-0: output
      kafka:
        binder:
          brokers: ${KAFKA_URL}
          auto-create-topics: false
          consumer-properties:
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: ${SCHEMA_REGISTRY_URL}
        bindings:
          input:
            consumer:
              auto-commit-on-error: true
              configuration:
                spring:
                  deserializer:
                    key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                    value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                  json:
                    trusted.packages: '*'
```

**Comment by sobychacko** [comment]
@metalpalo Spring Cloud Schema Registry is now deprecated and is already disconnected from Spring Cloud Stream. We recommend not using that at this point with Spring Cloud Stream. We suggest you use Confluent Schema Registry for Kafka-based applications. It seems like that is what you are doing because I see the property, `schema.registry.url`.  I suppose that is the Confluent Schema Registry. No need to provide `dynamic-schema-generation-enabled`. It has no effect when using Confluent's SR. That is a legacy property from the Spring Cloud Schema Registry. So it seems like you are mixing the two. You might want to clean that up first. When using native encoding/decoding, Spring Cloud Stream does not do any conversion and the property `contentType` is not relevant at all since all serialization is done natively in the Kafka client. Thus, you don't need to set any `contentType`.  If your goal is to propagate an arbitrary content-type property downstream, then you may want to rely on other methods. 

After cleaning up your configuration based on these suggestions, if you are still encountering issues, please feel free to provide us with a minimally reproducible sample. That way we can triage it further.

**Comment by sobychacko** [comment]
@metalpalo Any updates on this issue?

**Comment by metalpalo** [comment]
@sobychacko I dont use obsolete Spring Cloud Schema Registry now(nothing on classpath). It comming from history, so I will remove them from my config. I will use confluent registry with kafka native avro serialization/deserialization library later. 


But probably I have some problem with my config for json processing somewhere.
What I found out that my actuator/health is down with
```
{
  "status": "DOWN",
  "components": {
    "binders": {
      "status": "DOWN",
      "components": {
        "kafka": {
          "status": "DOWN",
          "details": {
            "error": "org.apache.kafka.common.KafkaException: Failed to construct kafka consumer",
            "listenerContainers": [
              {
                "isPaused": false,
                "listenerId": "KafkaConsumerDestination{consumerDestinationName='UpdateRequests', partitions=0, dlqName='null'}.container",
                "isRunning": true,
                "groupId": "LH_Updater",
                "isStoppedAbnormally": false
              }
            ]
          }
        }
      }
    }
  }
}
```

and logs are filled with chunks each minute like: 
```
[pool-3-thread-1] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
[pool-3-thread-1] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
[pool-3-thread-1] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
```

But everything seem works fine: 
reading, sending ok, ErrorHandlingDeserializer used together with delegates StringDeserializer, JsonDeserializer

My config is following(consumer deserializers are defined via **spring.cloud.stream.kafka.binder.consumer-properties** and **spring.cloud.stream.kafka.bindings.input.consumer.configuration**) :

```
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: ${project.parent.artifactId}
    description: ${project.description}
    index: ${random.uuid}
  config:
    import: configserver:${CONFIG_SERVER_URL}
  sleuth:
    function.enabled: false
    integration.enanbed: true
    sampler.probability: 1.0
#  kafka:
#    consumer:
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          deserializer:
#            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#            value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#          json:
#            trusted.packages: '*'
  cloud:
    config:
      fail-fast: true
    function:
      definition: processUpdate
    stream:
      default:
        content-type: application/json
        group: ${spring.cloud.stream.bindings.input.group:LH_Updater}
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
          max-attempts: 1
      bindings:
        input:
          destination: UpdateRequests
          content-type: application/json
        output:
          destination: UpdateResponses
          content-type: application/json
      function:
        bindings:
          processUpdate-in-0: input
          processUpdate-out-0: output
      kafka:
        binder:
          brokers: ${KAFKA_URL}
          auto-create-topics: true
          consumer-properties:
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        bindings:
          input:
            consumer:
              configuration:
                spring:
                  deserializer:
                    key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                    value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                  json:
                    trusted.packages: '*'

```

but when I move setting under spring.kafka.consumer like this, health check works fine.
```
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: ${project.parent.artifactId}
    description: ${project.description}
    index: ${random.uuid}
  config:
    import: configserver:${CONFIG_SERVER_URL}
  sleuth:
    function.enabled: false
    integration.enanbed: true
    sampler.probability: 1.0
  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted.packages: '*'
  cloud:
    config:
      fail-fast: true
    function:
      definition: processUpdate
    stream:
      default:
        content-type: application/json
        group: ${spring.cloud.stream.bindings.input.group:LH_Updater}
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
          max-attempts: 1
      bindings:
        input:
          destination: UpdateRequests
          content-type: application/json
        output:
          destination: UpdateResponses
          content-type: application/json
      function:
        bindings:
          processUpdate-in-0: input
          processUpdate-out-0: output
      kafka:
        binder:
          brokers: ${KAFKA_URL}
          auto-create-topics: true
#          consumer-properties:
#            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
#        bindings:
#          input:
#            consumer:
#              configuration:
#                spring:
#                  deserializer:
#                    key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#                    value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#                  json:
#                    trusted.packages: '*'
```


further I replaced ErrorHandlingDeserializer in consumer-properties with simple deserializers  StringDeserializer, JsonDeserializer and health check also works.
