### ISSUE TITLE
The @ServiceActivator(inputChannel = "[topic].[group]. Errors ") annotation Is there an unresolvable Circular reference exception

### ISSUE THREAD

**Issue by lijun4311** [spring-cloud/spring-cloud-stream#2479]
describe: 

hello
An exception occurred while using a channel that handles local exceptions,But it works fine

   ```java
      @ServiceActivator(inputChannel = "force-logout-topic.force-logout-group.errors")
      public void handleError(ErrorMessage message) {
        log.info("原始消息体 = {}", message);
     }
  ```

```java
Could not register an MBean for: forceLogoutTopic.handleError.serviceActivator  org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'forceLogoutTopic.handleError.serviceActivator': Requested bean is currently in creation: Is there an unresolvable circular reference?
```
```java
2022-08-16 00:41:24,893 WARN  [force-logout-topic.force-logout-group-1,27c4d80edb2f6454,9142bcafd2fa2973] o.s.c.l.c.RoundRobinLoadBalancer.getInstanceResponse(98): No servers available for service: my-shop-auth-service  
2022-08-16 00:41:24,894 WARN  [force-logout-topic.force-logout-group-1,27c4d80edb2f6454,9142bcafd2fa2973] o.s.c.o.l.RetryableFeignBlockingLoadBalancerClient.lambda$execute$2(145): Service instance was not resolved, executing the original request  
```

```yml
spring:
  cloud:
    stream:
      function:
        definition: forceLogoutConsumer
      bindings:
        forceLogoutConsumer-in-0:
          destination: force-logout-topic
          group: force-logout-group
        forceLogoutProducer:
          destination: force-logout-topic
          producer:
            error-channel-enabled: true
```
