### ISSUE TITLE
Missing bindings on reconnect

### ISSUE THREAD

**Issue by mkluzacek** [spring-cloud/spring-cloud-stream#2483]
**Describe the issue**
When using multiple binding routing keys like:
```
spring:
  cloud:
    stream:
      bindings:
        tagCreatedTagDeleted-in-0:
          content-type: application/json
          destination: backend-events
          group: backend-events.tag-created-tag-deleted.v1
          consumer:
            max-attempts: 1
      rabbit:
        bindings:
          tagCreatedTagDeleted-in-0:
            consumer:
              exchangeType: topic
              queueNameGroupOnly: true
              bindingRoutingKey: TAG_CREATED;TAG_DELETED
              bindingRoutingKeyDelimiter: ';'
              acknowledgeMode: MANUAL
              prefetch: 100
    function:
      definition: tagCreatedTagDeleted
```
everything works fine starting the application and connecting to rabbit. But when you restart the rabbit and delete all of its data then on application reconnect the queue is created only with the first binding in this example the `TAG_CREATED`

**To Reproduce**
1. Start basic rabbitMQ application( I used spring initializer with basic rabbitMQ config and application.yml from above)
2. Restart rabbitMQ together with deleting all of its data( i used docker image and deleted its volume + restart it)
3. Wait for the application to reconnect
4. The queue is recreated with only the first routing key

**Version of the framework**
Spring boot starter 2.7.2
Spring cloud stream 3.2.4
**Expected behavior**
The queue is recreated with all bindings. Not only the first one.
