### ISSUE TITLE
Routing events type (avro) to right Consumer from one topic in reactive programming.

### ISSUE THREAD

**Issue by alakhdarlmfr** [spring-cloud/spring-cloud-stream#2517]
I use 
spring-cloud-stream:3.2.2
spring-cloud-stream-binder-kafka:3.2.5
spring-cloud-stream-binder-kafka-streams:3.2.5

I want to write consumer kafka in reactive programming. I work with avro schema registry.
In my case i have multiple events type in one topic. My consumer consume all type, but i want to write one consumer per events type. 
In your documentation i found some information concerning Routing. In reactive mode i can use routing-expression in application.yml only. But it's not working for me. 
Can you help me ? I tried several things, but i don't find why it's not working. 
My 2 Consumer consume all events type not specific. 

My two consumer: 

    @Bean
    public Consumer<FirstRankPaymentAgreed> testAvroConsumer() {
	    return firstRankPaymentAgreed -> {
            log.error("test reception event {} ", firstRankPaymentAgreed.getState().getCustomerOrderId());
        };
    }

    @Bean
    public Consumer<CustomerOrderValidated> devNull() {
        return o -> {
            log.error("devNull ");
        };
    }

my application.yml ( i try lot of simple test)

```
spring
  cloud:
    stream:
      function:
        routing:
          enabled: true
        definition: testAvroConsumer;devNull
        #routing-expression: "'true'.equals('true') ? devNull : testAvroConsumer;" #"payload['type'] == 'CustomerOrderValidated' ? devNull : testAvroConsumer;"
      bindings:
        testAvroConsumer-in-0:
          destination: tempo-composer-event
        devNull-in-0:
          destination: tempo-composer-event
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
          consumer-properties:
            value:
              subject:
                name:
                  strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
    function:
      #routing-expression: "'true'.equals('true') ? devNull : testAvroConsumer;"
      #routing-expression: "payload['type'] == 'CustomerOrderValidated' ? devNull : testAvroConsumer;"
      definition: testAvroConsumer;devNull
```
