### ISSUE TITLE
Binder Kafka: unexpected consumer retries when max-attemps: 1 & enable-dlq: false

### ISSUE THREAD

**Issue by sergey-volkov-lm** [spring-cloud/spring-cloud-stream#2560]
**Describe the issue**
If error is thrown from listener function, there are 9 unexpected retries without delays, although I explicitly set `max-attempts: 1` in generic consumer configuration in yml. It's confusing, not covered in docs for max-attempts property.

**To Reproduce**
Message receiving class
```kotlin
@Service
class TestEventKafkaMessageReceiver {
    @Bean
    fun testEvent(): Consumer<String> {
        return Consumer { rawMessage ->
            throw RuntimeException("something happened with $rawMessage")
        }
    }
}
```

application.yml config
```yaml
spring:
  cloud:
    function:
      definition: testEvent
    stream:
      kafka:
        bindings:
          testEvent-in-0:
            consumer:
              ack-mode: RECORD
              enable-dlq: false
      bindings:
        testEvent-in-0:
          binder: my-kafka
          destination: test-topic
          group: test-group
          consumer:
            max-attempts: 1
            start-offset: latest
      binders:
        my-kafka:
          type: kafka
          environment:
            spring:
              kafka: 
                ### kafka cluster settings
```

**Version of the framework**
Spring Boot 2.7.5
Spring Cloud Dependencies 2021.0.5

**Expected behavior**
There is only one attempt to consume message, then listener commits offset and reads the next message.

**Additional context**
Linked Issues:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1135
https://github.com/spring-cloud/spring-cloud-stream/issues/2205

PR which reduced number of tries from 10 * max-attempts to max-attempts, _but not working for max-attempts=1_:  
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1136
