### ISSUE TITLE
Actuator's "channels" endpoint may not properly expose binding channel information

### ISSUE THREAD

**Issue by yoshikawaa** [spring-cloud/spring-cloud-stream#2612]
### versions
* Spring Boot: 2.7.6
* Spring Cloud: 2021.0.5

### Problem
```yml
management:
  endpoints:
    web:
      exposure:
        include:
          - health # (1)
          - health-path
          - bindings
          - channels # (2)
```

If I expose the endpoints that Spring Cloud Stream provides to Spring Boot Actuator via HTTP, there is a problem that exposing the "health" endpoint prevents the "channels" endpoint from retrieving binding channel information.

* If "health" is not exposed, "channels" exposes binding channel information normally.
* If "health" is exposed, "channels" exposes empty information.

### Cause
This is because if the "health" is exposed, the processing timing of the `BindableFunctionProxyFactory` will be delayed, and the `ChannelsEndpoint` will not be initialized in time.
