### ISSUE TITLE
Spring Cloud Stream Kafka Binder  health actuator with "destinationIsPattern" enabled  does not show health status "DOWN" when kafka cluster is no longer reachable

### ISSUE THREAD

**Issue by swissmalamute** [spring-cloud/spring-cloud-stream#2628]
The question concerns the health actuator of the Spring Cloud Stream Kafka Binder. When a regex is specified for a destination using "destination-is-pattern: true", the health actuator from Spring Cloud Stream Kafka Binder always reports the health status "UP", even if the Kafka cluster is no longer accessible.

To Reproduce:
1. Configure a destination with "destination-is-pattern: true"
2. Start the spring boot service
3. Watch the health status of the kafka binders
4. Shut down the kafka cluster
5. The health status of the binder remains "UP"

Version of the framework: 
spring-cloud-stream:3.2.6

Expected behavior: 
When the Kafka cluster is no longer reachable, the health state of the kafka binders should change to "DOWN", even if the destination is configured using regex and "destination-is-pattern: true".

Matching configuration:

```yaml
spring:
  cloud:
    stream:
      bindings:
        nFAConsumer-in-0:
          destination: .*eap-rep
          group: nfa-consumer-group
      kafka:
        binder:
          brokers: localhost:16106
          healthTimeout: 10
        bindings:
          nFAConsumer-in-0:
            consumer:
              destination-is-pattern: true
```
