### ISSUE TITLE
AdminClientConfig being invoked despite autoCreateTopics=false

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-stream#2651]
**Describe the issue**

AdminClientConfig being invoked despite autoCreateTopics=false

**To Reproduce**
Here is a very straightforward and minimal sample:

```
@SpringBootApplication
public class StreamReactiveConsumerApplication implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(StreamReactiveConsumerApplication.class);

    public static void main(String... args) {
        new SpringApplicationBuilder(StreamReactiveConsumerApplication.class).run(args);
    }

    @Override
    public void run(String... args) {
    }

    @Bean
    Function<Flux<String>, Flux<String>> consume() {
        return flux -> flux
                .flatMap(one -> myHandle(one) )
                .subscribe();
    }

    private Mono<String> myHandle(Message<String> one) {
        log.info("<==== look at this thread, it is always the same!" + "\u001B[32m" + one.getPayload() + "\u001B[0m");
        String payload = one.getPayload();
        return Mono.just(payload);
    }
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>streamreactiveconsumer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.2</version>
        <relativePath/>
    </parent>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2022.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

```
spring:
  kafka:
  application:
    name: stream-reactive-consumer
  cloud:
    stream:
      bindings:
        consume-in-0.destination: mycoolinput
        consume-out-0.destination: mycooloutput
        consume-in-0.group: mycoolgroup
      kafka:
        binder:
          autoCreateTopics: false
          brokers: mykafka.com:9092
          configuration:
            security:
              protocol: SSL
            ssl:
              keystore:
                location: /path/to/keystore.p12
                password: changeit
              truststore:
                location: /path/to/truststore.p12
                password: changeit


```

please note in the application.yml, there is a custom kafka host, as well as SSL enabled with keystore and truststore.

Issue 1, despite autoCreateTopics=false + consumer create topic = false, the topics are there already, AdminClientConfig is being invoked:

please look at timestamps:

```
2023-02-14 17:20:52 22788 INFO  --- [main] [stream-reactive-consumer,,] o.a.k.c.consumer.ConsumerConfig : ConsumerConfig values:
2023-02-14 17:20:54 22788 INFO  --- [main] [stream-reactive-consumer,,] o.a.k.c.consumer.ConsumerConfig : ConsumerConfig values:
2023-02-14 17:20:55 22788 INFO  --- [pool-1-thread-1] [stream-reactive-consumer,,] o.a.k.c.consumer.ConsumerConfig : ConsumerConfig values:
2023-02-14 17:21:05 22788 INFO  --- [KafkaConsumerDestination{consumerDestinationName='mycoolinput', partitions=0, dlqName='null'}.container-0-C-1] [stream-reactive-consumer,,] o.a.k.c.admin.AdminClientConfig : AdminClientConfig values:
bootstrap.servers = [mykafka.com:9092]
security.protocol = PLAINTEXT
ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
```

Issue2: while I strongly believe AdminClientConfig should not have been invoked in the first place, now that this is invoked, it is not taking into account the SSL properties + keystore and truststore.

**Version of the framework**
4.0.1 and 4.0.2-SNAPSHOT

**Expected behavior**

For issue 1, since there is no topic creation or any topic management, AdminClientConfig should not be called at all.
For issue 2, it is not picking any of the properties from
```
          configuration:
            security:
              protocol: SSL
            ssl:
              keystore:
                location: /path/to/keystore.p12
                password: changeit
              truststore:
                location: /path/to/truststore.p12
                password: changeit

```

Could you please help on this issue please?

Thank you

**Comment by sobychacko** [comment]
@patpatpat123 `KafkaTopicProvisioner` should not try to provision a topic if `spring.cloud.stream.kafka.binder.auto-create-topics` is set to `false`. This doesn't mean that the topic will not be created. When the binding ultimately creates the Kafka consumer, if the broker is enabled with auto topic creation, the Kafka consumer will still try to create the topic. I wonder if that is what you are seeing. The only guarantee the binder provisioner gives (if that property ^^ is set) is that it stays away from doing any topic maintenance chores. I tried your scenario on a simple non-reactive consumer, and set the property to false and I am seeing the right provisioner behavior, i.e. it is not trying to create the topic, and I am not seeing any admin client configs, but the consumer creates the topic anyways with a single partition. When I set the property to `true` (the default in the binder), and try your SSL configuration, I see the right values in the admin client config:

```
2023-02-15T10:35:09.920-05:00  INFO 94601 --- [           main] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values: 
......
......
        security.protocol = SSL
	ssl.keystore.location = /path/to/keystore.p12
	ssl.keystore.password = [hidden]
	ssl.truststore.location = /path/to/truststore.p12
	ssl.truststore.password = [hidden]
```

Of course, the app fails since I don't have any of these SSL paths sets properly. 

Here is the code/config I tried:

```
@Bean
public Consumer<String> consumer() {
    return s -> System.out.println("received");
}
```

config:

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          configuration:
            security:
              protocol: SSL
            ssl:
              keystore:
                location: /path/to/keystore.p12
                password: changeit
              truststore:
                location: /path/to/truststore.p12
                password: changeit
      bindings:
        consumer-in-0:
          destination: my-test-topic
```
