### ISSUE TITLE
Reactive kafka binder not commit offset

### ISSUE THREAD

**Issue by vavisha** [spring-cloud/spring-cloud-stream#2653]
Hello Spring Cloud Stream team.
I changed Apache Kafka Binder to Reactive Kafka Binder and consumer stopped committing offsets.

code:
```
package com.exanple;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;
import reactor.core.publisher.Flux;

import java.util.function.Function;

@SpringBootApplication
public class PingPongApplication {
    private static final Logger log = LoggerFactory.getLogger(PingPongApplication.class);

    public static void main(final String[] args) {
        SpringApplication.run(PingPongApplication.class, args);
    }

    @Bean
    public Function<Flux<Message<String>>, Flux<Message<String>>> pingPongStream() {
        return flux -> flux
                .doOnNext(s -> log.info("ping message {}", s.getPayload()))
                .map(message -> MessageBuilder.withPayload("pong").build())
                .doOnNext(s -> log.info("pong message {}", s));
    }
}
```

yml:
```
spring:
  application.name: ping-service
  cloud.stream:
    function.definition: pingPongStream
    default.producer.useNativeEncoding: true
    bindings:
      pingPongStream-in-0:
        destination: ping
        group: pin-server-group
      pingPongStream-out-0:
        destination: pong
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging.level.root: INFO
```

bulid.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
		<spring-cloud.version>2022.0.1</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka-reactive</artifactId>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Expected behavior**
Similar to spring-cloud-stream-binder-kafka, binder-kafka-reactive should commit offset after receive message
