### ISSUE TITLE
can not add custom header when message publish to DLQ by spring cloud stream Kafka binder

### ISSUE THREAD

**Issue by guanyingjie** [spring-cloud/spring-cloud-stream#2668]
**Describe the issue**
I try to add a custom header before message publish to dlq. but seems like this configuration is not work 

this is my configuration
```
spring:
  cloud:
    function:
      definition: numberConsumer
    stream:
      bindings:
        numberProducer-out-0:
          destination: first-topic
        numberConsumer-in-0:
          group: group
          destination: first-topic
      kafka:
        bindings:
          numberConsumer-in-0:
            consumer:
              standard-headers:
              enableDlq: true
              dlqName: dlq
              dlq-partitions: 1
```
this is my consumer,I let it throw a exception so that the message will enter dlq

```
  @Bean
  public Consumer<String> numberConsumer() {
    return message -> {
      log.info("receive message : {}", message);
      throw new NullPointerException();
    };
  }
```

and this is my implementation
```
@Configuration
@Slf4j
public class KafkaConfiguration {

  @Bean
  public ListenerContainerCustomizer<AbstractMessageListenerContainer<String, String>> customizer(DefaultErrorHandler errorHandler) {
    return (container, dest, group) -> {
      container.setCommonErrorHandler(errorHandler);
    };
  }

  @Bean
  public DefaultErrorHandler errorHandler(DeadLetterPublishingRecoverer deadLetterPublishingRecoverer) {
    return new DefaultErrorHandler(deadLetterPublishingRecoverer,new FixedBackOff(0,0));
  }

  @Bean
  public DeadLetterPublishingRecoverer publisher(KafkaOperations template) {
    DeadLetterPublishingRecoverer recover = new DeadLetterPublishingRecoverer(template);

    recover.setExceptionHeadersCreator((kafkaHeaders, exception, isKey, headerNames) -> {
      var exceptionType = getRootCauseExceptionType(exception);
      kafkaHeaders.add("exception-type", exceptionType.getBytes());
    });
    return recover;
  }

```

SpringBoot version 3.0.1
SpringCloud Version 2022.0.1
Spring Cloud Stream Kafka version 4.0.1

this the demo to produce the issue:
https://github.com/guanyingjie/spring-cloud-stream.git
