### ISSUE TITLE
Issue with exchange type reading from properties file

### ISSUE THREAD

**Issue by kartik-kaushik** [spring-cloud/spring-cloud-stream#2705]
Hi team,
Getting issue with the code described below:

    
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
      <version>4.0.3-SNAPSHOT</version>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-stream-binder-rabbit-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-stream</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-binder-rabbit-core</artifactId>
      <version>4.0.3-SNAPSHOT</version>
    </dependency>

    
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream</artifactId>
      <version>4.0.3-SNAPSHOT</version>
    </dependency>

we are using exchangeType fanout but it is always taking topic. But same properties are working fine in non-native app
```yaml
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          emailevent-out-0:
            producer:
              routingKeyExpression: '''events.in'''
              exchangeType: direct
              use-confirm-header: true
          audit-out-0:
            producer:
              exchangeType: fanout
              use-confirm-header: true
      default-binder: binder1
      binders:
        binder1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: virtual-host1
                host: localhost
                port: 5672
                username: guest
                password: guest
                ssl:
                  enabled: false
        binder2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: virtual-host2
                host: localhost
                port: 5672
                username: guest
                password: guest
                ssl:
                  enabled: false
      bindings:
        audit-out-0:
          producer:
            error-channel-enabled: true
          binder: binder1
          destination: domain.events
        emailevent-out-0:
          binder: binder2
          destination: domain.events2
```
error:
inequivalent arg 'type' for exchange 'domain.events' in vhost 'virtual-host1': received 'topic' but current is 'fanout'

Kindly help in resolution of the same.
