### ISSUE TITLE
Provide a Mechanism to Receive SenderResults

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2729]
The reactor-kafka binder currently has an undocumented feature of setting the `sendResult` header, containing a `Mono<RecordMetadata>`.

Change this to return `Mono<SenderResult>` instead - the record metadata is not very useful without the correlation metadata in the `SenderResult`.

https://stackoverflow.com/questions/76221809/how-to-get-correlation-id-in-spring-cloud-stream/76221941#76221941

**Comment by kitkars** [comment]
I was about to open this issue...You did already :)

To the original issue, The header approach sounds good. I can understand. But will it be ok for an extremely high throughput application?

```
@Bean
Supplier<Flux<Message<Integer>>> someProducer(){
	return () -> Flux.range(1, 10_000_000).map(i -> convertToMessage(i));
}
```
So, I was thinking, if we could send the results to a separate consumer as shown here?

```
@Bean
Consumer<Flux<SenderResult>> resultConsumer(){
	return flux -> flux.doOnNext(...).subscribe();
}
```

```
spring:
  cloud:
    function:
      definition: someProducer;
    stream:
      default-binder: reactorKafka
      bindings:
        producer-out-0:
          destination: order-events
          sendResultsTo: resultConsumer // function bean which accepts the result
```

sorry if it sounds ridiculous :)
