### ISSUE TITLE
org.springframework.cloud.stream.binding.BindingsLifecycleController no longer finds bindings

### ISSUE THREAD

**Issue by Impakt** [spring-cloud/spring-cloud-stream#2736]
Hello,
Since upgrading my spring cloud dependencies the BindingsLifecycleController no longer finds bindings. I noticed that between [4.0.1 and 4.0.2](https://github.com/spring-cloud/spring-cloud-stream/commit/807f51f175ac2d943b4f4252fde5c318d51b920e) the methods to locate a binding now return a list. I updated my code to suit but my tests that use the `queryState` method now have lists that are empty. When i inspect the controller while debugging a test, the only binding there is `dynamicDestinationsBindable`

My spring cloud stream config is as follows:

```yaml
spring:
  cloud:
    stream:
      default.group: blah
      default.producer.useNativeEncoding: true
      default.consumer.useNativeDecoding: true
      function:
        definition: c64;amiga
      bindings:
        c64-in-0:
          destination: foo
          ds-topic: true
          ds-input-topic: true
        amiga-in-0:
          destination: bar
          ds-topic: true
          ds-input-topic: true
        tmpTopic-in-0:
          destination: tmp
        tmpTopic2-in-0:
          foo: bar
```

**Comment by sobychacko** [comment]
I have a simple consumer like this:
```
@Bean
public Consumer<String> hello() {
  return c -> System.out.println("hello " + c);
}
```
```
spring:
  cloud:
    stream:
      bindings:
        hello-in-0:
          destination: hello-my-topic
```

and when calling `bindingsLifecycleController.queryState("hello-in-0")`, I get the following.

![image](https://github.com/spring-cloud/spring-cloud-stream/assets/827682/c8bd8c1d-e67f-4041-8928-207405d1ab3b)

This is using `4.0.2`. Could you give more details or provide a small minimal sample app? What binder are you using?
