### ISSUE TITLE
[spring-cloud-starter-stream-rabbit] Spring Boot 3.X.X is not working

### ISSUE THREAD

**Issue by RaulGF92** [spring-cloud/spring-cloud-stream#2762]
**Describe the issue**
When made a clean project of spring-cloud-starter-stream-rabbit with Spring 3.1.0, is not autoStarting if you downgrade to low Spring version (2.XX) that error doesn't apperar

**To Reproduce**
1. Create a new Empty Spring project (3.1.0)
2. Configurated pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>es.raulgf92.poc.events</groupId>
	<artifactId>connect-streams</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>connect-streams</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
		<spring-cloud.version>2022.0.3</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
		  <groupId>org.springframework.cloud</groupId>
		  <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
		  <groupId>org.projectlombok</groupId>
		  <artifactId>lombok</artifactId>
		  <optional>true</optional>
		 </dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```
3. Configurated application.yaml

```
spring:
  cloud:
    stream:
      function:
        definition: pkslowSource;pkslowSink
      bindings:
        pkslowSource-out-0:
         destination: pkslow-topic
        pkslowSink-in-0:
          group: pkslow
          destination: pkslow-topic
      poller:
        fixed-delay: 500
  rabbitmq:
    host: 2.tcp.eu.ngrok.io
    port: 11620
    username: guest
    password: guest
```
4. Create beans

```
@SpringBootApplication
@Slf4j
public class ConnectStreamsApplication {

	public static void main(String[] args) {
		SpringApplication.run(ConnectStreamsApplication.class, args);
	}
	
	@Bean(autowireCandidate = true)
	public Supplier<String> pkslowSource() {
	  return () -> {
	    String message = "www.pkslow.com";
	    log.info("Sending value: " + message);
	    return message;
	  };
	}
	
	@Bean(autowireCandidate = true)
	public Consumer<String> pkslowSink() {
	  return message -> {
	    log.info("Received message " + message);
	  };
	}

}
```

6. Console not bootstrapping like we expected

![image](https://github.com/spring-cloud/spring-cloud-stream/assets/9384625/e018be4a-b113-4fe0-aa47-f35294848a34)

If we downgrade to old spring version, this project works without problems and connect with rabbitmq servers

**Comment by Egraveline** [comment]
Hello!

It looks like you aren't setting you bean definitions correctly based on this line:
`Multiple functional beans were found [pkslowSInk, pkslowSource],...`

I was able to run this locally by changing your application.yaml to properly set the definitions like this:

```
spring:
  cloud:
    function:
      definition: pkslowSource;pkslowSink
    stream:
      bindings:
        pkslowSource-out-0:
         destination: pkslow-topic
        pkslowSink-in-0:
          group: pkslow
          destination: pkslow-topic
      poller:
        fixed-delay: 500
  rabbitmq:
    host: 2.tcp.eu.ngrok.io
    port: 11620
    username: guest
    password: guest
```

specially moving the function out of the stream scope.

Hope that helps!
