### ISSUE TITLE
Key extractor does not get invoked consistently

### ISSUE THREAD

**Issue by ennishol** [spring-cloud/spring-cloud-stream#2770]
When a function generates a message and sets the `spring.cloud.stream.sendto.destination` header to dynamically select the destination topic, the defined key-extractor does not get invoked. The expected behavior is that the defined key extractor should be called consistently.

In the code below the custom key-extractor is called on messages from `generate` `Supplier`, but not for messages created by `UpperCase` function. The goal is to always store same messages on the same partition

```yaml
server:
  port: 8081
spring:
  cloud:
    function:
      definition: generate;upperCase;demoEven;demoOdd
    stream:
      bindings:

        generate-out-0:
          destination: demoinput
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16

        upperCase-in-0:
          destination: demoinput
          
        demoEven-out-0:
          destination: demoresult_even
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16
        demoOdd-out-0:
          destination: demoresult_odd
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16

      kafka:
        binder:
          auto-add-partitions: true
          min-partition-count: 16
```

```java
package com.example.scstdemo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.binder.PartitionKeyExtractorStrategy;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;

import java.util.List;
import java.util.Locale;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Function;
import java.util.function.Supplier;

@SpringBootApplication
public class CloudStreamDemoApplication {

	private static final List<String> NAMES = List.of(
			"Alice", "Bob", "Hugo", "Arthur", "Elon", "Maria", "Jesus",
			"Jazz", "Pop", "Bas", "Gas", "Blues", "Harry", "Mary", "Anna", "Diana", "Megan");

	public static void main(String[] args) {
		SpringApplication.run(CloudStreamDemoApplication.class, args);
	}

	@Bean
	public PartitionKeyExtractorStrategy demoKeyExtractor() {
		return message -> {
			Object payload = message.getPayload();
			if (payload instanceof String p) {
				System.out.println("key extractor key is " + p);
				return p;
			}
			System.out.println("key extractor payload class is " + payload.getClass());
			return payload;
		};
	}

	@Bean
	public Supplier<String> generate() {
		return () -> "name: " + NAMES.get(ThreadLocalRandom.current().nextInt(NAMES.size()));
	}

	@Bean
	public UpperCase upperCase() { return new UpperCase(); }

	public static class UpperCase implements Function<String, Message<String>> {

		@Override
		public Message<String> apply(String input) {
			boolean isEven = System.currentTimeMillis() % 2 == 0;
			return createMsg("demoresult_" + (isEven ? "even" : "odd"), input);
		}

		private Message<String> createMsg(String topic, String dto) {
			return MessageBuilder.withPayload(dto.toUpperCase(Locale.ROOT))
					.setHeader("spring.cloud.stream.sendto.destination", topic)
					.build();
		}
	}

}

```

**2022.0.3**

**Comment by sobychacko** [comment]
@ennishol Where are the `demoEven` and `demoOdd` functions defined? Can you set this up as a sample app and share the repository?

**Comment by ennishol** [comment]
@sobychacko both functions do not exist. In application.yaml we added just to make it possible to send out the messages to the desired topics/bindings.

The demo project is literally those 2 files. But here is the archive [demo.tar.gz](https://github.com/spring-cloud/spring-cloud-stream/files/12024694/demo.tar.gz)

**Comment by sobychacko** [comment]
@ennishol This issue has been addressed now. Please try it on the latest snapshots. You also need the following configuration updates to make it work.

```
spring:
  cloud:
    function:
      definition: generate;upperCase
    stream:
      bindings:
        generate-out-0:
          destination: demoinput
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16
        upperCase-in-0:
          destination: demoinput
          
        demoresult_even:
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16
        demoresult_odd:
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16
...
```
