### ISSUE TITLE
Key-extractor called twice with StreamBridge.send

### ISSUE THREAD

**Issue by ennishol** [spring-cloud/spring-cloud-stream#2771]
Wenn a message is sent out using StreamBridge.send the custom key extractor is called twice: one time with the expected payload and the second time with the `Message<byte[]>` payload, which is unexpected.

The expected behavior is that the key extractor should be invoked only once per message.

How to reproduce:
- start the application
- curl localhost:8080/trigger
- watch the console or use the debugger on demoKeyExtractor invocation

```yaml
spring:
  cloud:
    stream:
      bindings:
        generate-out-0:
          destination: demoinput
          producer:
            partition-key-extractor-name: demoKeyExtractor
            partition-count: 16
      kafka:
        binder:
          auto-add-partitions: true
          min-partition-count: 16
```
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.binder.PartitionKeyExtractorStrategy;
import org.springframework.cloud.stream.function.StreamBridge;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class CloudStreamDemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(CloudStreamDemoApplication.class, args);
	}

	@Bean
	public PartitionKeyExtractorStrategy demoKeyExtractor() {
		return message -> {
			Object payload = message.getPayload();
			if (payload instanceof String p) {
				System.out.println("key extractor key is " + p);
				return p;
			}
			System.out.println("key extractor payload class is " + payload.getClass());
			return payload;
		};
	}

	@RestController
	public static class Api {
		private final StreamBridge streamBridge;

		public Api(StreamBridge streamBridge) {this.streamBridge = streamBridge;}

		@GetMapping("/trigger")
		public void name() {
			streamBridge.send("generate-out-0", "Alice");
		}
	}

}

```
