### ISSUE TITLE
streamBridgeFunctionCache inside StreamBridge causing collisions if multiple producers have same content type but different useNativeEncoding flag

### ISSUE THREAD

**Issue by francocm** [spring-cloud/spring-cloud-stream#2783]
**Describe the issue**

`StreamBridge` has the following method:

```java
private synchronized FunctionInvocationWrapper getStreamBridgeFunction(String outputContentType, ProducerProperties producerProperties) {
  if (StringUtils.hasText(outputContentType) && this.streamBridgeFunctionCache.containsKey(outputContentType)) {
    return this.streamBridgeFunctionCache.get(outputContentType);
  }
  else {
    FunctionInvocationWrapper functionToInvoke = this.functionCatalog.lookup(STREAM_BRIDGE_FUNC_NAME, outputContentType.toString());
    this.streamBridgeFunctionCache.put(outputContentType, functionToInvoke);
    functionToInvoke.setSkipOutputConversion(producerProperties.isUseNativeEncoding());
    return functionToInvoke;
  }
}
```

As we can see, the `streamBridgeFunctionCache` maps the function based on `outputContentType`. However, the function is being mutated with:

```java
functionToInvoke.setSkipOutputConversion(producerProperties.isUseNativeEncoding());
```

This changes the `skipOutputConversion` state within `SimpleFunctionRegistry` for the function mapped to that specific `outputContentType`.

Due to this, if there are multiple producers, having the same content type, but different `use-native-encoding: true|false` values, this will corrupt the cache and cause some of the producers to no longer honour the `use-native-encoding` value.

**To Reproduce**

Add something along these lines to your `application.yml` file:

```yaml
spring:
  cloud:
    stream:
      kafka:
        binder:
          required-acks: all
          auto-create-topics: false
        bindings:
          myKafkaProducer-out-0:
            producer:
              message-key-expression: headers.partitionKey
              configuration:
                key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                value.serializer: "io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer"
                schema.registry.url: ${schema-registry-url}
                json.write.dates.iso8601: true
      bindings:
        myKinesisProducer:
          destination: foo-events
          binder: kinesis
          content-type: application/json
          group: ${spring.application.name}
          producer:
            header-mode: none
        myKafkaProducer-out-0:
          destination: baz.events
          binder: kafka
          content-type: application/json
          group: ${spring.application.name}
          producer:
            partition-key-expression: headers.partitionKey
            use-native-encoding: true
```

In the above, depending for which producer `streamBridge.send()` was invoked, the `use-native-encoding` will get cached, which would have the wrong value for a subsequent publish via the other producer.

**Version of the framework**

Tested locally on `3.2.8` however issue is still present in 4.0.4 (see [here](https://github.com/spring-cloud/spring-cloud-stream/blob/v4.0.4/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L190-L200)).

**Expected behavior**

If caching is going to be used, it should be mapped to the binder itself (its unique name?), rather than the content type.

Any fixes would be ideal to also be part of 3.2.x, and not only 4.x please.

**Temporary workaround**

What I noticed based on my tests locally (at least for Kafka together with the `KafkaJsonSchemaSerializer`), you can work around it, by sending a dummy content-type, unique for the producer you're publishing to.

This **only** applies to the publishes done to the producer that has `use-native-encoding: true`. This works because the actual serialisation is being offloaded to the producer.

For the `use-native-encoding: false` producers, keep calling `send()` normally.

Example:

```java
// this is a workaround and far from ideal!
// works only if the 'bindId' has use-native-encoding: true
// do not do this if use-native-encoding is false

public boolean publish(Object event) {
  return streamBridge.send("bindId", event, new MimeType("foo", "foo"));
}
```

---

Let me know if you need anything else from me. Happy to help.

Thanks!
