### ISSUE TITLE
Anonymous queue for SpringCloudBus is not created using spring.cloud.stream binding

### ISSUE THREAD

**Issue by sudhapublic** [spring-cloud/spring-cloud-stream#2795]
I have created rabbitmq binding for exchange 'event' using spring.could.stream.bindings as per below configuration.

The bindings for 'event' exchange is works fine, but the default anonymous queue for springCloudBus is missing(not created ).

If i remove the binding 'eventIn-in-0' from configuration, then the default anonymous queue created for springCloudBus. 

What am missing in the binding configuration? so that i get both queue 'internal.service.main' and anonymous queue will be created?
```
spring:
  cloud:
    function:
      definition: eventIn
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: someuser
                password: somepwd
                virtual-host: /
      bindings:
         #Event Consumer Stream Binding
        eventIn-in-0:
          destination: event
          group: internal.service.main
          consumer:
            max-attempts: 1
      rabbit:
        bindings:
          eventIn-in-0:
            consumer:
              # Consumer specific config
              republish-to-dlq: false
              exchangeType: topic
              binding-routing-key-delimiter: ','
              binding-routing-key: event.internal.service.test
              auto-bind-dlq: true
              transacted: true
              dlq-ttl: 5000            
```
