### ISSUE TITLE
Spring cloud stream KTable-KTable join Avro schema deserialization issue

### ISSUE THREAD

**Issue by sumati-kulkarni** [spring-cloud/spring-cloud-stream#2800]
Hi,
I am trying to execute Spring Cloud Stream KTable-KTable join with avro schema and getting deserialization issue. Please help!

I got the POC working with JSON (without schema) but now I'm trying with Avro with schema. Please find the configuration below.

Topic: avro_EMPLOYEE
```
{"ID":"e5","KID":5,"DEPTID":"d2","ENAME":"eee","CREATED_DATE":1694007604367,"MODIFIED_DATE":1694007604367}
{"ID":"e4","KID":4,"DEPTID":"d4","ENAME":"ddd","CREATED_DATE":1694007604361,"MODIFIED_DATE":1694007604361}
{"ID":"e3","KID":3,"DEPTID":"d3","ENAME":"ccc","CREATED_DATE":1694007604355,"MODIFIED_DATE":1694007604355}
{"ID":"e2","KID":2,"DEPTID":"d2","ENAME":"bbb","CREATED_DATE":1694007604348,"MODIFIED_DATE":1694007604348}
{"ID":"e1","KID":1,"DEPTID":"d1","ENAME":"aaa","CREATED_DATE":1694007604338,"MODIFIED_DATE":1694007604338}
```

Topic: avro_DEPARTMENT
```
{"ID":"d4","KID":4,"DNAME":{"string":"DeptD"},"CREATED_DATE":1694007604997,"MODIFIED_DATE":1694007604997}
{"ID":"d3","KID":3,"DNAME":{"string":"DeptC"},"CREATED_DATE":1694007604986,"MODIFIED_DATE":1694007604986}
{"ID":"d2","KID":2,"DNAME":{"string":"DeptB"},"CREATED_DATE":1694007604965,"MODIFIED_DATE":1694007604965}
{"ID":"d1","KID":1,"DNAME":{"string":"DeptA"},"CREATED_DATE":1694007604952,"MODIFIED_DATE":1694007604952}
```

Java Class
```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee1 {
    @JsonProperty("ID")
    private String id;
    @JsonProperty("KID")
    private int kid;
    @JsonProperty("DEPTID")
    private String deptId;
    @JsonProperty("ENAME")
    private String ename;
    @JsonProperty("CREATED_DATE")
    private Date createdDate;
    @JsonProperty("MODIFIED_DATE")
    private Date modifiedDate;
}
```

```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Department1 {
    @JsonProperty("ID")
    private String id;
    @JsonProperty("KID")
    private int kid;
    @JsonProperty("DNAME")
    private String dname;
    @JsonProperty("CREATED_DATE")
    private Date createdDate;
    @JsonProperty("MODIFIED_DATE")
    private Date modifiedDate;
}
```

YAML file
```
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: enrichEmployee
      bindings:
        enrichEmployee-in-0:
          destination: avro_EMPLOYEE
          contentType: application/*+avro
          consumer:
            use-native-decoding: false
        enrichEmployee-in-1:
          destination: avro_DEPARTMENT
          contentType: application/*+avro
          consumer:
            use-native-decoding: false
        enrichEmployee-out-0:
          destination: avro_RESULT
          contentType: application/*+avro
          producer:
            use-native-encoding: true
      kafka:
        streams:
          binder:
            brokers:
              - localhost:9092
            functions:
              enrichEmployee.applicationId: 175594_appid
            configuration:
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              state.dir: state-store
              acceptable.recovery.lag: 0
              schema.registry.url: http://localhost:8081
          bindings:
            enrichEmployee-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            enrichEmployee-in-1:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            enrichEmployee-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
                useNativeEncoding: true
        binder:
          configuration:
            heartbeat.interval.ms: 10000
            max.poll.records: 5000
```

Enrichment BiFunction Bean
```
	@Bean
	public BiFunction<KTable<String, Employee1>, KTable<String, Department1>, KTable<String, EnrichEmployee>> enrichEmployee() {

		return (leftSource, rightSource) -> leftSource.join(rightSource,
				Employee1::getDeptId,
				(emp, dept) -> {
					EnrichEmployee enrichEmployee = new EnrichEmployee();
					enrichEmployee.setEid(emp.getId());
					enrichEmployee.setDeptId(dept.getId());
					enrichEmployee.setEname(emp.getEname());
					enrichEmployee.setDname(dept.getDname());
                    enrichEmployee.setCreatedDate(new Date());
                    enrichEmployee.setModifiedDate(new Date());
					return enrichEmployee;
				}/* ValueJoiner */
		);
	}
```
	
Error
[File attached] 
[avro_log.log](https://github.com/spring-cloud/spring-cloud-stream/files/12544324/avro_log.log)

Topics created when I run this application,
175594_appid-avro_EMPLOYEE-STATE-STORE-0000000000-changelog
175594_appid-avro_DEPARTMENT-STATE-STORE-0000000003-changelog
175594_appid-KTABLE-FK-JOIN-SUBSCRIPTION-STATE-STORE-0000000010-changelog
175594_appid-KTABLE-FK-JOIN-SUBSCRIPTION-RESPONSE-0000000014-topic
175594_appid-KTABLE-FK-JOIN-SUBSCRIPTION-REGISTRATION-0000000006-topic
avro_RESULT

pom.xml
[File attached]
[AvroKafkaCloudStreamIssue.txt](https://github.com/spring-cloud/spring-cloud-stream/files/12544326/AvroKafkaCloudStreamIssue.txt)

I also tried this join using the following avro generated classes. After using these Avro generated classes, I am not able to code the BiFunction join.

```
@org.apache.avro.specific.AvroGenerated
public class Department extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
....
}
```

generated from,

```
department-schema.avsc
{
  "connect.name": "DEPARTMENT",
  "namespace": "com.citi.schema",
  "fields": [
    {
      "name": "ID",
      "type": "string"
    },
    {
      "name": "KID",
      "type": "long"
    },
    {
      "default": null,
      "name": "DNAME",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "CREATED_DATE",
      "type": {
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "connect.version": 1,
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "name": "MODIFIED_DATE",
      "type": {
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "connect.version": 1,
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    }
  ],
  "name": "Department",
  "type": "record"
}
```

```
@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
...
}
```

generated from,

```
employee-schema.avsc
{
  "connect.name": "EMPLOYEE",
  "namespace": "com.citi.schema",
  "fields": [
    {
      "name": "ID",
      "type": "string"
    },
    {
      "name": "KID",
      "type": "long"
    },
    {
      "name": "DEPTID",
      "type": "string"
    },
    {
      "name": "ENAME",
      "type": "string"
    },
    {
      "name": "CREATED_DATE",
      "type": {
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "connect.version": 1,
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "name": "MODIFIED_DATE",
      "type": {
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "connect.version": 1,
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    }
  ],
  "name": "Employee",
  "type": "record"
}
```

**Comment by sobychacko** [comment]
@sumati-kulkarni Could you create this as a small sample application and put it somewhere on GH? We can then take it and run on our end to figure out what's going on.

**Comment by sumati-kulkarni** [comment]
Hi @sobychacko,

Please find the GH repo here,

https://github.com/sumati-kulkarni/spring-could-stream-avro

Kindly let me know if you need any further information.

Thanks,
Sumati

**Comment by sobychacko** [comment]
It is hard for us to run this application since it involves external database setup and other things. I think you can reproduce the issue without involving any external dependencies. However, before going this route, why don't you try a few things? 
First of all, I cleaned up your config as below (in Kafka Streams binder, using native decoding and encoding are the default and the recommended way).

```spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: enrichEmployee
      bindings:
        enrichEmployee-in-0:
          destination: avro_EMPLOYEE
        enrichEmployee-in-1:
          destination: avro_DEPARTMENT
        enrichEmployee-out-0:
          destination: avro_RESULT
      kafka:
        streams:
          binder:
            brokers:
              - localhost:9092
            functions:
              enrichEmployee.applicationId: 175594_appid
            configuration:
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              state.dir: state-store
              acceptable.recovery.lag: 0
              schema.registry.url: http://localhost:8081
          bindings:
            enrichEmployee-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            enrichEmployee-in-1:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            enrichEmployee-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
        binder:
          configuration:
            heartbeat.interval.ms: 10000
            max.poll.records: 5000
```

I think the core of your issue is with the following call not providing explicit Serdes..

```
leftSource.join(rightSource,
				Employee1::getDeptId,
				(emp, dept) -> {
					EnrichEmployee enrichEmployee = new EnrichEmployee();
					enrichEmployee.setEid(emp.getId());
					enrichEmployee.setDeptId(dept.getId());
					enrichEmployee.setEname(emp.getEname());
					enrichEmployee.setDname(dept.getDname());
                    enrichEmployee.setCreatedDate(new Date());
                    enrichEmployee.setModifiedDate(new Date());
					return enrichEmployee;
				}/* ValueJoiner */
		)
```

You need to call the proper overloaded `join` method that takes the right Serdes. For e.g. this one: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java#L1335

You can use one of the static methods from the `Materialized` class to provide the proper key/value Serdes. Here is how it may look like (in pseudo-code).

```
leftSource.join(rightSource,
				Employee1::getDeptId,
				(emp, dept) -> {
					EnrichEmployee enrichEmployee = new EnrichEmployee();
					enrichEmployee.setEid(emp.getId());
					enrichEmployee.setDeptId(dept.getId());
					enrichEmployee.setEname(emp.getEname());
					enrichEmployee.setDname(dept.getDname());
                    enrichEmployee.setCreatedDate(new Date());
                    enrichEmployee.setModifiedDate(new Date());
					return enrichEmployee;
				}/* ValueJoiner */,
                  Materialized.with(key serde, value serde)
		)
```

**Comment by sobychacko** [comment]
It is hard to run this sample because of the external database dependencies. I think you can reproduce the issue, though, without involving any external dependencies. However, why don't we try a few things first? I cleaned up your configuration as below (in Kafka Streams binder, using native decoding/encoding is the default and recommended).

```
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: enrichEmployee
      bindings:
        enrichEmployee-in-0:
          destination: avro_EMPLOYEE
        enrichEmployee-in-1:
          destination: avro_DEPARTMENT
        enrichEmployee-out-0:
          destination: avro_RESULT
      kafka:
        streams:
          binder:
            brokers:
              - localhost:9092
            functions:
              enrichEmployee.applicationId: 175594_appid
            configuration:
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              state.dir: state-store
              acceptable.recovery.lag: 0
              schema.registry.url: http://localhost:8081
          bindings:
            enrichEmployee-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            enrichEmployee-in-1:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
            enrichEmployee-out-0:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                configuration:
                  specific.avro.reader: true
        binder:
          configuration:
            heartbeat.interval.ms: 10000
            max.poll.records: 5000
```

I think the reason why you are getting the CCE is because of your `join` call. You need to use the proper overloaded `join` method that takes the right key/value Serdes. Here is a candidate: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java#L1335
You can use one of the static methods from the `Materialized` class. Here is a pseudo code:

```
leftSource.join(rightSource,
				Employee1::getDeptId,
				(emp, dept) -> {
					EnrichEmployee enrichEmployee = new EnrichEmployee();
					enrichEmployee.setEid(emp.getId());
					enrichEmployee.setDeptId(dept.getId());
					enrichEmployee.setEname(emp.getEname());
					enrichEmployee.setDname(dept.getDname());
                    enrichEmployee.setCreatedDate(new Date());
                    enrichEmployee.setModifiedDate(new Date());
					return enrichEmployee;
				}/* ValueJoiner */
                             Materialized.with(key serde, value serde)
		);
```

Make those changes and see how they go.

**Comment by sobychacko** [comment]
@sumati-kulkarni, Any updates on this issue?

**Comment by sumati-kulkarni** [comment]
Hi @sobychacko,

Sorry for late response. I added producers and removed external database dependencies. Please refer the updated [README.md](https://github.com/sumati-kulkarni/spring-could-stream-avro/blob/main/README.md) file to run the join.

After changing the classes to Avro generated classes (EMPLOYEE and DEPARTMENT), the foreign key KTable-KTable join is not working.

<
@Bean
	public BiFunction<KTable<String, EMPLOYEE>, KTable<String, DEPARTMENT>, KTable<String, RESULT>> enrichEmployee() {

		return (leftSource, rightSource) -> leftSource.**join**(rightSource,
				**EMPLOYEE::getDEPTID,**
				(emp, dept) -> {
					RESULT result = new RESULT();
					result.setID(emp.getID());
					result.setDEPTID(dept.getID());
					result.setENAME(emp.getENAME());
					result.setDNAME(dept.getDNAME());
                    result.setCREATEDDATE(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant());
                    result.setMODIFIEDDATE(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant());
					return result;
				},
				**Materialized.with(Serdes.String(), new JsonSerde<>(RESULT.class))/* ValueJoiner */**
		);
	}
>

I have updated the application.yml file and added the Materialized as you suggested. 

Appreciated your help! Thank you.
Sumati

**Comment by sumati-kulkarni** [comment]
Thanks for pointing that out. I would like to use Confluent Schema Registry. I tried fixing it referring to [your example](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/confluent-schema-registry-integration). I am still facing the same issue with the join. Please help.
 
Thanks,
Sumati

**Comment by sobychacko** [comment]
Try these changes in your project:

**produce-employee**

`application.yml`

```
server.port: 8078
spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          destination: test_EMPLOYEE
          producer:
            useNativeEncoding: true
      kafka:
        bindings:
          supplier-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081
```

From the maven configuration (`pom.xml`) of this project, you can remove the following 3 dependencies:

```
spring-cloud-stream-binder-kafka-streams
spring-cloud-schema-registry-client
kafka-streams-avro-serde
```

**produce-department**

`application.yml`

```
server.port: 8079
spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          destination: test_DEPARTMENT
          producer:
            useNativeEncoding: true
      kafka:
        bindings:
          supplier-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081
```

From the maven configuration (`pom.xml`) of this project, you can remove the following 3 dependencies:

```
spring-cloud-stream-binder-kafka-streams
spring-cloud-schema-registry-client
kafka-streams-avro-serde
```

**One thing to keep in mind is that to join the records, you need to use the same keys on both records (employee and department)**.
Therefore, when producing the department, use the following. 

```
Message<DEPARTMENT> message = MessageBuilder.withPayload(d)
                    .setHeader("kafka_messageKey", "e" + (i + 1))
                    .build();
```

The `kafka_messageKey` is equal to the same message key of the employee. 

**emp-enrichment-avro**

I modified your `BiFunction` as below for easier debugging. Please take note of all the code changes, such as the `Serde` used and the need to configure the `SpecificAvroSerde` etc. This is only for demo purposes, as I am adding a couple of `toStream()` and `toTable()` method calls for debugging. 

```
@Bean
public BiFunction<KTable<String, EMPLOYEE>, KTable<String, DEPARTMENT>, KTable<String, RESULT>> enrichEmployee() {

Serde<RESULT> specificAvroSerde = new SpecificAvroSerde<>();
specificAvroSerde.configure(
		Collections.singletonMap(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, "http://localhost:8081"),
		false);
return (leftSource, rightSource) -> leftSource
		.toStream().peek(new ForeachAction<String, EMPLOYEE>() {
			@Override
			public void apply(String key, EMPLOYEE value) {
				System.out.println(key + value);
			}
		})
		.toTable()
		.join(rightSource,
		(emp, dept) -> {
			RESULT result = new RESULT();
			result.setID(emp.getID());
			result.setDEPTID(dept.getID());
			result.setENAME(emp.getENAME());
			result.setDNAME(dept.getDNAME());
                  result.setCREATEDDATE(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant());
                  result.setMODIFIEDDATE(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant());
			return result;
		},
		Materialized.with(Serdes.String(), specificAvroSerde)/* ValueJoiner */)
		.toStream().peek(new ForeachAction<String, RESULT>() {
			@Override
			public void apply(String key, RESULT value) {
				System.out.println("Enriched: " + key + value);
			}
		})
		.toTable();
}
```

`application.yml`

```
spring:
  cloud:
    stream:
      function:
        definition: enrichEmployee
      bindings:
        enrichEmployee-in-0:
          destination: test_EMPLOYEE
        enrichEmployee-in-1:
          destination: test_DEPARTMENT
      kafka:
        streams:
          binder:
            functions:
              enrichEmployee.applicationId: 175594_appid
            configuration:
              commit.interval.ms: 100
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              state.dir: state-store
              acceptable.recovery.lag: 0
              schema.registry.url: http://localhost:8081
```
From the maven configuration (`pom.xml`) of this project, you can remove the following 2 dependencies:

```
spring-cloud-stream-binder-kafka
spring-cloud-schema-registry-client
```

Please remove the usage of `EnableSchemaRegistryClient` annotation from all the classes.

**Running the samples**

Make sure you have Kafka available on `localhost:9092` and the Confluent Schema Registry on `localhost:8081`. 

1. Run the `PosnEnrichApplication`
2. Run the `ProduceEmployee` application
3. Run the `ProduceDepartment` application

`curl -X POST http://localhost:8078/sendEmployees`
`curl -X POST http://localhost:8079/sendDepartments`

Observe that in your `PosnEnrichApplication`, you see the joined data. 

Everything works for me as expected. I am closing this issue. Please open a new issue if you observe any bugs. Otherwise, for questions like these, our preferred way of communication is via Stack Overflow and using the tag `spring-cloud-stream`. Thanks!.
