### ISSUE TITLE
Default partitioning not respected with StreamBridge

### ISSUE THREAD

**Issue by dejank1986** [spring-cloud/spring-cloud-stream#2815]
**Describe the issue**
After upgrading to version `4.0.4` we noticed that default partitioning is not working as expected `(key.hashCode() % partitionCount)` when using StreamBridge. It can be possibly associated with this commented block: https://github.com/spring-cloud/spring-cloud-stream/blob/e06d4eedfd70302f0ba7241adb3e3e3d8d8b00d5/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L263. Before, if condition is met, `DefaultPartitionInterceptor` was added and `partitionHandler.determinePartition(message)` was called, which is not the case now in version `4.0.4`.

**To Reproduce**
We are using Spring Cloud Stream functions. The message key is a very simple record schema.

1. Set the configuration properties
```
spring.cloud.stream:
  default:
    producer:
      useNativeEncoding: true
      partition-key-expression: headers['kafka_messageKey'].id
    consumer.useNativeDecoding: true
  function.autodetect: false
  bindings:
    testEventSource-out-0:
      destination: test-event
  kafka:
    binder:
      auto-create-topics: false
      producer-properties:
        key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
```
2. Run the following integration test
```
void sendEvent_whenUsingStreamBridge_shouldRespectPartitioningScheme() {
        final int numberOfPartitions = 6;

        final Message<KafkaNull> outgoingMessage = MessageBuilder.withPayload(KafkaNull.INSTANCE)
                .setHeader(KafkaHeaders.KEY, TestEventKey.newBuilder().setId(1001L).build())
                .build();

        streamBridge.send("testEventSource-out-0", outgoingMessage);

        final ConsumerRecords<Object, Object> records = testConsumer.poll(Duration.ofSeconds(5L));
        assertThat(records.iterator().next().partition()).isEqualTo(eventId % numberOfPartitions);
    }
```
We have used `KafkaNull.INSTANCE` but it's the same behaviour with the regular message.
4. See the failed assertion

**Version of the framework**
SpringBoot 3.1.2
SpringCloudStream 4.0.4

**Expected behavior**
When using defaults partition should be selected based on the following function: `(key.hashCode() % partitionCount)`.
