### ISSUE TITLE
Merge Other Configurations with Default Config

### ISSUE THREAD

**Issue by omercelikceng** [spring-cloud/spring-cloud-stream#2840]
Hello,

In my project, I define some default configs for producers, consumers and topics. In this way, I try to prevent unnecessary config repetition.
However, I may need to override some configurations. But when I override, my default configs are not used.
I want my default configs to be merged with the settings I define under **spring.cloud.stream.kafka.bindings.**

When I examined the code, I saw that when a configuration was defined under **spring.cloud.stream.kafka.bindings**, the default settings were ignored.
Wouldn't it be better if we merge these?

Can you help me with this? Wouldn't it be better to introduce such a feature?

My Default Configs : 

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 3
          autoCreateTopics: true
          autoAddPartitions: true
          minPartitionCount: 5
        default:
          consumer:
            topic:
              properties:
                retention.ms: 300000000
                segment.bytes: 300000000
                min.insync.replicas: 2
          producer:
            configuration:
              compression.type: lz4
              acks: all
              retries: 567
              enable:
                idempotence: true
            topic:
              properties:
                retention.ms: 300000000
                segment.bytes: 300000000
                min.insync.replicas: 2
```

Configs for override: 

```
spring:
  cloud:
    stream:
      kafka:
        bindings:
          student-topic-out:
            producer:
              topic:
                properties:
                  retention.bytes: 800000000
```

When I define this configuration, only the retention byte configuration is valid.
My other default producer configs are ignored.
I want these settings to remain valid as well. (**acks: all, compression.type: lz4, retries: 567, min.insync.replicas: 2** ....)
Actually, I just want to be able to override the retention.byte configuration. But it causes my other default configurations to be ignored.

![tempsnip](https://github.com/spring-cloud/spring-cloud-stream/assets/34758411/f2756ef2-05e7-43c2-9035-79cf3dac6b40)
