### ISSUE TITLE
Spring cloud kafka binder configuration doesnt work

### ISSUE THREAD

**Issue by hellerEkc** [spring-cloud/spring-cloud-stream#2871]
Hi, I have simple project for producer to Kafka, but Spring Cloud ignore configuration in application.yml. It allways pick topic name from placeholder of StreamBridge, not from configuration. I use Kafka kafka_2.13-3.6.0. Project to reproduce this issue is in attachment
[kafka_demo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/13649177/kafka_demo.zip)

**Comment by sobychacko** [comment]
When you use `StreamBridge#send`, the first argument is the binding name. In your case, you are providing `kafkaDemoTopic` as the binding name when calling the `send` method. If a destination is not provided on the binding via configuration, the binding name will be used as the topic name. I see some issues in your configuration. Here is a cleaned-up version of it. I removed all the unnecessary configurations. 

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          brokers: localhost:9092 # this is the default value, so not really needed. 
          autoCreateTopics: false
      bindings:
        kafkaDemoTopic-out-0:
          destination: kafka_demo_topic
```

Then, when you call `StreamBridge.send`, use `kafkaDemoTopic-out-0` as the binding name instead of `kafkaDemoTopic`.

```
streamBridge.send("kafkaDemoTopic-out-0", ...)
```
