### ISSUE TITLE
Classpath reference doesn't work for arbitrary producerProperties

### ISSUE THREAD

**Issue by srinivasboini** [spring-cloud/spring-cloud-stream#2882]
Currently using:

spring-boot 2.7.3
spring-cloud 2021.0.3 (spring-cloud-starter-stream-kafka 3.2.4)

I have a scenario where I need to use a JKS certificate to connect both to Kafka and to the Schema registry. I have declared properties like so:
```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
            security:
              protocol: SSL
            ssl:
              truststore:
                type: JKS
                location: classpath:certs/mycert-app.jks
                password: myapp
              keystore:
                type: JKS
                location: classpath:certs/mycert.jks
                password: myapp
          producerProperties:
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: classpath:certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: classpath:certs/mycert.jks
                    password: myapp

```
The problem is that the classpath: reference only works for the Kafka connection itself. It doesn't work for the Schema, throwing a java.io.FileNotFoundException: classpath:certs/mycert.jks (No such file or directory).
It works though with an absolute path, like /Users/eduardolbueno/workspace/myapp/src/main/resources/certs/mycert.jks but that is subpotimal for cloud environments.

I also went through below issue and code fix that has done for the similar issue before.

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1171

The applied fix for moving the certs from classpath to temp dir and then updating the absolute path to ssl props should also applicable for consumerProperties and producerProperties. In my case the schema registry ssl connection only works if I place all the schema registry ssl props under producerProperties with the cert location as absolute path. However, if the cert is in my classpath it fails with the below error.

```
Caused by: java.io.FileNotFoundException: classpath:certs/mycert.jks (No such file or directory) 
at java.io.FileInputStream.open0(Native Method) 
at java.io.FileInputStream.open(FileInputStream.java:195) 
at java.io.FileInputStream.<init>(FileInputStream.java:138) 
at java.io.FileInputStream.<init>(FileInputStream.java:93) 
at io.confluent.kafka.schemaregistry.client.security.SslFactory$SecurityStore.load(SslFactory.java:160) 
at io.confluent.kafka.schemaregistry.client.security.SslFactory$SecurityStore.access$000(SslFactory.java:144) 
at io.confluent.kafka.schemaregistry.client.security.SslFactory.createSslContext(SslFactory.java:96) 
at io.confluent.kafka.schemaregistry.client.security.SslFactory.<init>(SslFactory.java:69)
```

**Version of the framework** 
spring-boot 2.7.3
spring-cloud 2021.0.3 (spring-cloud-starter-stream-kafka 3.2.4)

**Expected behavior* should be able to use jks file from classpath to connect to schema registry with mtls configuration*

**Comment by sobychacko** [comment]
@srinivasboini, does it work if you move your schema registry SSL properties out of `producerProperties` as below? This is the fix that the other commit you mentioned ^^ addresses. 

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
            security:
              protocol: SSL
            ssl:
              truststore:
                type: JKS
                location: classpath:certs/mycert-app.jks
                password: myapp
              keystore:
                type: JKS
                location: classpath:certs/mycert.jks
                password: myapp
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: classpath:certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: classpath:certs/mycert.jks
                    password: myapp    
          producerProperties:
      ...      
```

If so, what prevents you from going with this approach?

**Comment by srinivasboini** [comment]
Hi @sobychacko , Thanks for looking into this. 

If we move the schema registry ssl properties out of producer properties and place it under binder configuration will not work. I listed down the scenario's that I tested below for further understanding on this issue.

1) Schema registry ssl props under binder configurations with keystore and trust locations starts with **classpath:**  **WON'T WORK**

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: classpath:certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: classpath:certs/mycert.jks
                    password: myapp    
```


2)  Schema registry ssl props under binder producerProperties with keystore and trust locations starts with **classpath:**  **WON'T WORK**

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
.......
........

         producerProperties:
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: classpath:certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: classpath:certs/mycert.jks
                    password: myapp    

```

3) Schema registry ssl props under binder configurations with keystore and trust locations are absolute paths  **WON'T WORK**

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: /tmp/certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: /tmp/certs/mycert.jks
                    password: myapp    
```

The only working configurations so far is below .

4)  Schema registry ssl props under binder producerProperties with keystore and trust locations starts with absolute path **WON'T WORK**

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: // omitted
          configuration:
.......
........

         producerProperties:
            schema:
              registry:
                url: // omitted
                ssl:
                  truststore:
                    location: /tmp/certs/mycert-app.jks
                    password: myapp
                  keystore:
                    location: /tmp/certs/mycert.jks
                    password: myapp    

```

It only works if you pass the absolute path for the JKS file , For this, the ssl schema registry properties have to be declared under producerProperties. Also, the same applies to consumerProperties if you have a consumer. 

It would be really great if we can give a provision to place this schema registry ssl props under **binder configuration** and make it work  for both producer and consumers with keystore and trust store locations either absolute path or a location from classpath itself.
