### ISSUE TITLE
Force disable the creation of Kafka Admin Client

### ISSUE THREAD

**Issue by akoufa** [spring-cloud/spring-cloud-stream#2914]
I am using Spring Cloud Stream Binder Kafka to connect to an Azure Event Hub Kafka. I am observing a strange behaviour that Kafka AdminClient is being created despite being disabled by the auto topic creation property. Is there a workaround to force disable the Kafka Admin Client creation?

My configuration looks like this:

```
spring:
  cloud:
    azure:
      eventhubs:
        connection-string: ${azure.eventhub.connection-string}
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          brokers: ${azure.eventhub.namespace}
          configuration:
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${azure.eventhub.connection-string}";
          consumer-properties:
            heartbeat.interval.ms: 3000
            session.timeout.ms: 30000
            max.poll.interval.ms: 300000
```
