### ISSUE TITLE
/actuator/bindings endpoint does not sanitize sensitive data nor invokes actuators SanitizingFunction methods

### ISSUE THREAD

**Issue by Felixel42** [spring-cloud/spring-cloud-stream#2932]
**Describe the issue**
I guess it would be more sort of a new/unspported features, that the `/actuator/bindings` endpoint sanitizes it's properties with actuator's default [sanitizing function](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.sanitization) or invokes the userProvided `SanitizingFunction` Bean by default. 
At least I expected that it would be  the default for all actuator endpoints, enclosing bindings endpoint.

**To Reproduce**

- have a minimal spring-cloud-stream application with a least one binding, that contains sensitive data in its configuration e.g. `sasl.jaas.config` for accessing topics with dedicated credentials

```yaml
  cloud:
    function:
      definition: "consume"
    stream:
      bindings:
        consume-in-0:
          destination: my-topic
          group: "my-group"
      kafka:
        binder:
          autoCreateTopics: true
        bindings:
         consume-in-0:
            consumer:
              configuration:
                sasl:
                  jaas:
                    config: "string containing credentials"

## expose bindings via http in actuator/bindings
management:
  endpoints:
    web:
      exposure:
        include: health, bindings

```

1. Invoke GET on localhost:8080 '/actuator/bindings'

```json
[
  {
    "bindingName": "consume-in-0",
    "name": "my-topic",
    "group": "my-group",
    "pausable": true,
    "state": "stopped",
    "paused": false,
    "extendedInfo": {
      "bindingDestination": "KafkaConsumerDestination{consumerDestinationName='my-topic', partitions=0, dlqName='null'}",
      "ExtendedConsumerProperties": {
        "bindingName": "consume-in-0",
        "concurrency": 1,
        "instanceCount": 1,
        "maxAttempts": 3,
        "backOffInitialInterval": 1000,
        "backOffMaxInterval": 10000,
        "backOffMultiplier": 2.0,
        "defaultRetryable": true,
        "extension": {
          "ackEachRecord": false,
          "autoRebalanceEnabled": true,
          "autoCommitOffset": true,
          "ackMode": null,
          "autoCommitOnError": null,
          "startOffset": null,
          "resetOffsets": false,
          "enableDlq": false,
          "dlqName": null,
          "dlqPartitions": null,
          "dlqProducerProperties": {
            "bufferSize": 16384,
            "compressionType": "none",
            "sync": false,
            "sendTimeoutExpression": null,
            "batchTimeout": 0,
            "messageKeyExpression": null,
            "headerPatterns": null,
            "configuration": {},
            "topic": {
              "replicationFactor": null,
              "replicasAssignments": {},
              "properties": {}
            },
            "useTopicHeader": false,
            "recordMetadataChannel": null,
            "transactionManager": null,
            "closeTimeout": 0,
            "allowNonTransactional": false
          },
          "recoveryInterval": 5000,
          "trustedPackages": null,
          "standardHeaders": "none",
          "converterBeanName": null,
          "idleEventInterval": 30000,
          "destinationIsPattern": false,
          "configuration": {
            "sasl.jaas.config": "<may contain credentials>"
          },
          "topic": {
            "replicationFactor": null,
            "replicasAssignments": {},
            "properties": {}
          },
          "pollTimeout": 5000,
          "transactionManager": null,
          "txCommitRecovered": true,
          "commonErrorHandlerBeanName": null,
          "reactiveAutoCommit": false,
          "reactiveAtMostOnce": false
        }
      }
    },
    "binderName": "kafka",
    "input": true,
    "binderType": "kafka"
  }
]
```

Payload may contain sensitive data

**Version of the framework**: Spring Boot 3.2.4, <spring-cloud.version>2023.0.1</spring-cloud.version>
**Expected behavior**
- sensitive payload is either cleared or sanitized 

**Additional context**
- sanitize() must be explicitly called in the provided endpoint, like in actuator/env https://github.com/spring-projects/spring-boot/blob/c3c82bd220b39998e5dc483db55532092ace1b3b/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/env/EnvironmentEndpoint.java#L69
