### ISSUE TITLE
RabbitMQ: spring.cloud.stream.rabbit.bindings.* properties not recognized in Native/AOT builds

### ISSUE THREAD

**Issue by mjbingen** [spring-cloud/spring-cloud-stream#2938]
**Describe the issue**
When building a Spring Boot app with Spring Cloud Stream as a native image with GraalVM, the properties scoped under `spring.cloud.stream.rabbit.bindings.*` do not appear to be recognized in the native image and are defaulted.

This is problematic as properties like `exchangeType`, `routingKeyExpression`,  and `bindingRoutingKey` produce defaults that lead to unexpected behaviors. For example, the exchangeType will always be `topic` and the routing keys default to `#`.

It is important to note that properties scoped under `spring.cloud.function.definition`, `spring.cloud.stream.output-bindings`, and `spring.cloud.stream.bindings` seem to function as desired.

**To Reproduce**
A simple reproducible example can be found in full here: https://github.com/mjbingen/spring-cloud-stream-sandbox/tree/native

Example:

application.yml
```
spring:
  cloud:
    function:
      definition: onFoo;onBar
    stream:
      output-bindings: the-exchange
      bindings:
        onFoo-in-0:
          destination: the-exchange
        onBar-in-0:
          destination: the-exchange
      rabbit:
        bindings:
          the-exchange:
            producer:
              exchangeType: direct
              routingKeyExpression: '''the.foo.key'''
          onFoo-in-0:
            consumer:
              exchangeType: direct
              bindingRoutingKey: the.foo.key
          onBar-in-0:
            consumer:
              exchangeType: direct
              bindingRoutingKey: the.bar.key
```

Code - expect to self-consume messages when REST endpoint is hit only from `onFoo` method that is bound to the exchange with matching routing key. However, when application is run as a native image, all bounding keys default to `#`, so the YAML-specified routing key is ignored and both methods consume the message.
```
package com.mjb.spring.cloud;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.function.StreamBridge;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.time.OffsetDateTime;
import java.util.function.Consumer;

@SpringBootApplication
@RestController
public class Main
{
    public static void main(String... args)
    {
        SpringApplication.run(Main.class, args);
    }

    @Autowired
    private StreamBridge streamBridge;

    @RequestMapping
    @ResponseStatus(HttpStatus.ACCEPTED)
    public String sendToBridge()
    {
        // Publish a timestamp
        final var now = OffsetDateTime.now().toString();
        streamBridge.send("the-exchange", now);
        return now;
    }

    @Bean
    public Consumer<String> onFoo()
    {
        // Receive from exchange with key 'the.foo.key'
        return received -> System.out.println("Received from FOO: " + received);
    }

    @Bean
    public Consumer<String> onBar()
    {
        // Not expected to receive from exchange with key 'the.bar.key'
        return received -> System.out.println("ERROR: Received from BAR: " + received);
    }
}
```

**Version of the framework**
Spring Boot 3.2.5
Spring Cloud Stream 4.1.1
Oracle GraalVM 21

**Expected behavior**
Properties defined in `application.yml` and present at compile time should be reflected in the native image and behave just like the JVM version.

**Screenshots**

**Additional context**
Similar to [prior issue](https://github.com/spring-cloud/spring-cloud-stream/issues/2644) with Kafka streams. However, [RabbitMQ binder](https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/current/reference/html/spring-cloud-stream-binder-rabbit.html) documentation suggests properties must be defined in the prefix above.
