### ISSUE TITLE
[docs] @ServiceActivator mode has been outdated? and some conflicts are found in the documentation

### ISSUE THREAD

**Issue by chenbihao** [spring-cloud/spring-cloud-stream#3008]
**Describe the issue**

@ServiceActivator mode has been outdated? and some conflicts are found in the documentation

I found here [producing-and-consuming-messages-#Handling Errors](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#polled-errors)  to use the instructions to use `@serviceActivator` to make an error handling

And did not see the relevant instructions in the [overview-error-handling](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/overview-error-handling.html), have the@ServiceActivator mode have been removed?

**To Reproduce**

I use this way invalid:

```java
@ServiceActivator(inputChannel = "request-coupon-topic.add-coupon-group.errors")
public void requestCouponFallback(ErrorMessage errorMessage) throws Exception {
    log.info("consumer error fallback: {}", errorMessage);
}
```
```yml
      bindings:
        addCoupon-out-0:
          destination: request-coupon-topic
          content-type: application/json
          binder: my-rabbit
        addCoupon-in-0:
          destination: request-coupon-topic
          content-type: application/json
          group: add-coupon-group
          binder: my-rabbit
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 5000
            backOffMultiplier: 2
```

But it worked:

```java
@ServiceActivator(inputChannel = "errorChannel")
```
 it worked too:
```java
@Bean
    public Consumer<ErrorMessage> requestCouponErrorHandler() {
        return v -> {
            log.info("consumer error handler: {}", v);
        };
    }
```

**Version of the framework**

spring-cloud 2023.0.3

**Expected behavior**
**Screenshots**
