### ISSUE TITLE
Application fails to start when using Pulsar binder in multi-binder scenario

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-stream#3013]
### Scenario
A Spring Boot application using SCSt w/ Pulsar binder as input and Kafka binder as an output.

### Problem
App fails to start w/ following message:

> No qualifying bean of type 'org.springframework.pulsar.core.PulsarAdministration.

### Expected Behavior
Application starts with Pulsar as input binder and Kafka as output binder.

### Details
The reporting user followed [this guide](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/multiple-binders.html) to configure the binders w/ the following yaml:

```yaml
      binders:
        kafka:
          type: kafka
          (...)
        pulsar:
          type: pulsar
          environment:
            spring:
              cloud:
                stream:
                  pulsar:
                    binder:
                      config:
                        serviceUrl: pulsar://localhost:6650
                        adminUrl: http://localhost:8080
```

After deleting the `environment` property from pulsar binder config above, everything is fine, but it disables the possibility of additional configuration at this level.

> _Original report_: https://stackoverflow.com/questions/79046248/springboot-spring-cloud-stream-pulsar-binder-startup-failed

**Comment by Dagmara-K** [comment]
Issue observed for Springboot 3.3.2 + spring-cloud-stream 4.1.2, we tried also Springboot 3.2, 3.1 and 3.0, the same behaviour every time.

**Comment by onobc** [comment]
### Background

The Pulsar binder currently relies on Spring Boot auto-configuration (`PulsarAutoConfiguration`) to provide the necessary components to communicate to/from Pulsar.
This works well when for a Spring Boot application with a single binder as the binder context shares the outer application context and gets access to all of the expected Pulsar auto-configured components.
However, the moment that we add another binder and set the `environment` property, we are telling SCSt to not use the outer application context and instead rely on its own configuration.

> <sub>The above is more elegantly stated in [Connecting to Multiple Systems](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/multiple-systems.html).</sub>

In fact, you can remove the Kafka 2nd binder out of this equation and reproduce the error w/ this single Pulsar binder that is specifying the environment. For example:

```yaml
spring:
  cloud:
    stream:
      binders:
        pulsar1:
          type: pulsar
          environment:
            spring:
              cloud:
                stream:
                  pulsar:
                    binder:
                      config:
                        serviceUrl: pulsar://localhost:6650
                        adminUrl: http://localhost:8080          
```

#### So why does this work for Rabbit and Kafka? 
The reason is that the Rabbit|KafkaBinderConfiguration import a **subset** of their respective Spring Boot auto-configuration directly. I highlight **subset** because it is frowned upon to directly rely on Spring Boot auto-configuration classes as they are not considered public API. 

We broke the direct dependence for Rabbit and Kafka a while back ([here](https://github.com/spring-cloud/spring-cloud-stream/commit/58cdd1b157660bc6928b6a9d56e0cc6608332e3d) and [here](https://github.com/spring-cloud/spring-cloud-stream/commit/37abca427d2f97185e19fda0e052c5d3874bfa3f)) which allowed us to include this subset of the auto-configuration for their binders. 

This subset of configuration does not yet exist for Spring Pulsar so when we implemented the Pulsar binder we decided to keep it simple and support a single binder in a Spring Boot Spring Pulsar application. 

### Workaround
However, until we break the dependence on the PulsarAutoConfiguration, there is a workaround to support multi-binders for Pulsar.

1. Exclude the application's outer PulsarAutoConfiguration and then
2. Use `spring.main.sources` to include the auto-configuration on the environment entry.

The example above becomes:

```yaml
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.pulsar.PulsarAutoConfiguration
  cloud:
    stream:
      binders:
        pulsar1:
          type: pulsar
          environment:
            spring:
              main.sources: org.springframework.boot.autoconfigure.pulsar.PulsarAutoConfiguration
              cloud:
                stream:
                  pulsar:
                    binder:
                      config:
                        serviceUrl: pulsar://localhost:6650
                        adminUrl: http://localhost:8080   
```

Let us know once you give the above workaround a try. Once we are done communicating on this issue I will close it and create an issue to break the dependence on the Pulsar auto-configuration (like we did previously for Kafka and Rabbit).

Thanks
