### ISSUE TITLE
Application fails to start when using Google PubSub binder in multi-binder scenario

### ISSUE THREAD

**Issue by chrissalerno** [spring-cloud/spring-cloud-stream#3046]
### Scenario

Similar to the issue logged https://github.com/spring-cloud/spring-cloud-stream/issues/3013

It seems that the PubSub binder has the same issue when trying to run it in a multi binder setup.  In my scenario, I was trying to have two different input binders, one for pubsub and another for Solace.  As soon as both were introduced, in addition to the additional environment variables being configured for the PubSub binder, the application would begin to not start up. 

### Problem

App fails to start w/ following message:

`No qualifying bean of type 'org.springframework.cloud.stream.binder.Binder<?, ?, ?>' available`

### Details

The following guide was followed [this guide](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/multiple-binders.html) to configure the binders w/ the following yaml:

```
binders:
   pubsub:
      type: pubsub
      environment:
         spring:
            cloud:
              gcp:
                project-id: example-prokect-id
```

As soon as the environment properties are removed the application starts up again.
