### ISSUE TITLE
Consumer stops processing messages when handling large backlogs using spring-cloud-starter-stream-rabbit

### ISSUE THREAD

**Issue by yupu1998** [spring-cloud/spring-cloud-stream#3080]
Thanks for considering raising a Spring Cloud Stream issue. Please take the time to review the following categories as some of them do not apply here.

**Describe the issue**
I encountered an issue while using the spring-cloud-starter-stream-rabbit library to process a large backlog of messages. My implementation involves reading the backlog data, categorizing it into two types, and pushing these types to two separate queues. Then, I consume and process data from the two queues independently.

However, during actual usage, after running for a short period of time, the consumer responsible for processing the backlog stops consuming messages. There are no errors or exceptions logged, and the application appears to be in a stalled state.

To verify this behavior, I created a simple demo that reproduces the problem.

**To Reproduce**
*yml*
 ```
 cloud:
    function:
      definition: input1;input2;input3
    stream:
      rabbit:
        bindings:
          input1-in-0:
            consumer:
              exchangeType: direct
              bindingRoutingKey: output1
              acknowledge-mode: none
              queueNameGroupOnly: true
          input2-in-0:
            consumer:
              exchangeType: direct
              bindingRoutingKey: output2
              acknowledge-mode: none
              queueNameGroupOnly: true
          input3-in-0:
            consumer:
              exchangeType: direct
              bindingRoutingKey: output3
              acknowledge-mode: none
              queueNameGroupOnly: true
          output1-out-0:
            producer:
              exchangeType: direct
              routingKeyExpression: "'output1'"
              queueNameGroupOnly: true
          output2-out-0:
            producer:
              exchangeType: direct
              routingKeyExpression: "'output2'"
              queueNameGroupOnly: true
          output3-out-0:
            producer:
              exchangeType: direct
              routingKeyExpression: "'output3'"
              queueNameGroupOnly: true
      bindings:
        input1-in-0: 
          destination: TestExchange1
          content-type: application/json
          group: TestExchange1.queue1 
        input2-in-0: 
          destination: TestExchange2 
          content-type: application/json
          group: TestExchange2.queue2 
        input3-in-0: 
          destination: TestExchange2 
          content-type: application/json
          group: TestExchange2.queue3 
        output1-out-0: 
          destination: TestExchange1 
          content-type: application/json
          group: TestExchange1.queue1
        output2-out-0: 
          destination: TestExchange2
          content-type: application/json
          group: TestExchange2.queue2
        output3-out-0: 
          destination: TestExchange2 
          content-type: application/json
          group: TestExchange2.queue3
```
*key code*
```
@Resource
    private DataProducer dataProducer;
    @Resource
    private AtomicRecord atomicRecord;
    @Bean
    ConnectionFactoryCustomizer connectionFactoryCustomizer() {
        return (connectionFactory) -> {
            connectionFactory.setShutdownTimeout(0);
        };
    }

    @Bean
    public Consumer<Message<byte[]>> input1() throws IOException {
        return message -> {
            atomicRecord.increment1();
            byte[] payload = message.getPayload();
            dataProducer.sendOutput2(payload);
            dataProducer.sendOutput3(payload);
        };
    }


    @Bean
    public Consumer<Message<byte[]>> input2() throws IOException {
        return message -> {
            atomicRecord.increment2();
            byte[] payload = message.getPayload();
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        };
    }


    @Bean
    public Consumer<Message<byte[]>> input3() throws IOException {
        return message -> {
            atomicRecord.increment3();
            byte[] payload = message.getPayload();
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        };
    }
```
*push a large volume of data into the backlog queue*
```
@Scheduled(fixedDelay = 1000)
    public void keystoneCache(){

        //生成数据
        String content = String.join("!!!", Collections.nCopies(1000, "Hello World"));
        byte[] data = content.getBytes();

        //推送数据给output1
        for (int i = 0; i < 1000; i++) {
            dataProducer.sendOutput1(data);
        }
    }
```
*monitor the health of the consumers*
```
 @Scheduled(fixedDelay = 1000)
    public void logConsumer(){

        boolean c1 = false;
        boolean c2 = false;
        boolean c3 = false;
        if(atomicRecord.getCount1()!= count1){
            c1 = true;
            count1 = (long) atomicRecord.getCount1();
        }
        if(atomicRecord.getCount2()!= count2){
            c2 = true;
            count2 = (long) atomicRecord.getCount2();
        }
        if(atomicRecord.getCount2()!= count3){
            c3 = true;
            count3 = (long) atomicRecord.getCount3();
        }
        System.out.println(String.format("input1:%s; input2:%s; input3:%s",c1,c2,c3));

    }
```
*monitor  logs*
```
input1:true; input2:true; input3:true
input1:true; input2:true; input3:true
input1:true; input2:true; input3:true
input1:true; input2:true; input3:true
input1:true; input2:true; input3:true
input1:false; input2:true; input3:true
input1:false; input2:true; input3:true
input1:false; input2:true; input3:true
input1:false; input2:true; input3:true
input1:false; input2:true; input3:true
input1:false; input2:true; input3:true
```

**Version of the framework**
spring-cloud-starter-stream-rabbit 4.2.0

**Additional context**
The problem occurs only when processing a large backlog of messages.
There are no errors or exceptions in the logs.
