### ISSUE TITLE
Problems with applying clientFactoryCustomizer when using a transaction producer

### ISSUE THREAD

**Issue by youngpark17** [spring-cloud/spring-cloud-stream#3090]
**Describe the issue**

The clientFactoryCustomizer does not register properly when it is a transaction producer.

**To Reproduce**

```java
@Bean
ClientFactoryCustomizer clientFactoryCustomizer() {
	return new ClientFactoryCustomizer() {
		@Override
		public void configure(ProducerFactory<?, ?> producerFactory) {
			if (producerFactory instanceof DefaultKafkaProducerFactory) {
				((DefaultKafkaProducerFactory) producerFactory).setMaxAge(Duration.ofDays(6));
			}
		}
	};
}
```

```yml
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: host
          required-acks: all
          auto-create-topics: false
          auto-add-partitions: false
          transaction:
            transaction-id-prefix: ${random.uuid}
          producer-properties:
            acks: all
            retries: 3
            enable.idempotence: true
            max.in.flight.requests.per.connection: 1
            max.block.ms: 5000
        bindings:
          outbound-test-command:
            producer:
              allowNonTransactional: false
```

1. make ProducerFactory in transaction producer
![Image](https://github.com/user-attachments/assets/4c2c1f9c-0301-4bb7-8845-40e7b1368e06)

2. clientFactoryCustomizers trying to customize **but clientFactoryCustomizers is empty**
![Image](https://github.com/user-attachments/assets/8cb3e6c5-f0e6-433f-b39d-5271562ac3a7)

3. add clientFactoryCustomizers after customizer
![Image](https://github.com/user-attachments/assets/9c5b82f5-5e8e-467c-9a2e-1f94a36d697a)

clientFactoryCustomizer needs to set maxAge but cannot.

**Version of the framework**
:: Spring Boot ::                (v3.4.1)
spring-cloud-stream 4.2
spring-cloud-stream-binder-kafka 4.2

**Expected behavior**
clientFactoryCustomizer needs to set maxAge
**Screenshots**

**Additional context**
