### ISSUE TITLE
Bindings endpoint doesn't works when SpEL expression is configured

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#3104]
**Describe the issue**
The [bindings endpoint actuator](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_actuator) doesn't works when a binding is configured with a expression. for example:

```yaml
spring: 
  cloud:
    stream:
      kafka:
        bindings:
          foo-out-0:
            producer:
              message-key-expression: headers['kafka_receivedMessageKey']
```  

**To Reproduce**
We are crated a [repository](https://github.com/ferblaca/demoStreamGenerics/tree/issue-endpoint-bindings) that reproduces the problem:
1. Start application
2. Go to http://localhost:8080/demo-stream-kafka/actuator/bindings

**Version of the framework**
SB 3.4.4
SC 2024.0.1

**Observed behavior**
An error is throw:
```
{"timestamp":"2025-03-26T11:39:23.281+00:00","status":500,"error":"Internal Server Error","message":"No serializer found for class org.springframework.expression.spel.support.StandardTypeConverter and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[10]->org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$1[\"extension\"]->org.springframework.cloud.stream.binder.kafka.properties.KafkaProducerProperties[\"messageKeyExpression\"]->org.springframework.expression.spel.standard.SpelExpression[\"evaluationContext\"]->jdk.proxy2.$Proxy144[\"typeConverter\"])","errors":[]}
``` 

**Expected behavior**
The endpoint return the bindings information correctly.

**Additional context**
For SC 2024.0.0 works OK.
