### ISSUE TITLE
output-bindings property does not work for bindings definition

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-stream#3109]
After upgrading from Spring Cloud 2021 to 2024, I faced the issue with `spring.cloud.stream.output-bindings` property. 

Configuration:
```
spring:
  cloud:
    stream:
      output-bindings: demo-test
      bindings:
        demo-test-out-0:
          destination: demo_topics
          content-type: application/json
          producer:
            header-mode: none
          binder: kafka
```

With SC 2021 topic `demo_topics` was created and used.
With SC 2024 (and 2023) `demo_topics` was not used, and topic with name `demo-test` was created.

I prepared a demo to reproduce the issue.
Configuration: [application-test.yml](https://github.com/Ferioney/output-bindings-demo/blob/781dcf0691876aa4566483540a20b3d8fe2aa7f0/src/test/resources/application-test.yml#L1-L17).
Function test: [TopicsInUse](https://github.com/Ferioney/output-bindings-demo/blob/781dcf0691876aa4566483540a20b3d8fe2aa7f0/src/test/java/com/example/bindings/demo/TopicsInUseTest.java#L20).
SC 2021 branch: [cloud2021 pom.xml](https://github.com/Ferioney/output-bindings-demo/blob/cloud2021/pom.xml)
SC 2024 branch: [cloud2024 pom.xml](https://github.com/Ferioney/output-bindings-demo/blob/cloud2024/pom.xml)
