### ISSUE TITLE
Partitioning and Multi-Threaded processing of Queue Messages - Messages Not Being Delivered

### ISSUE THREAD

**Issue by ulmermark** [spring-cloud/spring-cloud-stream#663]
Help me if I am doing something wrong here.

My desire is to use partitioning/concurrency to insure thread-affinity as well as increase throughput of the application.

Spring Boot 1.4.0.RELEASE
Spring Cloud Starter Stream Rabbit - 1.0.0.RELEASE

I have an app that is queuing messages to a Processor.OUTPUT and consuming on Process.INPUT and when I have no partitioning I see all messages queued and consumed ( 8 for 8 in thiscase)

I introduce partitioning using the following:

```
  stream:
    bindings:
      input:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        consumer:
           concurrency: 1
           partitioned: true

      output:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        producer:
           partitioned: true
           partitionCount: 1
           partitionKeyExpression: payload.biller.externalKey
```

And receive 8 for 8 messages queue and consumed as shown in attached file.

[1-partitioned-logs.txt](https://github.com/spring-cloud/spring-cloud-stream/files/485856/1-partitioned-logs.txt)

If I change the concurrency to 2 and the partitionCount to 2, I do not get all 8 messages consumed as shown in the attached log file:

```
  stream:
    bindings:
      input:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        consumer:
           concurrency: 2
           partitioned: true

      output:
        destination: spn-rpps-biller-svc.biller.process
        group: biller
        producer:
           partitioned: true
           partitionCount: 2
           partitionKeyExpression: payload.biller.externalKey
```

[2-partitioned-logs.txt](https://github.com/spring-cloud/spring-cloud-stream/files/485873/2-partitioned-logs.txt)
