### ISSUE TITLE
Broadcast not work

### ISSUE THREAD

**Issue by beenryuu** [spring-cloud/spring-cloud-stream#688]
I'm trying a application with spring-cloud-stream. The application has two consumers, one is used to receive broadcast messages(all instances receive the same message), and the other one is not(only one instance receive messages in the same consumer group.)
I have two instances to run the application and the application.yml files are as below

```
# for instance 1
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: myhost01:4443,myhost02:4443,myhost03:4443
          zkNodes: myhost01:2181,myhost02:2181,myhost03:2181
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        channel1:
          consumer:
            startOffset: earliest
            partitioned: true
            instanceIndex: 0
            instanceCount: 2
          destination: topic1
          group: topic1-group
        channel2:
          consumer:
            startOffset: earliest
            instanceIndex: 0
            instanceCount: 1
          destination: topic2
          group: topic2-ins1
```
```
# for instance 2
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: myhost01:4443,myhost02:4443,myhost03:4443
          zkNodes: myhost01:2181,myhost02:2181,myhost03:2181
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        channel1:
          consumer:
            startOffset: earliest
            partitioned: true
            instanceIndex: 1
            instanceCount: 2
          destination: topic1
          group: topic1-group
        channel2:
          consumer:
            startOffset: earliest
            instanceIndex: 0
            instanceCount: 1
          destination: topic2
          group: topic2-ins2
```

The consumers binded to channel1 works well on two instances (only one consumer receive messages one time).
But conumsers binded to channel2 seemed not. I want the messages sent to topic2 broadcasted to all the consumers, but only one received.
Did I miss any other configurations?

kafka version: 0.9.0.1
dependency in my pom
```
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-stream-dependencies</artifactId>
                <version>1.0.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

Thanks!!
