### ISSUE TITLE
concurrency setting (in application.yml) doesn't work

### ISSUE THREAD

**Issue by beenryuu** [spring-cloud/spring-cloud-stream#701]
I have 2 nodes and there is a consumer process on each one with following application.yml
``` 
# for node 1
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: myhost01:4443,myhost02:4443,myhost03:4443
          zkNodes: myhost01:2181,myhost02:2181,myhost03:2181
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        channel1:
          consumer:
            startOffset: earliest
            partitioned: true
            instanceIndex: 0
            instanceCount: 2
          destination: topic1
          group: topic1-group
```
``` 
# for node 2
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: myhost01:4443,myhost02:4443,myhost03:4443
          zkNodes: myhost01:2181,myhost02:2181,myhost03:2181
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        channel1:
          consumer:
            startOffset: earliest
            partitioned: true
            instanceIndex: 1
            instanceCount: 2
          destination: topic1
          group: topic1-group
``` 
They work well and I add concurrency to increase throughput as below:
``` 
# for node 1
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: myhost01:4443,myhost02:4443,myhost03:4443
          zkNodes: myhost01:2181,myhost02:2181,myhost03:2181
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        channel1:
          consumer:
            startOffset: earliest
            partitioned: true
            instanceIndex: 0
            instanceCount: 2
          destination: topic1
          group: topic1-group
          concurrency: 2
```
``` 
# for node 2
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: myhost01:4443,myhost02:4443,myhost03:4443
          zkNodes: myhost01:2181,myhost02:2181,myhost03:2181
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        channel1:
          consumer:
            startOffset: earliest
            partitioned: true
            instanceIndex: 1
            instanceCount: 2
          destination: topic1
          group: topic1-group
          concurrency: 2
``` 
But it seems nothing changes. Did I use concurrency the wrong way?
Thanks!!
