### ISSUE TITLE
It is not clear how to handle onsuccess and onerror results when using Kafka

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream#795]
The framework offers `MessageChannel` as a way to send the messages asynchronously/synchronously:

    @Autowired
    private Source source;

    public void sayHello(String name) {
         source.output().send(MessageBuilder.withPayload(body).build());
    }

However the MessageChannel API doesn't allow the use of any type of callback to handle onsuccess and onerror results.

When a delivery fails I observe that there is a automatically registered `LoggingProducerListener` that prints the error:

    public interface ProducerListener<K, V> {
        void onSuccess(String topic, Integer partition, K key, V value, RecordMetadata recordMetadata);
        void onError(String topic, Integer partition, K key, V value, Exception exception);
        boolean isInterestedInSuccess();
    }

It would come in handy if we could specify a callback in the send() operation.
Otherwise, how can we register a custom error handler per operation? How can we know that the operation was successful? Are we supposed to use directly the KafkaTemplate (`KafkaTemplate.setProducerListener`) ?

In any case it would be great if the doc were a little bit clearer in this regards.

Thanks!

**Comment by mbogoevici** [comment]
@codependent You can register your own ProducerListener for handling errors.

Alternatively,  you can set an outbound binding to use a synchronous producer: as described in http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR2/reference/htmlsingle/#_kafka_producer_properties . This would cause an exception to be thrown if sending the message fails.

**Comment by codependent** [comment]
@mbogoevici The only downside is that the new registered ProducerListener would be shared by all producers, there's no way of having different behaviours per producer...

**Comment by mbogoevici** [comment]
@codependent Yes, that's one of the downsides of it. We can definitely consider suggestions to improve the API (either for Stream or for Spring Messaging itself), but for now I would recommend to stick to synchronous producers for error handling.

**Comment by codependent** [comment]
@mbogoevici Thanks I'll follow your advice and use the sync approach. Regarding this, I configured my service like this:

```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - kafka
          zk-nodes:
          - kafka
        bindings:
          paymentRequests:
            producer:
              sync: true
```
And it does block as expected. I stopped Kafka to check the blocking behaviour and found something weird:  even though I set a 500 msec timeout it takes 10 seconds to unblock the thread:

```
try{
    logger.info("*****");
    orderProcessor.output().send(MessageBuilder.withPayload(mapper.map(orderEntity, com.codependent.microshopping.stream.dto.Order.class)).build(), 500);
    logger.info("*****");
}catch(Exception e){
    logger.info("----");
}
```
```
2017-02-10 10:43:26.523  c.c.m.order.service.OrderServiceImpl     : *****
2017-02-10 10:43:36.532  c.c.m.order.service.OrderServiceImpl     : ----
```
How come it doesn't unblock after 500msec? I have lookup the doc in case there is a retrying mechanishm that is going on underneath but haven't found anything.

**Comment by mbogoevici** [comment]
@codependent 

Where do you set the 500msec timeout? Do notice that `batchTimeout` is equivalent to `linger.ms` and refers to how long a producer client will wait until releasing messages.

You can consider using the properties http://kafka.apache.org/documentation/#producerconfigs (use the `spring.cloud.stream.kafka.bindings.<channel>.producer.configuration` map to set generic Kafka properties), in particular `request.timeout.ms`. 

In any case, if the broker is down, the Kafka producer client will wait until its internal timeout has expired (defaults to 30s) before deciding that the record cannot be sent. The 10s timeout is coming from the underlying `KafkaProducerMessageHandler` that handles the sync operations (we don't expose an option for that, even if we should). Configuring a smaller timeout for the Kafka producer client should cause it to fail faster, which is what you expect.

**Comment by codependent** [comment]
I was indicating the timeout in `MessageChannel.send(Message<?> message, long timeout);` The javadoc states: `@param timeout the timeout in milliseconds or {@link #INDEFINITE_TIMEOUT}`:

In my code: `orderProcessor.output().send(MessageBuilder.withPayload(order).build(), 500);`

I will use the property `request.timeout.ms` but It's a little misleading to have a method to provide a timeout whereas this field is ignored. Anyway it's likely I'm missing something and it's there for a reason...

**Comment by mbogoevici** [comment]
Thanks for the clarification @codependent - I see the source of confusion now.

The parameter refers to the timeout of the channel receiving and passing the message to the downstream component (the outbound channel adapter). It does not apply because in this case the message is sent immediately (by contrast, for example with a `QueueChannel` with a bounded queue where the sender may block until the queue can receive the message).

You are raising a valid point though, as from the perspective of the user, the channel is supplied directly by the framework so it can honour this contract as well. While there is little we can do immediately, this is something we could consider for the future.

**Comment by garyrussell** [comment]
Since version 1.3, you can use the `error-channel-enabled` producer property.

Example:

```yaml
spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            error-channel-enabled: true
      kafka:
        bindings:
          output:
            producer:
              configuration:
                max:
                  block:
                    ms: 5000
```

and

```java
@SpringBootApplication
@EnableBinding(Source.class)
public class Scstgh795Application {

	public static void main(String[] args) {
		SpringApplication.run(Scstgh795Application.class, args);
	}

	@Bean
	ApplicationRunner runner(MessageChannel output) {
		return args -> {
			System.out.println("Stop the brokers and hit enter");
			System.in.read();
			output.send(new GenericMessage<>("foo"));
		};
	}

	@ServiceActivator(inputChannel = "output.errors")
	public void errorHandler(ErrorMessage em) {
		System.out.println(em);
	}

}
```

(Use a service activator subscribed to the error channel).

and...

```
Stop the brokers and hit enter
...
2018-04-11 11:22:34.843 ERROR 69320 --- [           main] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='{102, 111, 111}' to topic output:

org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 5000 ms.

ErrorMessage [payload=org.springframework.integration.kafka.support.KafkaSendFailureException: nested exception is org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 5000 ms., failedMessage=GenericMessage [payload=byte[3], ... [record=ProducerRecord(topic=output, partition=null, ...
```

**Comment by garyrussell** [comment]
The binder currently does not support receiving results of successful sends.

**Comment by garyrussell** [comment]
I updated the example to see how to get the results of successful sends, using a `ProducerInterceptor`:

```yaml
spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            error-channel-enabled: true
      kafka:
        bindings:
          output:
            producer:
              configuration:
                max:
                  block:
                    ms: 5000
                interceptor:
                  classes: com.example.Scstgh795Application$MyInterceptor
```

```java
@SpringBootApplication
@EnableBinding(Source.class)
public class Scstgh795Application {

	public static void main(String[] args) {
		SpringApplication.run(Scstgh795Application.class, args);
	}

	@Bean
	ApplicationRunner runner(MessageChannel output) {
		return args -> {
			System.out.println("Stop the brokers and hit enter");
			System.in.read();
			output.send(new GenericMessage<>("foo"));
			System.out.println("Start the brokers and hit enter");
			System.in.read();
			output.send(new GenericMessage<>("bar"));
			Thread.sleep(5_000);
		};
	}

	@ServiceActivator(inputChannel = "output.errors")
	public void errorHandler(ErrorMessage em) {
		System.out.println(em);
	}

	public static class MyInterceptor implements ProducerInterceptor<byte[], byte[]> {

		@Override
		public void configure(Map<String, ?> configs) {
		}

		@Override
		public ProducerRecord<byte[], byte[]> onSend(ProducerRecord<byte[], byte[]> record) {
			return record;
		}

		@Override
		public void onAcknowledgement(RecordMetadata metadata, Exception exception) {
			if (metadata != null) {
				System.out.println(metadata);
			}
			if (exception != null) {
				System.out.println(exception);
			}
		}

		@Override
		public void close() {
		}

	}

}
```
