### ISSUE TITLE
Setting binder properties using environment does not work

### ISSUE THREAD

**Issue by snwiem** [spring-cloud/spring-cloud-stream#873]
I'm trying to overwrite the host/port values for by rabbitmq binder using environment variables.
The environment variables are set using docker-compose file.

```
version: '2'
services:
  rabbitmq:
    image: 'spo/rabbitmq-server:latest'
    ports:
      - "5672:5672"
      - "15672:15672"
  demographics_loader:
    image: 'spo/datain-demographics-loader'
    links:
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=XXX
      - SPRING_DATASOURCE_PASSWORD=XXX
- SPRING_CLOUD_STREAM_BINDERS_RABBITBINDER_ENVIRONMENT_SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CLOUD_STREAM_BINDERS_RABBITBINDER_ENVIRONMENT_SPRING_RABBITMQ_PORT=5672

```

The application startup failes with

```
demographics_loader_1  | ***************************
demographics_loader_1  | APPLICATION FAILED TO START
demographics_loader_1  | ***************************
demographics_loader_1  |
demographics_loader_1  | Description:
demographics_loader_1  |
demographics_loader_1  | Binding to target org.springframework.cloud.stream.config.ChannelBindingServiceProperties@a9e5784e failed:
demographics_loader_1  |
demographics_loader_1  |     Property: spring.cloud.stream.binders[RABBITBINDER_ENVIRONMENT_SPRING_RABBITMQ_HOST]
demographics_loader_1  |     Value: rabbitmq
demographics_loader_1  |     Reason: Failed to convert property value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BinderProperties] for property 'binders[RABBITBINDER_ENVIRONMENT_SPRING_RABBITMQ_H
OST]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BinderProperties] for property 'binders[RABBITBINDER_ENVIRONMENT_SPRING
_RABBITMQ_HOST]': no matching editors or conversion strategy found
demographics_loader_1  |
demographics_loader_1  |     Property: spring.cloud.stream.binders[RABBITBINDER_ENVIRONMENT_SPRING_RABBITMQ_PORT]
demographics_loader_1  |     Value: 5672
demographics_loader_1  |     Reason: Failed to convert property value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BinderProperties] for property 'binders[RABBITBINDER_ENVIRONMENT_SPRING_RABBITMQ_P
ORT]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BinderProperties] for property 'binders[RABBITBINDER_ENVIRONMENT_SPRING
_RABBITMQ_PORT]': no matching editors or conversion strategy found
demographics_loader_1  |
demographics_loader_1  |
demographics_loader_1  | Action:
demographics_loader_1  |
demographics_loader_1  | Update your application's configuration
```

The environment variables for the database configuration work without any issues.
If I use an application-<profile>.yml with the correct settings like 

```
spring:
  cloud:
    stream:
      bindings:
        ...
      binders:
          rabbitbinder:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: rabbitmq
                  port: 5672
                  username: XXX
                  password: XXX

```

everything works as expected.
